import MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuFouvryG9TotalError
import MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuFouvryG9PositiveCover
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridIndex
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridIndex
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridIndex_bounds
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridIndex_bounds
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridIndex_mono
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridIndex_mono
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_label_bounds
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_label_bounds
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridKey
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridKey
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridUsed
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridUsed
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridBox
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridBox
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridKey_bounds
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridKey_bounds
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridUsed_subset
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridUsed_subset
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridUsed_card_le
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridUsed_card_le
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_card
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_card
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_log_window
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_log_window
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_one
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_one
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_scalar
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_scalar
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_total
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCost_total
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_mem_iff
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_mem_iff
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_nonempty_iff
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_nonempty_iff
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_rectangle
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_rectangle
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_long_le_two
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_long_le_two
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_scale_window
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_scale_window
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_sum
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_sum
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_card_sum
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridCell_card_sum
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongLabels
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongLabels
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongProducts
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongProducts
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_nonneg
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_nonneg
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_le_divisors
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_le_divisors
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_firstIndex_eq
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_firstIndex_eq
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_bounds
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongAlpha_bounds
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_sum
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_sum
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongProducts_bounds
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongProducts_bounds
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongProducts_le_two
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongProducts_le_two
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongLabels_of_cell
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongLabels_of_cell
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels_of_cell
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels_of_cell
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongRectCoordinates
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongRectCoordinates
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongRectCoordinates_injOn
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongRectCoordinates_injOn
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongRectCoordinates_subset
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongRectCoordinates_subset
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_cell_le_label_rectangle
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_cell_le_label_rectangle
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_cell_le_weighted_rectangle
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_cell_le_weighted_rectangle
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9PrimeHalfOpenInterval
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9PrimeHalfOpenInterval
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.mem_g9PrimeHalfOpenInterval
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.mem_g9PrimeHalfOpenInterval
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_short_endpoints
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_short_endpoints
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridPrimeInterval
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9GridPrimeInterval
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels_eq_interval
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels_eq_interval
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels_sum_interval
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9LongShortLabels_sum_interval
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_cell_le_prime_rectangle
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Long_cell_le_prime_rectangle
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_const_mul_rpow_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_const_mul_rpow_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_power_endpoints
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_power_endpoints
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_local_global
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_local_global
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_level_identity
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_level_identity
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_level_numerator
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_level_numerator
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_local_global_and_level
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_eventually_local_global_and_level
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_exists_threshold_local_global_and_level
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_exists_threshold_local_global_and_level
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.SignedWellFactorable.level_mono
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.SignedWellFactorable.level_mono
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_buffered_geometry
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_buffered_geometry
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_exists_buffered_C2_parameters
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Grid_exists_buffered_C2_parameters
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.SignedWellFactorable.factorSupported
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.SignedWellFactorable.factorSupported
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_level_eq_of_support
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_level_eq_of_support
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_levels_eq_of_support
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_levels_eq_of_support
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_global_level_ge_one
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.g9Scale_global_level_ge_one
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9RectangleError
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9RectangleError
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9RectangleError_uniform
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9RectangleError_uniform
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9RectangleError_total
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9RectangleError_total
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_positive_rectangle_cover
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_positive_rectangle_cover
