import MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuFouvryKGoldbachRectangle
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_aux_scale_rpow_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_aux_scale_rpow_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_eventually_tau_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_eventually_tau_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_eventually_signedError_bound
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_eventually_signedError_bound
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_divisorPart_power_saving
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_divisorPart_power_saving
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_signedError_log_payment
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_signedError_log_payment
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_smooth_error_scale_product_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_smooth_error_scale_product_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_alpha_sq_mul_smooth_envelopes_le_c2
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_alpha_sq_mul_smooth_envelopes_le_c2
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_eventually_smooth_error_log_payment
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_eventually_smooth_error_log_payment
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_alpha_sq_mul_smooth_envelopes_c2_log_payment
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_alpha_sq_mul_smooth_envelopes_c2_log_payment
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_dispersionUV_smooth_c2_log_payment
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_dispersionUV_smooth_c2_log_payment
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_dispersionUV_smooth_c2_dyadic_log_payment
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_dispersionUV_smooth_c2_dyadic_log_payment
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_signedError_sq_le_nonzeroMode_c2
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_signedError_sq_le_nonzeroMode_c2
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_signedError_sq_le_clean_nonzeroMode_c2
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kClean_signedError_sq_le_clean_nonzeroMode_c2
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeGCD_pair_mass_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeGCD_pair_mass_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.highOmega_shifted_tau_sum_le_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.highOmega_shifted_tau_sum_le_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kscale_log_cost
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kscale_log_cost
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeGCD_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeGCD_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_abs_le_largeGCD_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_abs_le_largeGCD_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedTruncated_largeGCD_power_saving_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedTruncated_largeGCD_power_saving_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_largeGCD_power_saving_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_largeGCD_power_saving_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_largeGCD_alpha_log_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_largeGCD_alpha_log_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_largeGCD_alpha_real_log_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedTruncated_largeGCD_alpha_real_log_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_largeGCD_dyadic_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_largeGCD_dyadic_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_clean_firstGCD_truncated_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_clean_firstGCD_truncated_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_highOmega_signedError_bound_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_highOmega_signedError_bound_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_highOmega_signedError_log_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_highOmega_signedError_log_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.highOmega_original_signedError_log_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.highOmega_original_signedError_log_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_firstGCD_truncated_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_firstGCD_truncated_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kDelta_natAbs_mul_sub_le_of_cutoff
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kDelta_natAbs_mul_sub_le_of_cutoff
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeDelta_pair_mass_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeDelta_pair_mass_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeDelta_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeDelta_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedOriginal_zero_largeDelta_power_saving_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedOriginal_zero_largeDelta_power_saving_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_largeDelta_dyadic_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_largeDelta_dyadic_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_twoGCD_truncated_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_twoGCD_truncated_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeSupport_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_largeSupport_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedOriginal_zero_largeSupport_power_saving_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedOriginal_zero_largeSupport_power_saving_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_largeSupport_dyadic_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_largeSupport_dyadic_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_twoGCD_support_truncated_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_twoGCD_support_truncated_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_modulus_support_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wMaskedOriginal_abs_le_modulus_support_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedOriginal_zero_modulus_support_power_saving_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.eventually_wMaskedOriginal_zero_modulus_support_power_saving_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kModSupport_eventually_level_le_long
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.kModSupport_eventually_level_le_long
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_modulus_support_dyadic_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_wMaskedTruncated_modulus_support_dyadic_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_five_small_truncated_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_lowOmega_five_small_truncated_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_modulusHighOmega_signedError_bound_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_modulusHighOmega_signedError_bound_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_modulusHighOmega_signedError_dyadic_bound_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_modulusHighOmega_signedError_dyadic_bound_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_modulusHighOmega_signedError_dyadic_log_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.betaClean_modulusHighOmega_signedError_dyadic_log_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.modulusHighOmega_signedError_dyadic_log_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.modulusHighOmega_signedError_dyadic_log_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.factorLowOmega_signedError_difference_payment_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.factorLowOmega_signedError_difference_payment_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_parameter_caps
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_parameter_caps
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_S_eq_zero
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_S_eq_zero
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_exponent_bounds
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_exponent_bounds
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_secondary_exponent_margin
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_secondary_exponent_margin
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_normalized_margins
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_normalized_margins
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_short_add_S_le_half
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_short_add_S_le_half
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_zero_monomial
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_zero_monomial
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_main_monomial
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_main_monomial
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_secondary_monomial
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_secondary_monomial
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_factor_levels
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.c2_extended_factor_levels
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_five_small_factored_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.signedError_sq_le_five_small_factored_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_five_small_factored_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_five_small_factored_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_five_small_extracted_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_five_small_extracted_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_floor_extracted_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_floor_extracted_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_floor_key_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_floor_key_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalytic_phase_budget_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalytic_phase_budget_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wExtractedFloorKey_phase_budget_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wExtractedFloorKey_phase_budget_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticDyadicBlock_parameter_budget_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticDyadicBlock_parameter_budget_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticGridWeight_variation_bound_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticGridWeight_variation_bound_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticDyadicWeightedBlock_norm_le_prefix_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticDyadicWeightedBlock_norm_le_prefix_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wExtractedFloorKeyExponential_norm_le_prefixes_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wExtractedFloorKeyExponential_norm_le_prefixes_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticVariationConstant_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wAnalyticVariationConstant_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_floor_prefix_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wellFactorable_signedError_sq_le_floor_prefix_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_max_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_max_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_abs_rpow_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_abs_rpow_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_loss_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_loss_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_bound
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_bound
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_uniform
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKMain_uniform
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKSecondary_tau
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKSecondary_tau
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKSecondary_growth_data
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKSecondary_growth_data
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKSecondary_weight_paid
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directPayKSecondary_weight_paid
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directJoinedKSecondary_uniform
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.directJoinedKSecondary_uniform
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_retained_cell_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_retained_cell_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wCoprimePairBound_extended_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.wCoprimePairBound_extended_le
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_key_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_key_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_total_prefix_cost_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_total_prefix_cost_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_wellFactorable_signedError_sq_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_wellFactorable_signedError_sq_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_wellFactorable_signedError_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.direct_wellFactorable_signedError_kscale
#check @MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_goldbach_rectangle_kscale
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_goldbach_rectangle_kscale
