import MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuFouvryGoldbachRectangle
import MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuFouvryPrimeC2
import MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuFouvryG9Discrepancy
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_deleted_subset
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_deleted_subset
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_deleted_card_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_deleted_card_le
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWBeta_nonneg
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWBeta_nonneg
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_primeFactors_le_tau
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_primeFactors_le_tau
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_eq_card
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_eq_card
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_nonneg
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_nonneg
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_sieve_sub
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_sieve_sub
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_sieve_abs_sub_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_sieve_abs_sub_le
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_sieve_discrepancy_sub_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_sieve_discrepancy_sub_le
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_discrepancy_one
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_discrepancy_one
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_mono
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_mono
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_discrepancy_eq
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_discrepancy_eq
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_le_card
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_le_card
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_discrepancy_le_card
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_discrepancy_le_card
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_small_prefix
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_small_prefix
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_Ioc
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWSum_Ioc
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWInterval_AP_eq_sub
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWInterval_AP_eq_sub
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_primesInAP_mod
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_primesInAP_mod
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_error_le_prefix
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_error_le_prefix
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_interval_li_bound
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_interval_li_bound
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_tau_two_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_tau_two_le
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_interval_discrepancy_bound
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_interval_discrepancy_bound
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_reciprocal_totient
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_reciprocal_totient
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_AP_count_le
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_AP_count_le
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_large_modulus_envelope
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_large_modulus_envelope
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_log_rpow_eventually
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_log_rpow_eventually
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_log_cutoff_eventually
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_log_cutoff_eventually
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_large_log_bound
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_large_log_bound
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_uniform_eventually
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_uniform_eventually
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_floor_log_comparison
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_floor_log_comparison
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_interval_card_bound
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_interval_card_bound
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_uniform_real
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_uniform_real
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_BetaCoprimeSWFamily
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSW_BetaCoprimeSWFamily
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2Interval_support
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2Interval_support
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWBeta_le_order_one
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWBeta_le_order_one
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_unconditional
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_unconditional
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWBeta_clean_nat
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeSWBeta_clean_nat
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_clean_family
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_clean_family
#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_clean_unconditional
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_clean_unconditional
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Coordinates_injOn
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Coordinates_injOn
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_sum_reindex
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_sum_reindex
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Carrier_geometry
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Carrier_geometry
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Multiplicity_le_divisors
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Multiplicity_le_divisors
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Discrepancy_eq_reindexed
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Discrepancy_eq_reindexed
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_output_dvd_iff
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_output_dvd_iff
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_actual_divisor_count
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9_actual_divisor_count
#check MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Multiplicity_le_tau_two
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.fouvryG9Multiplicity_le_tau_two

#check MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_goldbach_rectangle
#print axioms MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_goldbach_rectangle
