import MathlibNt.SieveTheory.LiLiuGoldbachWeightAllRetainedEndpointsConsumed
import MathlibNt.SieveTheory.LiLiuGoldbachB10RetainedEndpoints
import MathlibNt.SieveTheory.LiLiuGoldbachS4RetainedEndpoints
import MathlibNt.SieveTheory.LiLiuGoldbachB10IntegralScalarUpper

set_option pp.deepTerms true
set_option pp.proofs true
set_option pp.maxSteps 1000000

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.goldbachB10I10_eight_mul_le_540995781
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.goldbachB10I10_eight_mul_le_540995781

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.goldbachB10SiftedCount_540995781_upper
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.goldbachB10SiftedCount_540995781_upper

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.retained_scalar_gain
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.retained_scalar_gain

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.retained_scalar_strict_improvement
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.B10Retained.retained_scalar_strict_improvement

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.goldbachB8MainIntegral_eight_mul_le_60961168
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.goldbachB8MainIntegral_eight_mul_le_60961168

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.goldbachS4_normalized_upper_60961168
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.goldbachS4_normalized_upper_60961168

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.retained_scalar_gain
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.retained_scalar_gain

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.retained_scalar_strict_improvement
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.S4Retained.retained_scalar_strict_improvement

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachB10I10_eight_mul_le_540996
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachB10I10_eight_mul_le_540996

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachB10SiftedCount_540996_upper
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachB10SiftedCount_540996_upper

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachB8MainIntegral_eight_mul_le_60962
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachB8MainIntegral_eight_mul_le_60962

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachS4_normalized_upper_60962
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachS4_normalized_upper_60962

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeightFiveCoefficient_zero_ge_allRetained
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeightFiveCoefficient_zero_ge_allRetained
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_allRetained_small_epsilon
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_allRetained_small_epsilon
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_allRetainedUniform_consumed_small_epsilon
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_allRetainedUniform_consumed_small_epsilon