import MathlibNt.SieveTheory.LiLiuGoldbachB10PanPrefixes

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check goldbachC10CoeffReal
#check goldbachC10CoeffReal_eq_one_of_mem_productSupport
#check abs_goldbachC10CoeffReal_le_one
#check goldbachC10CoeffReal_ne_zero_iff
#check goldbachC10CoeffReal_ne_zero_imp_one_lt
#check goldbachC10CoeffReal_ne_zero_imp_coprime
#check goldbachB10ProductQFiber_card_eq_primePrefix_sub
#check goldbachB10ProductResidueQFiber_card_eq_primePrefix_sub
#check goldbachB10PanAPPrefixCount
#check goldbachB10DivisorAtoms_card_eq_panAPPrefixCount_sub
#check goldbachB10PanKappa0
#check goldbachB10PanMainPrefix
#check goldbachB10PanPrefixRemainder
#check liuMainPanCoprimeIntervalSum_eq_prefixCount_sub_mainPrefix
#check goldbachB10PanPrefixRemainder_eq_panErrors_sub
#check abs_goldbachB10PanPrefixRemainder_le

#print axioms goldbachC10CoeffReal_eq_one_of_mem_productSupport
#print axioms abs_goldbachC10CoeffReal_le_one
#print axioms goldbachC10CoeffReal_ne_zero_iff
#print axioms goldbachC10CoeffReal_ne_zero_imp_one_lt
#print axioms goldbachC10CoeffReal_ne_zero_imp_coprime
#print axioms goldbachB10ProductQFiber_card_eq_primePrefix_sub
#print axioms goldbachB10ProductResidueQFiber_card_eq_primePrefix_sub
#print axioms goldbachB10DivisorAtoms_card_eq_panAPPrefixCount_sub
#print axioms liuMainPanCoprimeIntervalSum_eq_prefixCount_sub_mainPrefix
#print axioms goldbachB10PanPrefixRemainder_eq_panErrors_sub
#print axioms abs_goldbachB10PanPrefixRemainder_le