import MathlibNt.SieveTheory.LiLiuGoldbachWeightRemainingEight
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachWeightRemainingEight
#check goldbachWeightTwelveBase_eq_positivePair_sub_s2_add_remainingEight
#check goldbachWeight_remainingEight_S1_S2_I10_consumed_eventually
#print axioms goldbachWeightRemainingEight
#print axioms goldbachWeightTwelveBase_eq_positivePair_sub_s2_add_remainingEight
#print axioms goldbachWeight_remainingEight_S1_S2_I10_consumed_eventually