import MathlibNt.SieveTheory.LiLiuGoldbachWeightG11IntegralConsumed

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11NormalizedIntegral_logError_paid
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11NormalizedIntegral_envelope_loss
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11NormalizedIntegral_choose_loss
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11NormalizedIntegral_envelope

#print axioms goldbachG11NormalizedIntegral_logError_paid
#print axioms goldbachG11NormalizedIntegral_envelope_loss
#print axioms goldbachG11NormalizedIntegral_choose_loss
#print axioms goldbachG11NormalizedIntegral_envelope
#print axioms goldbachWeightG11_le_normalizedIntegral
#print axioms goldbachWeightG11_le_normalizedIntegral_one
#print axioms goldbachWeight_g11NormalizedIntegral_consumed
#print axioms goldbachWeight_g11NormalizedIntegral_one_consumed
#check goldbachWeightG11_le_normalizedIntegral
#check goldbachWeightG11_le_normalizedIntegral_one
#check goldbachWeight_g11NormalizedIntegral_consumed
#check goldbachWeight_g11NormalizedIntegral_one_consumed