import MathlibNt.SieveTheory.LiLiuGoldbachS1LowerRosser
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachS1Endpoint
#print axioms goldbachS1Endpoint
#check goldbachS1SiftingPrimes
#print axioms goldbachS1SiftingPrimes
#check goldbachS1ProdPrimes
#print axioms goldbachS1ProdPrimes
#check mem_goldbachS1SiftingPrimes_iff
#print axioms mem_goldbachS1SiftingPrimes_iff
#check goldbachS1ProdPrimes_squarefree
#print axioms goldbachS1ProdPrimes_squarefree
#check goldbachS1ProdPrimes_ne_zero
#print axioms goldbachS1ProdPrimes_ne_zero
#check goldbachS1ProdPrimes_primeFactors
#print axioms goldbachS1ProdPrimes_primeFactors
#check prime_dvd_goldbachS1ProdPrimes_iff
#print axioms prime_dvd_goldbachS1ProdPrimes_iff
#check goldbachS1ProdPrimes_coprime_N
#print axioms goldbachS1ProdPrimes_coprime_N
#check goldbachS1_dvd_prodPrimes_coprime_N
#print axioms goldbachS1_dvd_prodPrimes_coprime_N
#check goldbachS1Endpoint_le
#print axioms goldbachS1Endpoint_le
#check goldbachS1Endpoint_add_one
#print axioms goldbachS1Endpoint_add_one
#check mem_goldbachPrimeCarrier_iff_prime_le_goldbachS1Endpoint
#print axioms mem_goldbachPrimeCarrier_iff_prime_le_goldbachS1Endpoint
#check goldbachS1_coprime_prodPrimes_iff_literalHPoint
#print axioms goldbachS1_coprime_prodPrimes_iff_literalHPoint
#check goldbachS1_mod_mem_unitResidues
#print axioms goldbachS1_mod_mem_unitResidues
#check goldbachS1BoundingSieve
#print axioms goldbachS1BoundingSieve
#check goldbachS1BoundingSieve_multSum_eq_primesInAP
#print axioms goldbachS1BoundingSieve_multSum_eq_primesInAP
#check goldbachS1BoundingSieve_siftedSum_eq
#print axioms goldbachS1BoundingSieve_siftedSum_eq
#check goldbachS1BoundingSieve_nu_eq_inv_totient
#print axioms goldbachS1BoundingSieve_nu_eq_inv_totient
#check goldbachS1BoundingSieve_mainSum_eq_totientSum
#print axioms goldbachS1BoundingSieve_mainSum_eq_totientSum
#check goldbachS1BoundingSieve_rem_eq_standardPrimeAPError
#print axioms goldbachS1BoundingSieve_rem_eq_standardPrimeAPError
#check goldbachS1BoundingSieve_lowerErrSum_le_prefixSum
#print axioms goldbachS1BoundingSieve_lowerErrSum_le_prefixSum
#check goldbachS1_lowerRosser_mainTerm_sub_prefix_le
#print axioms goldbachS1_lowerRosser_mainTerm_sub_prefix_le