import MathlibNt.SieveTheory.LiLiuGoldbachG11ActiveProductGeometry
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachG11_active_product_bounds
#print axioms goldbachG11_active_product_bounds