import MathlibNt.SieveTheory.LiLiuGoldbachS1LowerDensitySix

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check goldbachS1_levelSix_lowerDensitySix
#print axioms goldbachS1_levelSix_lowerDensitySix