import MathlibNt.SieveTheory.LiLiuGoldbachG11EffectiveProductSupport
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachG11_product_active_bounds
#print axioms goldbachG11_product_active_bounds
#check goldbachG11EffectiveProductSupport
#print axioms goldbachG11EffectiveProductSupport
#check goldbachG11ProductFirstPrimeFiber_eq_empty_of_inactive
#print axioms goldbachG11ProductFirstPrimeFiber_eq_empty_of_inactive
#check goldbachG11GoodSwitchedTotal_eq_effective_product_sum
#print axioms goldbachG11GoodSwitchedTotal_eq_effective_product_sum
#check goldbachG11EffectiveProductCoefficient
#print axioms goldbachG11EffectiveProductCoefficient
#check goldbachG11EffectiveProductCoefficient_bounds
#print axioms goldbachG11EffectiveProductCoefficient_bounds
#check goldbachG11EffectiveProductCoefficient_support
#print axioms goldbachG11EffectiveProductCoefficient_support
#check goldbachG11GoodSwitchedTotal_eq_effective_normalized_sum
#print axioms goldbachG11GoodSwitchedTotal_eq_effective_normalized_sum