import MathlibNt.SieveTheory.LiLiuGoldbachB8PaidUpper

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check exists_goldbachB8PlusBoundingSieve_dimensionOneLocalProductBound
#check goldbachB8Plus_upperRosserWeight_certificate
#check goldbachB8PlusSiftedCount_le_rosserFactor_add_upperErrSum
#check goldbachB8Plus_upperErrSum_le_sieveDivisorSum
#check goldbachB8Plus_floor_paidLevel_le_panModulusCutoff
#check goldbachB8Plus_upperErrSum_log_saving
#check goldbachB8PlusSiftedCount_upper_paid

#print axioms exists_goldbachB8PlusBoundingSieve_dimensionOneLocalProductBound
#print axioms goldbachB8Plus_upperRosserWeight_certificate
#print axioms goldbachB8PlusSiftedCount_le_rosserFactor_add_upperErrSum
#print axioms goldbachB8Plus_upperErrSum_le_sieveDivisorSum
#print axioms goldbachB8Plus_floor_paidLevel_le_panModulusCutoff
#print axioms goldbachB8Plus_upperErrSum_log_saving
#print axioms goldbachB8PlusSiftedCount_upper_paid