import MathlibNt.SieveTheory.LiLiuGoldbachWeightTwelve
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check mem_goldbachC10Pairs_iff
#check goldbachG10Corrected_eq_card_atoms
#check mem_goldbachG10CorrectedAtoms_iff
#check mem_goldbachG10ActualAtoms_iff
#check mem_goldbachDifferenceCarrier_iff_exists
#check goldbachDifferenceCarrier_prime_data
#check goldbachG10DifferenceCarrier_bounds
#check mem_goldbachG10BadActualAtoms_iff
#check mem_goldbachG10NonbadActualAtoms_iff
#check mem_goldbachG10RSquareActualAtoms_iff
#check mem_goldbachG10NoRSquareActualAtoms_iff
#check mem_goldbachG10SSquareActualAtoms_iff
#check mem_goldbachG10GoodActualAtoms_iff
#check goldbachG10ActualAtom_eq_prod_mul_cofactor
#check goldbachG10ActualAtom_fst_mem_largePrimeDivisors
#check goldbachG10ActualAtom_snd_mem_largePrimeDivisors
#check goldbachPi10_eq_card_atoms
#check mem_goldbachPi10Atoms_iff
#check goldbachG10GoodActualAtom_pair_ne
#check goldbachG10Cofactor_coprime
#check goldbachG10Cofactor_primeDivisor_ge_cutoff
#check goldbachG10Cofactor_prime_of_lt_sq
#check goldbachG10Cofactor_prime
#check goldbachG10GoodActualAtoms_card_le_goldbachPi10
#check goldbachWeightT16_nonneg
#check goldbachS5Closed_eq_sum_goldbachC10Pairs
#check goldbachC10Pair_cell_le_goldbachG10CorrectedCell_add_t16Slice
#check goldbachS5Closed_le_goldbachG10Corrected_add_goldbachWeightT16
#check goldbachT16Coverage_pointwise_geometry
#check goldbachT16Coverage_pointwise_membership
#check goldbachWeightT16_le_explicitClosedPrimeTripleSum
#check goldbachG10BadActualAtoms_le_four_hundred_badCount
#check goldbachG10RSquareActualAtoms_le_twenty_mul_goldbachQA
#check goldbachG10SSquareActualAtoms_le_twenty_mul_goldbachQA
#check goldbachG10Corrected_actual_le_pi10_with_errors
#check exists_goldbachG10SwitchFinite_cutoff
#check goldbachG10Corrected_actual_eventually_le_pi10_with_errors
#check goldbachG10SwitchErrors_le_880
#check goldbachG10Corrected_eventually_le_pi10_add_880
#check goldbachS4Pairs_eq_empty_of_cube_bound
#check goldbachS4_cube_cutoff_eq_zero
#check goldbachWeight_three_triples_le_s6_add_b6
#check goldbachWeight_twelve_corrected_lower_bound_eventually
#check goldbachWeight_twelve_switched_lower_bound_eventually
#print axioms mem_goldbachC10Pairs_iff
#print axioms goldbachG10Corrected_eq_card_atoms
#print axioms mem_goldbachG10CorrectedAtoms_iff
#print axioms mem_goldbachG10ActualAtoms_iff
#print axioms mem_goldbachDifferenceCarrier_iff_exists
#print axioms goldbachDifferenceCarrier_prime_data
#print axioms goldbachG10DifferenceCarrier_bounds
#print axioms mem_goldbachG10BadActualAtoms_iff
#print axioms mem_goldbachG10NonbadActualAtoms_iff
#print axioms mem_goldbachG10RSquareActualAtoms_iff
#print axioms mem_goldbachG10NoRSquareActualAtoms_iff
#print axioms mem_goldbachG10SSquareActualAtoms_iff
#print axioms mem_goldbachG10GoodActualAtoms_iff
#print axioms goldbachG10ActualAtom_eq_prod_mul_cofactor
#print axioms goldbachG10ActualAtom_fst_mem_largePrimeDivisors
#print axioms goldbachG10ActualAtom_snd_mem_largePrimeDivisors
#print axioms goldbachPi10_eq_card_atoms
#print axioms mem_goldbachPi10Atoms_iff
#print axioms goldbachG10GoodActualAtom_pair_ne
#print axioms goldbachG10Cofactor_coprime
#print axioms goldbachG10Cofactor_primeDivisor_ge_cutoff
#print axioms goldbachG10Cofactor_prime_of_lt_sq
#print axioms goldbachG10Cofactor_prime
#print axioms goldbachG10GoodActualAtoms_card_le_goldbachPi10
#print axioms goldbachWeightT16_nonneg
#print axioms goldbachS5Closed_eq_sum_goldbachC10Pairs
#print axioms goldbachC10Pair_cell_le_goldbachG10CorrectedCell_add_t16Slice
#print axioms goldbachS5Closed_le_goldbachG10Corrected_add_goldbachWeightT16
#print axioms goldbachT16Coverage_pointwise_geometry
#print axioms goldbachT16Coverage_pointwise_membership
#print axioms goldbachWeightT16_le_explicitClosedPrimeTripleSum
#print axioms goldbachG10BadActualAtoms_le_four_hundred_badCount
#print axioms goldbachG10RSquareActualAtoms_le_twenty_mul_goldbachQA
#print axioms goldbachG10SSquareActualAtoms_le_twenty_mul_goldbachQA
#print axioms goldbachG10Corrected_actual_le_pi10_with_errors
#print axioms exists_goldbachG10SwitchFinite_cutoff
#print axioms goldbachG10Corrected_actual_eventually_le_pi10_with_errors
#print axioms goldbachG10SwitchErrors_le_880
#print axioms goldbachG10Corrected_eventually_le_pi10_add_880
#print axioms goldbachS4Pairs_eq_empty_of_cube_bound
#print axioms goldbachS4_cube_cutoff_eq_zero
#print axioms goldbachWeight_three_triples_le_s6_add_b6
#print axioms goldbachWeight_twelve_corrected_lower_bound_eventually
#print axioms goldbachWeight_twelve_switched_lower_bound_eventually