import MathlibNt.SieveTheory.LiLiuGoldbachWeightG11GoodConsumed
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#print goldbachWeightG11GoodRemainder
#check goldbachWeightG11GoodRemainder
#print axioms goldbachWeightG11GoodRemainder
#check goldbachG11RoughTotal_le_goodSwitched_normalized
#print axioms goldbachG11RoughTotal_le_goodSwitched_normalized
#check goldbachWeightG11_le_goodSwitched_normalized
#print axioms goldbachWeightG11_le_goodSwitched_normalized
#check goldbachWeight_g11GoodSwitched_consumed_eventually
#print axioms goldbachWeight_g11GoodSwitched_consumed_eventually
#check goldbachWeight_g11GoodSwitched_consumed_small_epsilon
#print axioms goldbachWeight_g11GoodSwitched_consumed_small_epsilon