import MathlibNt.SieveTheory.LiLiuGoldbachB10ProductCount
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check mem_goldbachC10ProductSupport_iff
#print axioms mem_goldbachC10ProductSupport_iff
#check goldbachC10Coeff_eq_one_of_mem_productSupport
#print axioms goldbachC10Coeff_eq_one_of_mem_productSupport
#check goldbachC10_sum_nat_eq_sum_productSupport
#print axioms goldbachC10_sum_nat_eq_sum_productSupport
#check goldbachC10_sum_int_eq_sum_productSupport
#print axioms goldbachC10_sum_int_eq_sum_productSupport
#check mem_goldbachB10ProductQFiber_iff
#print axioms mem_goldbachB10ProductQFiber_iff
#check goldbachB10Fiber_eq_productQFiber
#print axioms goldbachB10Fiber_eq_productQFiber
#check goldbachB10Atoms_card_eq_sum_productSupport
#print axioms goldbachB10Atoms_card_eq_sum_productSupport
#check goldbachB10SiftedFiber_eq_productSiftedQFiber
#print axioms goldbachB10SiftedFiber_eq_productSiftedQFiber
#check goldbachB10SiftedCount_eq_sum_productSupport
#print axioms goldbachB10SiftedCount_eq_sum_productSupport
#check goldbachB10ProductResidueQFiber_eq_filter
#print axioms goldbachB10ProductResidueQFiber_eq_filter
#check mem_goldbachB10ProductResidueQFiber_iff
#print axioms mem_goldbachB10ProductResidueQFiber_iff
#check goldbachB10DivisorAtoms_card_eq_sum_productSupport
#print axioms goldbachB10DivisorAtoms_card_eq_sum_productSupport
#check goldbachC10ProductSupport_pos
#print axioms goldbachC10ProductSupport_pos
#check goldbachC10ProductSupport_le_rpow_half_and_lt_two_thirds
#print axioms goldbachC10ProductSupport_le_rpow_half_and_lt_two_thirds