import MathlibNt.SieveTheory.LiLiuGoldbachWeightRemainingFive
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachWeightRemainingFive
#print axioms goldbachWeightRemainingFive
#check goldbachWeightRemainingSix_eq_remainingFive_sub_two_s4
#print axioms goldbachWeightRemainingSix_eq_remainingFive_sub_two_s4
#check goldbachWeightFiveCoefficient
#print axioms goldbachWeightFiveCoefficient
#check goldbachWeight_remainingFive_S1_S2_S3_S4_I10_consumed_eventually
#print axioms goldbachWeight_remainingFive_S1_S2_S3_S4_I10_consumed_eventually
#check goldbachWeight_remainingFive_small_epsilon
#print axioms goldbachWeight_remainingFive_small_epsilon