import MathlibNt.SieveTheory.LiLiuPanBoundedAggregate

open MathlibNt.SieveTheory.LiuWeight

#check liuMainPanCoprimeIntervalMaxL_boundedAggregate_log_saving

#print axioms liuMainPanCoprimeIntervalMaxL_boundedAggregate_log_saving