import MathlibNt.SieveTheory.LiLiuGoldbachPreG11FinalLedger
import MathlibNt.SieveTheory.LiLiuGoldbachConditionalFinalAssembly

set_option pp.deepTerms true
set_option pp.maxSteps 1000000
set_option pp.universes true
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_preG11_allRetained_small_epsilon
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach_paperG11_budget_identity
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_small_epsilon_lower_with_error_of_actual_estimates
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_small_epsilon_lower_of_actual_estimates
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_eventually_lower_of_actual_estimates
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach19_eventually_representation_of_actual_estimates
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_eventually_lower_of_g11_le_10191
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach19_eventually_representation_of_g11_le_10191
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11_uniformScalar_fits_finalAssembly

set_option pp.universes false
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_preG11_allRetained_small_epsilon
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach_paperG11_budget_identity
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_small_epsilon_lower_with_error_of_actual_estimates
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_small_epsilon_lower_of_actual_estimates
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_eventually_lower_of_actual_estimates
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach19_eventually_representation_of_actual_estimates
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachD19_eventually_lower_of_g11_le_10191
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach19_eventually_representation_of_g11_le_10191
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11_uniformScalar_fits_finalAssembly