import MathlibNt.SieveTheory.LiLiuGoldbachB10PanDistribution
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachB10PanPrefixRemainder_log_saving
#print axioms goldbachB10PanPrefixRemainder_log_saving