import MathlibNt.SieveTheory.LiLiuGoldbachUpperThirdInterval
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbach_lowerFactor_continuousOn_four_six
#print axioms goldbach_lowerFactor_continuousOn_four_six
#check goldbachUpperThirdIntervalFactor
#print axioms goldbachUpperThirdIntervalFactor
#check goldbach_suzukiUpperFactor_eq_third
#print axioms goldbach_suzukiUpperFactor_eq_third
#check goldbachUpperThirdIntervalFactor_continuousOn
#print axioms goldbachUpperThirdIntervalFactor_continuousOn
#check goldbach_suzukiUpperFactor_continuousOn_threeHalves_seven
#print axioms goldbach_suzukiUpperFactor_continuousOn_threeHalves_seven
#check goldbach_one_le_suzukiUpperFactor
#print axioms goldbach_one_le_suzukiUpperFactor