import MathlibNt.SieveTheory.LiLiuGoldbachS2SwitchedDistribution

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check goldbachS2SwitchedLabels
#check mem_goldbachS2SwitchedLabels_iff
#check goldbachS2SwitchedOutput
#check goldbachS2SwitchedOutput_eq_sub
#check goldbachS2SwitchedAtom_prod_lt
#check goldbachS2SwitchedAtom_prod_add_output
#check goldbachS2SwitchedAtom_output_dvd_iff_modEq
#check goldbachS2SwitchedDivisorResidueCondition
#check goldbachS2SwitchedAtom_left_coprime_of_coprime_modulus
#check goldbachS2SwitchedAtom_output_dvd_iff_residueCondition
#check goldbachS2SwitchedDivisorLabels
#check mem_goldbachS2SwitchedDivisorLabels_iff
#check goldbachS2SwitchedDivisorLabels_eq_residueFilter
#check goldbachS2SwitchedSupport
#check mem_goldbachS2SwitchedSupport_iff
#check goldbachS2SwitchedWeight
#check goldbachS2SwitchedSiftedLabels
#check mem_goldbachS2SwitchedSiftedLabels_iff
#check goldbachS2SwitchedSiftedCount
#check goldbachS2SwitchedDivCount
#check goldbachS2SwitchedMainMass
#check goldbachS2SwitchedMainMass_nonneg
#check goldbachS2SwitchedWeight_sum_eq_card_labels
#check goldbachS2SwitchedWeight_nonneg
#check goldbachS2Switched_coprime_prodPrimes_iff_survivesSieve
#check goldbachS2SwitchedBoundingSieve
#check goldbachS2SwitchedBoundingSieve_multSum_eq_divCount
#check goldbachS2SwitchedBoundingSieve_siftedSum_eq
#check goldbachS2SwitchedBoundingSieve_nu_eq_inv_totient
#check goldbachS2SwitchedBoundingSieve_mainSum_eq_totientSum
#check goldbachS2SwitchedBoundingSieve_rem_eq_divCount_sub
#check goldbachS2SwitchedSmallPartnerLoss
#check goldbachS2PrimePairs_card_le_switchedSiftedCount_add_smallPartnerLoss
#check goldbachS2SwitchedSmallPartnerLoss_le_ceil
#check goldbachS2PrimePairs_card_le_switchedSiftedCount_add_ceil
#check goldbachS2_le_switchedSiftedCount_add_smallPartnerLoss_add_primeFactors
#check goldbachS2_le_switchedSiftedCount_add_ceil_add_primeFactors
#check goldbachS2_le_switchedSiftedCount_add_smallPartnerLoss_add_primeFactors_eventually
#check goldbachS2_le_switchedSiftedCount_add_ceil_add_primeFactors_eventually

#check goldbachS2SwitchedCoeff
#check goldbachS2SwitchedCoeff_eq_one_of_mem
#check goldbachS2SwitchedCoeff_eq_zero_of_not_mem
#check abs_goldbachS2SwitchedCoeff_le_one
#check goldbachS2SwitchedGatedMainMass
#check goldbachS2SwitchedRemainder
#check goldbachS2SwitchedPanAPPrefixCount
#check goldbachS2SwitchedPanMainPrefix
#check goldbachS2SwitchedDivCount_eq_panAPPrefixCount
#check goldbachS2SwitchedPanMainPrefix_eq_div_gatedMainMass
#check liuMainPanCoprimeIntervalSum_eq_goldbachS2SwitchedPrefixCount_sub_mainPrefix
#check goldbachS2SwitchedRemainder_eq_panError
#check goldbachS2SwitchedRemainder_log_saving
#check goldbachS2SwitchedGatedMainMass_eq_mainMass_of_dvd_prodPrimes
#check goldbachS2SwitchedBoundingSieve_rem_eq_remainder_of_dvd_prodPrimes

#print axioms goldbachS2SwitchedLabels
#print axioms mem_goldbachS2SwitchedLabels_iff
#print axioms goldbachS2SwitchedOutput
#print axioms goldbachS2SwitchedOutput_eq_sub
#print axioms goldbachS2SwitchedAtom_prod_lt
#print axioms goldbachS2SwitchedAtom_prod_add_output
#print axioms goldbachS2SwitchedAtom_output_dvd_iff_modEq
#print axioms goldbachS2SwitchedDivisorResidueCondition
#print axioms goldbachS2SwitchedAtom_left_coprime_of_coprime_modulus
#print axioms goldbachS2SwitchedAtom_output_dvd_iff_residueCondition
#print axioms goldbachS2SwitchedDivisorLabels
#print axioms mem_goldbachS2SwitchedDivisorLabels_iff
#print axioms goldbachS2SwitchedDivisorLabels_eq_residueFilter
#print axioms goldbachS2SwitchedSupport
#print axioms mem_goldbachS2SwitchedSupport_iff
#print axioms goldbachS2SwitchedWeight
#print axioms goldbachS2SwitchedSiftedLabels
#print axioms mem_goldbachS2SwitchedSiftedLabels_iff
#print axioms goldbachS2SwitchedSiftedCount
#print axioms goldbachS2SwitchedDivCount
#print axioms goldbachS2SwitchedMainMass
#print axioms goldbachS2SwitchedMainMass_nonneg
#print axioms goldbachS2SwitchedWeight_sum_eq_card_labels
#print axioms goldbachS2SwitchedWeight_nonneg
#print axioms goldbachS2Switched_coprime_prodPrimes_iff_survivesSieve
#print axioms goldbachS2SwitchedBoundingSieve
#print axioms goldbachS2SwitchedBoundingSieve_multSum_eq_divCount
#print axioms goldbachS2SwitchedBoundingSieve_siftedSum_eq
#print axioms goldbachS2SwitchedBoundingSieve_nu_eq_inv_totient
#print axioms goldbachS2SwitchedBoundingSieve_mainSum_eq_totientSum
#print axioms goldbachS2SwitchedBoundingSieve_rem_eq_divCount_sub
#print axioms goldbachS2SwitchedSmallPartnerLoss
#print axioms goldbachS2PrimePairs_card_le_switchedSiftedCount_add_smallPartnerLoss
#print axioms goldbachS2SwitchedSmallPartnerLoss_le_ceil
#print axioms goldbachS2PrimePairs_card_le_switchedSiftedCount_add_ceil
#print axioms goldbachS2_le_switchedSiftedCount_add_smallPartnerLoss_add_primeFactors
#print axioms goldbachS2_le_switchedSiftedCount_add_ceil_add_primeFactors
#print axioms goldbachS2_le_switchedSiftedCount_add_smallPartnerLoss_add_primeFactors_eventually
#print axioms goldbachS2_le_switchedSiftedCount_add_ceil_add_primeFactors_eventually

#print axioms goldbachS2SwitchedCoeff
#print axioms goldbachS2SwitchedCoeff_eq_one_of_mem
#print axioms goldbachS2SwitchedCoeff_eq_zero_of_not_mem
#print axioms abs_goldbachS2SwitchedCoeff_le_one
#print axioms goldbachS2SwitchedGatedMainMass
#print axioms goldbachS2SwitchedRemainder
#print axioms goldbachS2SwitchedPanAPPrefixCount
#print axioms goldbachS2SwitchedPanMainPrefix
#print axioms goldbachS2SwitchedDivCount_eq_panAPPrefixCount
#print axioms goldbachS2SwitchedPanMainPrefix_eq_div_gatedMainMass
#print axioms liuMainPanCoprimeIntervalSum_eq_goldbachS2SwitchedPrefixCount_sub_mainPrefix
#print axioms goldbachS2SwitchedRemainder_eq_panError
#print axioms goldbachS2SwitchedRemainder_log_saving
#print axioms goldbachS2SwitchedGatedMainMass_eq_mainMass_of_dvd_prodPrimes
#print axioms goldbachS2SwitchedBoundingSieve_rem_eq_remainder_of_dvd_prodPrimes