import MathlibNt.SieveTheory.LiLiuGoldbachG11ProductGrouping

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check goldbachG11SwitchedBodyProd_minFac
#print axioms goldbachG11SwitchedBodyProd_minFac
#check goldbachG11ProductSupport
#print axioms goldbachG11ProductSupport
#check goldbachG11ProductFiber
#print axioms goldbachG11ProductFiber
#check goldbachG11ProductCoefficient
#print axioms goldbachG11ProductCoefficient
#check mem_goldbachG11ProductSupport_iff
#print axioms mem_goldbachG11ProductSupport_iff
#check mem_goldbachG11ProductFiber_iff
#print axioms mem_goldbachG11ProductFiber_iff
#check goldbachG11ProductSupport_data
#print axioms goldbachG11ProductSupport_data
#check goldbachG11ProductFiber_nonempty_iff
#print axioms goldbachG11ProductFiber_nonempty_iff
#check goldbachG11ProductCoefficient_pos_iff
#print axioms goldbachG11ProductCoefficient_pos_iff
#check goldbachG11ProductCoefficient_eq_zero_iff
#print axioms goldbachG11ProductCoefficient_eq_zero_iff
#check goldbachG11ProductCoefficient_eq_zero_of_not_mem
#print axioms goldbachG11ProductCoefficient_eq_zero_of_not_mem
#check goldbachG11ProductCoordinates
#print axioms goldbachG11ProductCoordinates
#check goldbachG11ProductCoordinates_injOn
#print axioms goldbachG11ProductCoordinates_injOn
#check goldbachG11ProductCoordinates_mem_largePrimeDivisors
#print axioms goldbachG11ProductCoordinates_mem_largePrimeDivisors
#check goldbachG11ProductCoefficient_le_four_hundred
#print axioms goldbachG11ProductCoefficient_le_four_hundred
#check goldbachG11NormalizedProductCoefficient
#print axioms goldbachG11NormalizedProductCoefficient
#check goldbachG11NormalizedProductCoefficient_nonneg
#print axioms goldbachG11NormalizedProductCoefficient_nonneg
#check goldbachG11NormalizedProductCoefficient_le_one
#print axioms goldbachG11NormalizedProductCoefficient_le_one
#check goldbachG11NormalizedProductCoefficient_mul_four_hundred
#print axioms goldbachG11NormalizedProductCoefficient_mul_four_hundred
#check goldbachG11NormalizedProductCoefficient_eq_zero_of_not_mem
#print axioms goldbachG11NormalizedProductCoefficient_eq_zero_of_not_mem
#check goldbachG11ProductFirstPrimeFiber
#print axioms goldbachG11ProductFirstPrimeFiber
#check mem_goldbachG11ProductFirstPrimeFiber_iff
#print axioms mem_goldbachG11ProductFirstPrimeFiber_iff
#check goldbachG11FirstPrimeFiber_eq_product
#print axioms goldbachG11FirstPrimeFiber_eq_product
#check goldbachG11FirstPrimeFiber_eq_product_of_mem
#print axioms goldbachG11FirstPrimeFiber_eq_product_of_mem
#check goldbachG11GoodSwitchedBodies_sum_product
#print axioms goldbachG11GoodSwitchedBodies_sum_product
#check goldbachG11GoodSwitchedTotal_eq_product_sum
#print axioms goldbachG11GoodSwitchedTotal_eq_product_sum
#check goldbachG11GoodSwitchedTotal_eq_canonical_product_sum
#print axioms goldbachG11GoodSwitchedTotal_eq_canonical_product_sum

#check goldbachG11_body_minFac
#print axioms goldbachG11_body_minFac
#check largePrimeDivisors
#print axioms largePrimeDivisors
#check largePrimeDivisors_card_le_twenty
#print axioms largePrimeDivisors_card_le_twenty
#check goldbachG11GoodSwitchedTotal
#print axioms goldbachG11GoodSwitchedTotal