import MathlibNt.SieveTheory.LiLiuGoldbachWeightS4ScalarConsumed
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_s4Scalar_consumed
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_s4Scalar_consumed
#check @MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_s4Scalar_small_epsilon
#print axioms MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_s4Scalar_small_epsilon