import MathlibNt.SieveTheory.LiLiuGoldbachWeightTriplePartition

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check goldbachWeightLowMiddle
#check goldbachWeightUpperMiddle
#check goldbachWeightT14_eq_goldbachS6Closed
#check goldbachWeightLowMiddle_nonneg
#check goldbachWeightUpperMiddle_nonneg
#check goldbachWeightLowMiddle_add_goldbachWeightUpperMiddle_eq_goldbachS6Closed
#check goldbachWeightT14_add_goldbachWeightT15_eq_goldbachWeightLowMiddle_add_goldbachB6
#check goldbachWeightLowMiddle_monotone_right
#check goldbachWeightT14_add_goldbachWeightT15_add_goldbachWeightUpperMiddle_le_goldbachS6Closed_add_goldbachB6

#print axioms goldbachWeightT14_eq_goldbachS6Closed
#print axioms goldbachWeightLowMiddle_nonneg
#print axioms goldbachWeightUpperMiddle_nonneg
#print axioms goldbachWeightLowMiddle_add_goldbachWeightUpperMiddle_eq_goldbachS6Closed
#print axioms goldbachWeightT14_add_goldbachWeightT15_eq_goldbachWeightLowMiddle_add_goldbachB6
#print axioms goldbachWeightLowMiddle_monotone_right
#print axioms goldbachWeightT14_add_goldbachWeightT15_add_goldbachWeightUpperMiddle_le_goldbachS6Closed_add_goldbachB6