import MathlibNt.SieveTheory.LiLiuGoldbachS1AlphaNormalizedLower

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check goldbachS1_alphaFourFiftyThree_normalized_lower
#print axioms goldbachS1_alphaFourFiftyThree_normalized_lower