import MathlibNt.SieveTheory.LiLiuGoldbachB9CommonRemainder

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
open MathlibNt.SieveTheory.LiuWeight

#check instDecidableGoldbachB9PanDistribution
#check goldbachB9PlusDivCount
#check goldbachB9PlusGatedMainMass
#check goldbachB9PlusGatedRemainder
#check goldbachB9Product_mul_ne_self
#check goldbachB9Product_mul_lt_iff_le
#check goldbachB9PlusAtom_output_dvd_iff_residue
#check goldbachB9PlusProductResidueQFiber_card_eq_prefix
#check goldbachB9PlusDivCount_eq_product_sum
#check goldbachB9PlusPanAPPrefixCount
#check goldbachB9PlusDivCount_eq_panAPPrefixCount
#check goldbachB9PlusGatedRemainder_eq_panError
#check goldbachB9ProductSupport_pan_bounds
#check goldbachB9ProductSupport_mem_panInterval
#check goldbachB9ProductSupport_eventually_panInterval
#check goldbachB9PlusGatedRemainder_eventually_eq_panError
#check goldbachB9PlusGatedRemainder_abs_le_maxL
#check goldbachB9PlusGatedRemainder_log_saving
#check instDecidableGoldbachB9CommonRemainder
#check goldbachB9PlusCommonRemainder
#check goldbachB9PlusDeletedMain
#check goldbachB9PlusMainMass_eq_gated_add_deleted
#check goldbachB9PlusCommonRemainder_eq_gated_sub_deleted
#check goldbachB9PlusDeletedMain_one
#check goldbachB9PlusCommonRemainder_one
#check goldbachB9PlusDeletedMain_div_abs_eq_gateLoss
#check abs_goldbachB9PlusCommonRemainder_le
#check goldbachB9PlusCommonRemainder_log_saving
#check goldbachB9PlusBoundingSieve_rem_eq_commonRemainder
#check goldbachB9PlusBoundingSieve_remainder_log_saving
#check goldbachB9PlusBoundingSieve_levelSupport_subset
#check goldbachB9PlusBoundingSieve_levelRemainderSum_le
#check goldbachB9PlusBoundingSieve_levelRemainder_log_saving

#print axioms instDecidableGoldbachB9PanDistribution
#print axioms goldbachB9PlusDivCount
#print axioms goldbachB9PlusGatedMainMass
#print axioms goldbachB9PlusGatedRemainder
#print axioms goldbachB9Product_mul_ne_self
#print axioms goldbachB9Product_mul_lt_iff_le
#print axioms goldbachB9PlusAtom_output_dvd_iff_residue
#print axioms goldbachB9PlusProductResidueQFiber_card_eq_prefix
#print axioms goldbachB9PlusDivCount_eq_product_sum
#print axioms goldbachB9PlusPanAPPrefixCount
#print axioms goldbachB9PlusDivCount_eq_panAPPrefixCount
#print axioms goldbachB9PlusGatedRemainder_eq_panError
#print axioms goldbachB9ProductSupport_pan_bounds
#print axioms goldbachB9ProductSupport_mem_panInterval
#print axioms goldbachB9ProductSupport_eventually_panInterval
#print axioms goldbachB9PlusGatedRemainder_eventually_eq_panError
#print axioms goldbachB9PlusGatedRemainder_abs_le_maxL
#print axioms goldbachB9PlusGatedRemainder_log_saving
#print axioms instDecidableGoldbachB9CommonRemainder
#print axioms goldbachB9PlusCommonRemainder
#print axioms goldbachB9PlusDeletedMain
#print axioms goldbachB9PlusMainMass_eq_gated_add_deleted
#print axioms goldbachB9PlusCommonRemainder_eq_gated_sub_deleted
#print axioms goldbachB9PlusDeletedMain_one
#print axioms goldbachB9PlusCommonRemainder_one
#print axioms goldbachB9PlusDeletedMain_div_abs_eq_gateLoss
#print axioms abs_goldbachB9PlusCommonRemainder_le
#print axioms goldbachB9PlusCommonRemainder_log_saving
#print axioms goldbachB9PlusBoundingSieve_rem_eq_commonRemainder
#print axioms goldbachB9PlusBoundingSieve_remainder_log_saving
#print axioms goldbachB9PlusBoundingSieve_levelSupport_subset
#print axioms goldbachB9PlusBoundingSieve_levelRemainderSum_le
#print axioms goldbachB9PlusBoundingSieve_levelRemainder_log_saving

#check goldbachB9PlusLiWeight
#check goldbachB9PlusMainMass
#check goldbachB9PlusLiWeight_sum_gateLoss_log_saving_one
#check goldbachB9PlusAtoms_eq_B10ZeroPrefix
#check goldbachC9ProductSupport_bounds
#check goldbachB10DivisorAtoms_card_eq_sum_productSupport
#check abs_goldbachC10CoeffReal_le_one
#check liuMainPanCoprimeIntervalMaxL_boundedAggregate_log_saving
#check goldbachB10BoundingSieve_nu_eq_inv_totient
#check goldbachB10BoundingSieve_rem_eq_card_sub
#check goldbachB10_dvd_prodPrimes_coprime_N

#print axioms goldbachB9PlusLiWeight
#print axioms goldbachB9PlusMainMass
#print axioms goldbachB9PlusLiWeight_sum_gateLoss_log_saving_one
#print axioms goldbachB9PlusAtoms_eq_B10ZeroPrefix
#print axioms goldbachC9ProductSupport_bounds
#print axioms goldbachB10DivisorAtoms_card_eq_sum_productSupport
#print axioms abs_goldbachC10CoeffReal_le_one
#print axioms liuMainPanCoprimeIntervalMaxL_boundedAggregate_log_saving
#print axioms goldbachB10BoundingSieve_nu_eq_inv_totient
#print axioms goldbachB10BoundingSieve_rem_eq_card_sub
#print axioms goldbachB10_dvd_prodPrimes_coprime_N