import MathlibNt.SieveTheory.LiLiuGoldbachS2NormalizedUpper

namespace MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

set_option autoImplicit false

#check goldbachS2PrimeProduct
#check goldbachS2PrimeProduct_eq_sieveProductPrimeFactors
#check exists_goldbachS2SwitchedBoundingSieve_dimensionOneLocalProductBound
#check goldbachS2SwitchedSiftedCount_le_rosserFactor_add_upperErrSum
#check goldbachS2_upperErrSum_le_remainderModulusSum
#check goldbachS2SwitchedSiftedCount_le_rosserFactor_add_remainderModulusSum
#check goldbachS2SwitchedSiftedCount_upper_paid
#check goldbachS2MainMassUpperSum_eq_goldbachS2SwitchedMainMass
#check goldbachS2SwitchedBoundingSieve_sieveProductPrimeFactors_log_le_liuSingularSeries
#check goldbachS2SwitchedSiftedCount_normalized_upper_nine_nineteen_sub
#check goldbachS2_normalized_upper_nine_nineteen_sub

#print axioms goldbachS2PrimeProduct
#print axioms goldbachS2PrimeProduct_eq_sieveProductPrimeFactors
#print axioms exists_goldbachS2SwitchedBoundingSieve_dimensionOneLocalProductBound
#print axioms goldbachS2SwitchedSiftedCount_le_rosserFactor_add_upperErrSum
#print axioms goldbachS2_upperErrSum_le_remainderModulusSum
#print axioms goldbachS2SwitchedSiftedCount_le_rosserFactor_add_remainderModulusSum
#print axioms goldbachS2SwitchedSiftedCount_upper_paid
#print axioms goldbachS2MainMassUpperSum_eq_goldbachS2SwitchedMainMass
#print axioms goldbachS2SwitchedBoundingSieve_sieveProductPrimeFactors_log_le_liuSingularSeries
#print axioms goldbachS2SwitchedSiftedCount_normalized_upper_nine_nineteen_sub
#print axioms goldbachS2_normalized_upper_nine_nineteen_sub

end MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig