import MathlibNt.SieveTheory.LiLiuGoldbachB10PanGeometry

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check B10PanGeometryUpperWindow
#check B10PanGeometry_support_le_upperWindow
#check B10PanGeometry_upperWindow_le_rpow_two_thirds
#check B10PanGeometry_upperWindow_le_scaled_floor_rpow_eventually
#check B10PanGeometry_support_mem_commonWindow_eventually
#check B10PanGeometry_panModulusCutoff_comparison_eventually
#check B10PanGeometry_scaled_div_log_rpow_le_eventually
#check B10PanGeometry_consumer_threshold

#print axioms B10PanGeometryUpperWindow
#print axioms B10PanGeometry_support_le_upperWindow
#print axioms B10PanGeometry_upperWindow_le_rpow_two_thirds
#print axioms B10PanGeometry_upperWindow_le_scaled_floor_rpow_eventually
#print axioms B10PanGeometry_support_mem_commonWindow_eventually
#print axioms B10PanGeometry_panModulusCutoff_comparison_eventually
#print axioms B10PanGeometry_scaled_div_log_rpow_le_eventually
#print axioms B10PanGeometry_consumer_threshold