import MathlibNt.SieveTheory.LiLiuGoldbachWeightHighFirstConsumed
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachWeightLowFirstRemainder
#print axioms goldbachWeightLowFirstRemainder
#check goldbachWeightRemainingFive_eq_lowFirstRemainder_sub_high
#print axioms goldbachWeightRemainingFive_eq_lowFirstRemainder_sub_high
#check goldbachWeightHighFirstCoefficient
#print axioms goldbachWeightHighFirstCoefficient
#check goldbachB9HighMainIntegral_eq_singleIntegral
#print axioms goldbachB9HighMainIntegral_eq_singleIntegral
#check goldbachWeight_highFirst_consumed_eventually
#print axioms goldbachWeight_highFirst_consumed_eventually
#check goldbachWeight_highFirst_consumed_small_epsilon
#print axioms goldbachWeight_highFirst_consumed_small_epsilon