import MathlibNt.SieveTheory.LiLiuGoldbachS4CountTransport
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachS4_le_sifted_B8Plus_with_paid_finite_error
#print axioms goldbachS4_le_sifted_B8Plus_with_paid_finite_error