import MathlibNt.SieveTheory.LiLiuPrereqBuchstabUniformAbel

set_option autoImplicit false

#check LiLiuPrereqBuchstab.integral_eq_sub_of_hasDerivAt_off_one
#check LiLiuPrereqBuchstab.sum_mul_abel_of_ftc
#check LiLiuPrereqBuchstab.prime_abel_off_one
#check LiLiuPrereqBuchstab.hasDerivAt_buchstab_off_two
#check LiLiuPrereqBuchstab.abs_buchstabSlope_le_one
#check LiLiuPrereqBuchstab.hasDerivAt_buchstabPrimeKernel
#check LiLiuPrereqBuchstab.abs_buchstabPrimeKernelSlope_le
#check LiLiuPrereqBuchstab.integrableOn_buchstabPrimeKernelSlope
#check LiLiuPrereqBuchstab.buchstabPrimeKernel_abel
#check LiLiuPrereqBuchstab.prime_abel_log_error_identity
#check LiLiuPrereqBuchstab.prime_abel_log_error_le
#check LiLiuPrereqBuchstab.mem_primesIco
#check LiLiuPrereqBuchstab.sum_primesIcc_eq_sum_primesIco_add
#check LiLiuPrereqBuchstab.buchstabPrimeKernel_sum_Ioc_error_le
#check LiLiuPrereqBuchstab.buchstabPrimeKernel_sum_Ico_error_le
#check LiLiuPrereqBuchstab.buchstab_prime_sum_replacement_uniform

#print axioms LiLiuPrereqBuchstab.integral_eq_sub_of_hasDerivAt_off_one
#print axioms LiLiuPrereqBuchstab.sum_mul_abel_of_ftc
#print axioms LiLiuPrereqBuchstab.prime_abel_off_one
#print axioms LiLiuPrereqBuchstab.hasDerivAt_buchstab_off_two
#print axioms LiLiuPrereqBuchstab.abs_buchstabSlope_le_one
#print axioms LiLiuPrereqBuchstab.hasDerivAt_buchstabPrimeKernel
#print axioms LiLiuPrereqBuchstab.abs_buchstabPrimeKernelSlope_le
#print axioms LiLiuPrereqBuchstab.integrableOn_buchstabPrimeKernelSlope
#print axioms LiLiuPrereqBuchstab.buchstabPrimeKernel_abel
#print axioms LiLiuPrereqBuchstab.prime_abel_log_error_identity
#print axioms LiLiuPrereqBuchstab.prime_abel_log_error_le
#print axioms LiLiuPrereqBuchstab.mem_primesIco
#print axioms LiLiuPrereqBuchstab.sum_primesIcc_eq_sum_primesIco_add
#print axioms LiLiuPrereqBuchstab.buchstabPrimeKernel_sum_Ioc_error_le
#print axioms LiLiuPrereqBuchstab.buchstabPrimeKernel_sum_Ico_error_le
#print axioms LiLiuPrereqBuchstab.buchstab_prime_sum_replacement_uniform