import MathlibNt.SieveTheory.LiLiuGoldbachWeightLowPositivePrefixConsumed
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachWeight_lowPositivePrefix_consumed_eventually
#print axioms goldbachWeight_lowPositivePrefix_consumed_eventually
#check goldbachWeight_lowPositivePrefix_consumed_small_epsilon
#print axioms goldbachWeight_lowPositivePrefix_consumed_small_epsilon