import MathlibNt.SieveTheory.LiLiuGoldbachB9SplitIntegralReduction
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachB9InnerWeightedIntegral_eq
#print axioms goldbachB9InnerWeightedIntegral_eq
#check goldbachB9SubintervalIntegral_eq_single
#print axioms goldbachB9SubintervalIntegral_eq_single
#check goldbachB9WeightedSubintervalIntegral_eq_single
#print axioms goldbachB9WeightedSubintervalIntegral_eq_single
#check goldbachB9PaperSplitIntegral
#print axioms goldbachB9PaperSplitIntegral
#check goldbachB9PaperSplitIntegral_eq_singleIntegrals
#print axioms goldbachB9PaperSplitIntegral_eq_singleIntegrals
#check continuousOn_goldbachB9WeightedSingleIntegrand
#print axioms continuousOn_goldbachB9WeightedSingleIntegrand
#check intervalIntegrable_goldbachB9WeightedSingleIntegrand
#print axioms intervalIntegrable_goldbachB9WeightedSingleIntegrand
#check intervalIntegrable_goldbachB9WeightedInner
#print axioms intervalIntegrable_goldbachB9WeightedInner
#check intervalIntegrable_goldbachB9WeightedOuter
#print axioms intervalIntegrable_goldbachB9WeightedOuter
#check goldbachB9MainIntegral_eq_splitSingleIntegrals
#print axioms goldbachB9MainIntegral_eq_splitSingleIntegrals