import MathlibNt.SieveTheory.LiLiuGoldbachB8PanDistribution

open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig

#check instDecidableGoldbachB8FibreSieve
#check goldbachB8PlusSupport
#check goldbachB8PlusWeight
#check goldbachB8PlusDivCount
#check goldbachB8PlusMainMass
#check goldbachC8ProductSupport_one_lt_and_coprime
#check goldbachC8ProductSupport_two_le_quotient
#check goldbachB8PlusMainMass_nonneg
#check goldbachB8PlusWeight_sum_eq_card_atoms
#check goldbachB8PlusNu
#check goldbachB8PlusNu_isMultiplicative
#check goldbachB8PlusNu_eq_goldbachNu_of_squarefree
#check goldbachB8PlusBoundingSieve
#check goldbachB8PlusBoundingSieve_multSum_eq_divCount
#check goldbachB8PlusBoundingSieve_siftedSum_eq_card
#check goldbachB8PlusBoundingSieve_nu_eq_inv_totient
#check goldbachB8PlusBoundingSieve_rem_eq_divCount_sub
#check instDecidableGoldbachB8PanDistribution
#check goldbachC8CoeffReal
#check goldbachC8CoeffReal_eq_one_of_mem
#check goldbachC8CoeffReal_eq_zero_of_not_mem
#check abs_goldbachC8CoeffReal_le_one
#check goldbachB8PlusGatedMainMass
#check goldbachB8PlusRemainder
#check goldbachC8Product_mul_ne_self
#check goldbachC8Product_mul_lt_iff_le
#check goldbachC8Product_coprime_of_dvd_output
#check goldbachB8PlusAtom_output_dvd_iff_residue
#check goldbachB8PlusDivCount_eq_product_sum
#check goldbachC8CoeffReal_sum_eq_support
#check goldbachB8PlusPanAPPrefixCount
#check goldbachB8PlusDivCount_eq_panAPPrefixCount
#check goldbachB8PlusRemainder_eq_panError
#check goldbachC8ProductSupport_mem_panInterval
#check goldbachC8ProductSupport_eventually_panInterval
#check goldbachB8PlusRemainder_abs_le_maxL
#check goldbachB8PlusRemainder_log_saving
#check goldbachC8ProductSupport_coprime_of_dvd_prodPrimes
#check goldbachB8PlusGatedMainMass_eq_mainMass_of_dvd_prodPrimes
#check goldbachB8PlusBoundingSieve_rem_eq_remainder
#check goldbachB8PlusBoundingSieve_remainder_log_saving

#print axioms instDecidableGoldbachB8FibreSieve
#print axioms goldbachB8PlusSupport
#print axioms goldbachB8PlusWeight
#print axioms goldbachB8PlusDivCount
#print axioms goldbachB8PlusMainMass
#print axioms goldbachC8ProductSupport_one_lt_and_coprime
#print axioms goldbachC8ProductSupport_two_le_quotient
#print axioms goldbachB8PlusMainMass_nonneg
#print axioms goldbachB8PlusWeight_sum_eq_card_atoms
#print axioms goldbachB8PlusNu
#print axioms goldbachB8PlusNu_isMultiplicative
#print axioms goldbachB8PlusNu_eq_goldbachNu_of_squarefree
#print axioms goldbachB8PlusBoundingSieve
#print axioms goldbachB8PlusBoundingSieve_multSum_eq_divCount
#print axioms goldbachB8PlusBoundingSieve_siftedSum_eq_card
#print axioms goldbachB8PlusBoundingSieve_nu_eq_inv_totient
#print axioms goldbachB8PlusBoundingSieve_rem_eq_divCount_sub
#print axioms instDecidableGoldbachB8PanDistribution
#print axioms goldbachC8CoeffReal
#print axioms goldbachC8CoeffReal_eq_one_of_mem
#print axioms goldbachC8CoeffReal_eq_zero_of_not_mem
#print axioms abs_goldbachC8CoeffReal_le_one
#print axioms goldbachB8PlusGatedMainMass
#print axioms goldbachB8PlusRemainder
#print axioms goldbachC8Product_mul_ne_self
#print axioms goldbachC8Product_mul_lt_iff_le
#print axioms goldbachC8Product_coprime_of_dvd_output
#print axioms goldbachB8PlusAtom_output_dvd_iff_residue
#print axioms goldbachB8PlusDivCount_eq_product_sum
#print axioms goldbachC8CoeffReal_sum_eq_support
#print axioms goldbachB8PlusPanAPPrefixCount
#print axioms goldbachB8PlusDivCount_eq_panAPPrefixCount
#print axioms goldbachB8PlusRemainder_eq_panError
#print axioms goldbachC8ProductSupport_mem_panInterval
#print axioms goldbachC8ProductSupport_eventually_panInterval
#print axioms goldbachB8PlusRemainder_abs_le_maxL
#print axioms goldbachB8PlusRemainder_log_saving
#print axioms goldbachC8ProductSupport_coprime_of_dvd_prodPrimes
#print axioms goldbachB8PlusGatedMainMass_eq_mainMass_of_dvd_prodPrimes
#print axioms goldbachB8PlusBoundingSieve_rem_eq_remainder
#print axioms goldbachB8PlusBoundingSieve_remainder_log_saving