import MathlibNt.SieveTheory.LiLiuGoldbachG10CorrectedIntegralUpper
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachG10Corrected_I10_upper
#print axioms goldbachG10Corrected_I10_upper