import MathlibNt.SieveTheory.LiLiuGoldbachWeightRemainingFourCoarse
open MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig
#check goldbachWeightRemainingFour
#print axioms goldbachWeightRemainingFour
#check goldbachWeightRemainingFive_eq_remainingFour_sub_s5
#print axioms goldbachWeightRemainingFive_eq_remainingFour_sub_s5
#check goldbachWeightFourCoarseCoefficient
#print axioms goldbachWeightFourCoarseCoefficient
#check goldbachWeight_remainingFour_coarse_S1_S2_S3_S4_S5_I10_consumed_eventually
#print axioms goldbachWeight_remainingFour_coarse_S1_S2_S3_S4_S5_I10_consumed_eventually
#check goldbachWeight_remainingFour_coarse_small_epsilon
#print axioms goldbachWeight_remainingFour_coarse_small_epsilon