import Architect
import Goldbach.All

/-! Generated by scripts/generate_blueprint.py from blueprint/nodes.json.
The mathematical exposition is curated; theorem proofs are unchanged. -/

attribute [blueprint "bp:foundation-pnt"
  (title := "A quantitative prime number theorem")
  (statement := /-- $\exists c>0:\ \psi(x)-x=O(xe^{-c(\log x)^{1/10}})$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  AnalyticNumberTheory.PrimeDistribution.chebyshevPsi_medium_error

attribute [blueprint "bp:foundation-mertens"
  (title := "Mertens product with its identified constant")
  (statement := /-- $\exists C>0\ \forall n\ge2:\ |\prod_{p\le n}(1-1/p)-e^{-\gamma}/\log n|\le C/(\log n)^2$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  AnalyticNumberTheory.Mertens.primeProduct_mertens_nat

attribute [blueprint "bp:foundation-local-product"
  (title := "Uniform dimension-one Goldbach local product")
  (statement := /-- $\exists K>1:\ \prod_{p\in\mathcal P}(1-1/(p-1))^{-1}\le(\log z_2/\log z_1)(1+K/\log z_1)$ for every finite set of odd primes $\mathcal P\subset[z_1,z_2)$, $2\le z_1\le z_2$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.MertensTheorem.exists_goldbach_inverse_interval_bound

attribute [blueprint "bp:foundation-bv"
  (title := "Bombieri–Vinogradov for primes")
  (statement := /-- For every $A>0$ there are $B\ge0$, $C>0$ and $N_0$ such that $\sum_{1\le q\le Q_B(N)}E^*(N,q)\le CN/(\log N)^A$ for integers $N\ge N_0$, where $Q_B(N)=\lfloor N^{1/2}/(\log N)^B\rfloor$ and $E^*(N,q)=\max_{y\in\{0,\ldots,N\}}\max_{0\le a<q,\,(a,q)=1}|\pi(y;q,a)-L_*(y)/\varphi(q)|$. Here $L_*(x)=2/\log2+\int_2^xdt/\log t$ for $x>1$, while $L_*(0)=L_*(1)=2/\log2$ by the totalized interval-integral convention, not a principal value; $E^*(N,0)=0$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  AnalyticNumberTheory.LargeSieve.Bombieri1965Richert418.standardBombieriVinogradov

attribute [blueprint "bp:foundation-weighted-bv"
  (title := "The actual weighted conditioned Chen error")
  (statement := /-- For fixed $0<\epsilon<1/6$ and $A>0$, let $P_N=\prod_{2<p\le N^{1/10},\,p\nmid N}p$. Eventually, $\sum_{N^{1/10}<q\le N^{1/3},\ q\ \text{ prime},\ q\nmid N}\sum_{d\mid P_N,\ d<\lfloor N^{1/2-\epsilon}/q\rfloor+1}3^{\omega(d)}E_{\rm prime}(N,qd)\ll_{\epsilon,A}N/(\log N)^A$. The fixed-endpoint error is $E_{\rm prime}(N,h)=\max_{0\le a<h,\,(a,h)=1}|\pi(N;h,a)-L_*(N)/\varphi(h)|\le E^*(N,h)$; all products run over primes. The constants and threshold depend only on the fixed parameters. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.Bombieri1965RichertWeightedConsumer.chenWeightedBombieriVinogradov

attribute [blueprint "bp:foundation-jr-hats"
  (title := "Constructed Jurkat--Richert comparison functions")
  (statement := /-- For the constructed Jurkat--Richert functions $F,f$, let $c_\gamma=2e^\gamma$. On $s>0$, define $\widehat T^+(s)=s^{-2}$ for $s\le3$ and $[F(s)-f(s-1)]/(c_\gamma s)$ for $s>3$; define $\widehat T^-(s)=2s^{-2}$ for $s\le2$ and $[F(s-1)-f(s)]/(c_\gamma s)$ for $s>2$. These positive extensions of the normalized derivatives $-F'/c_\gamma$ and $f'/c_\gamma$ satisfy the complete Suzuki source properties with $\widehat\beta=2$: positivity, continuity, the initial formulas, weighted delay derivatives, and weighted and exponential decay. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.JurkatRichert1965ChenGammaOneQOne.jr1965Section13HatSourceContract

attribute [blueprint "bp:foundation-suzuki-lower"
  (title := "Lower Rosser comparison uniform in the sieve")
  (statement := /-- Fix hats satisfying the Suzuki source properties and real $d,\Delta,\Theta$ with $0<\Delta<1$, $d>7/(1-\Delta)$, $\Theta>0$, $2/d<1/\Theta$ and $2/\Theta+3/d<1-\Delta$. The source selects its auxiliary constants, and in particular $C\ge3$, before the bounding sieve $S$ varies. For each $K\ge2$ satisfying its dimension-one local-product bound, each integer $D\ge2$ and $4\le s\le6$, put $z=\lceil D^{1/s}\rceil\ge2$ and assume $s\le\sigma_{\rm src}(D;d)=(\log D)^{1/d}\log\log(27D)$. With $\mathcal P_S(z)$ the supported primes below $z$, $P=\prod_{p\in\mathcal P_S(z)}p$, $m=2(|\mathcal P_S(z)|+1)$ and $V_S(z)=\prod_{p\in\mathcal P_S(z)}(1-g_S(p))$, one has $V_S(z)[f(s)-C e^{\sqrt K}E_m(D,s;d)(\log D)^{-\Delta}]\le\sum_{e\mid P}\lambda_e^-g_S(e)$. The weights are the finite lower Rosser weights of natural level $D$, and $E_m(D,s;d)=(1+s^d/\log D)^s s\widehat T^{\eta_m}(s)$, with $\eta_m=+$ for odd $m$ and $-$ for even $m$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.exists_lowerRosserDensity_dimensionOneLowerFactor_of_suzuki_literal_allDepth_uniform_in_S_of_source

attribute [blueprint "bp:foundation-suzuki-upper"
  (title := "Modern upper Rosser comparison")
  (statement := /-- Given hats satisfying the Suzuki source properties and fixed $d,\Delta,\Theta$ with $0<\Delta<1$, $d>7/(1-\Delta)$, $\Theta>0$, $2/d<1/\Theta$ and $2/\Theta+3/d<1-\Delta$, for every $K>1$ and $\rho>0$ there is $z_0$ before the bounding sieve $S$ varies. If $z\ge\max(2,z_0)$, $D_{\rm real}>0$, $S$ satisfies the dimension-one local-product bound with $K$, every sifting prime is at most $z$, and $s=\log D_{\rm real}/\log z\in[3/2,4]$, then $\sum_{e\mid P}\lambda_e^+g_S(e)\le(F(s)+\rho)\prod_{p\mid P}(1-g_S(p))$. Here $P$ is the product of the sifting primes, the product on the right is over primes, and $\lambda^+$ is the finite upper Rosser weight at natural level $\lfloor D_{\rm real}\rfloor+1$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.dimensionOneUpperRosserDensityFundamentalLemma_of_suzuki_allDepth

attribute [blueprint "bp:foundation-liupan"
  (title := "Liu--Pan distribution for the actual convolution")
  (statement := /-- $\exists\kappa\ \forall U>0\ \exists C>0,B\ge0,N_0:\ \sum_{q<N^{1/2}/(\log N)^B}M_{a_N,I_N,\kappa}(N;q)\le CN/(\log N)^U$ for $N\ge N_0$; the proof chooses $\kappa=2/\log2$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.liuPanUnweightedTheorem2Specialization_proved

attribute [blueprint "bp:foundation-liupan-canonical"
  (title := "Liu–Pan convolution distribution")
  (statement := /-- $\forall\epsilon,A>0\ \exists C>0,B\ge0,N_0:$ the canonical $L_2$ coprime weighted remainder majorant is $\le CN/(\log N)^A$ for $N\ge N_0$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.liuPanCanonicalCoprimeTheorem_proved

attribute [blueprint "bp:foundation-pan-bounded"
  (title := "Pan distribution for varying weights")
  (statement := /-- $\forall U>0\ \exists C>0,B\ge0,N_0\ \forall N\ge N_0,I,a:\ \sum_{1\le q\le Q_B(N)}M_{a,I,*}(N;q)\le CN/(\log N)^U$, provided $|a|\le1$, $A_2\le N^{2/3}$, $(\log N)^{2B}\le A_1$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.liuMainPanCoprimeIntervalMaxL_boundedAggregate_log_saving

attribute [blueprint "bp:foundation-selberg-denominator"
  (title := "Asymptotic of the optimized Selberg denominator")
  (statement := /-- $\epsilon<1/2\implies G(N,\epsilon)\mathfrak S_{\mathrm{Liu}}(N)/\log N\to(1/4-\epsilon/2)/2$ along the even integers. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.tendsto_liuSelbergDenominator_normalized_even

attribute [blueprint "bp:foundation-selberg-remainder"
  (title := "Paying the signed Selberg remainder")
  (statement := /-- $|\mathcal R_{\lambda}(N,\epsilon)|\le\mathcal M_{\mathrm{full}}(N,\epsilon)$ for $N\ge1$ and admissible supported $\lambda$; the majorant has lcm weight $3^{\omega(d)}$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.abs_liuSelbergRemainder_le_fullDistributionMajorant

attribute [blueprint "bp:foundation-fouvry-rectangle"
  (title := "Well-factorable rectangular Goldbach distribution")
  (statement := /-- Fix $i,j,A\in\mathbb N$, $C_{\rm scale}\ge1$ and $\zeta>0$. There is a threshold $x_0$ depending only on these parameters such that for every real $x\ge x_0$ the bound $|\mathcal E_{\rm rect}|\le x/(\log x)^A$ holds uniformly in the following data: $M,T\ge1$, $4MT=x$, $T=x^\nu$, $\zeta\le\nu\le1/10+\zeta/10$; an integer residue $0<N\le C_{\rm scale}x$; a finite set $\mathcal U\subset[M,2M]\cap\mathbb N$ and interval $J=(u,v]\cap\mathbb N$ with $T\le u\le v\le2T$; coefficients $|\alpha(m)|\le\tau_i(m)$ on $\mathcal U$, the short coefficient $\beta_N(n)=\mathbf1_{n\ \text{ prime},\,(n,N)=1}$, and a signed well-factorable coefficient $c$ of order $j$ at $Q=x^{(5-5\nu)/9-\zeta}$. Here $\tau_i$ is the ordered $i$-fold divisor function, and $\mathcal E_{\rm rect}$ is the signed sum over $1\le q\le\lfloor Q\rfloor$, $(q,N)=1$, of $c(q)$ times the $\alpha\beta_N$ bilinear progression mass at $mn\equiv N\pmod q$ minus its coprime mass divided by $\varphi(q)$. The threshold precedes all rectangle, residue and coefficient choices. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.AnalyticNumberTheory.LargeSieve.LiLiuPrereqFouvry.primeC2_goldbach_rectangle_kscale

attribute [blueprint "bp:chen-positive-weight"
  (title := "Positive weight detects at most two factors")
  (statement := /-- If $2\le z<y$, $1\le n<y^3$, no prime below $z$ divides $n$, and $w(n)>0$, then $n=1$, $n$ is prime, or $n=rs$ for primes $r,s\ge z$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.chenWeight_pos_implies_semiprime

attribute [blueprint "bp:chen-finite-counting"
  (title := "Chen finite counting inequality")
  (statement := /-- If $z<y$ and every corrected candidate complement is below $y^3$, then $|\mathcal C(N)|-(P(N)+T(N))/2\le|\mathcal C(N)\cap G(N)|$. The proof sums the pointwise weight bound. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.corrected_counting_bridge

attribute [blueprint "bp:chen-lower-sieve"
  (title := "Lower Rosser density gives the actual base sieve")
  (statement := /-- The source lower-density lemma implies that for every $\delta>0$ some fixed $0<\epsilon<1/2$ gives $(f(5)-\delta)XV_N-\mathcal R_0(N,\epsilon)\le|\mathcal S(N)|$ eventually for even $N$. The actual finite remainder is retained. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.chenJurkatRichertBaseLowerSieveFundamentalLemma_of_density

attribute [blueprint "bp:chen-base-asymptotic"
  (title := "Distribution closes the base lower bound")
  (statement := /-- The base lower sieve and its Goldbach distribution estimate imply, for every $\eta>0$, $(8(\log4+J)-\eta)\mathcal X_N\le|\mathcal S(N)|$ eventually for even $N$. Mertens normalization is supplied internally. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.chenJurkatRichertBaseLowerSieveAsymptotic_of_inputs

attribute [blueprint "bp:chen-finite-upper"
  (title := "Sum the conditioned finite upper sieves")
  (statement := /-- For $N>1$ and $\epsilon<1/60$, $H(N)\le\mathcal M_q(N,\epsilon)+\mathcal R_q(N,\epsilon)$, using exact conditioned sources and levels $d<\lfloor N^{1/2-\epsilon}/q\rfloor+1$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.jurkatRichertSourceMediumPrimeAggregate_le_main_add_remainder

attribute [blueprint "bp:chen-weighted-bv"
  (title := "Pay combined-modulus weighted prime errors")
  (statement := /-- Ordinary BV implies that for each fixed $0<\epsilon<1/6$ and $A>0$ some $C>0$ gives $\sum_{q\in\mathcal Q(N),\ q\nmid N}\sum_{d\mid\mathcal P_N,\ d\le N^{1/2-\epsilon}/q}3^{\omega(d)}E_{\rm prime}(N,qd)\le CN/(\log N)^A$ eventually. Here $E_{\rm prime}(N,m)=\max_l|\pi(N;m,l)-L_*(N)/\varphi(m)|$ over canonical reduced residues, $L_*=\operatorname{li}_{2/\log2}$, and $E_{\rm prime}(N,m)\le E^*(N,m)$. Modulus zero has error zero and modulus one uses residue zero. The proof requests ordinary prefix-maximal saving $2A+10$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.Richert1969.chenWeightedBombieriVinogradov_of_standard

attribute [blueprint "bp:chen-upper-asymptotic"
  (title := "Close the varying-prime upper asymptotic")
  (statement := /-- The uniform upper density theorem and weighted BV imply, for every $\eta>0$, $H(N)\le(8(\log8+K/2)+\eta)\mathcal X_N$ eventually for even $N$. Prime partial summation is internal. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.chenJurkatRichertVaryingQUpperSieveAsymptotic_of_standardInput

attribute [blueprint "bp:chen-distinct-lower"
  (title := "Subtract half the medium-prime upper bound")
  (statement := /-- The base lower asymptotic and the two standard upper inputs imply $W_{\rm src}(N)\ge(2.6408-\eta)\mathcal X_N$ eventually for even $N$, for every $\eta>0$. The proof uses the exact source weight identity and the integral estimate. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.chenJurkatRichertDistinctWeightedLowerBound_of_asymptotics

attribute [blueprint "bp:chen-prime-powers"
  (title := "Bound the proper-prime-power correction")
  (statement := /-- For even $N>2^{110}$, $P(N)\le\sum_{p\in\mathcal C(N)}\#\{r\in[z,y):r\text{ prime},\ r\mid N-p\}+60N^{9/10}$. Square-divisibility counts and a valuation bound pay the correction. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenPrimePowerSum_le_q1Count_add_negligible

attribute [blueprint "bp:chen-valuation-lower"
  (title := "Chen weighted lower bound")
  (statement := /-- The distinct source weighted lower bound implies $W(N)\ge(2.6408-\eta)\mathcal X_N$ eventually for even $N$, for every $\eta>0$. Source-boundary and valuation losses are absorbed using $\mathfrak S_{\mathrm{Liu}}(N)\ge U>0$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.SwitchingPrinciple.chenJurkatRichertWeightedLowerBound_of_distinct

attribute [blueprint "bp:chen-triple-endpoints"
  (title := "Inject first-factor witnesses into source triples and endpoints")
  (statement := /-- For $N\ge1$ and $\lfloor N^{1/10}\rfloor\ge2$, $T(N)\le T_{\rm src}(N)+13N^{9/10}$. An injective selected-factor map isolates the two integer cutoff fibres. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.correctedChenTripleFactorSum_le_source_add_thirteen_mul_rpow_nine_tenths

attribute [blueprint "bp:chen-square-majorant"
  (title := "A candidate prime contributes a unit Selberg packet")
  (statement := /-- For even $N$ and $R\ge1$, the corrected triple slice at a fixed pair is bounded by its optimal Selberg square sum plus the residual counting candidate primes $N-rsu\mid Q$. Away from this residual only divisor $1$ contributes. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.liuSelbergCorrectedTripleSlice_le_square_add_QResidual

attribute [blueprint "bp:chen-square-expansion"
  (title := "Expand the square into progression counts")
  (statement := /-- For all $N,\epsilon,\lambda$, $\mathcal B_\lambda=\sum_{d_1,d_2\in\mathcal D}\lambda_{d_1}\lambda_{d_2}\sum_a b(a)\pi(N;a,[d_1,d_2],N\bmod[d_1,d_2])$. The proof is finite sum interchange and least-common-multiple divisibility. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.liuSelbergSquareCount_eq_switchedCount

attribute [blueprint "bp:chen-square-main-term"
  (title := "Bound the optimized Selberg main term")
  (statement := /-- For every fixed $\kappa\ge0$ and $0<\epsilon\le10^{-10}$, eventually along even $N$, the optimal main term $H_{\kappa}(N)/\mathcal G$ is at most $3.94033\mathcal X_N$, where $H_{\kappa}(N)=\sum_a b(a)\operatorname{li}_{\kappa}(N/a)$. The actual source integral is $I_{\rm Liu}=\int_{1/10}^{1/3}\int_{1/3}^{(1-\alpha)/2}[\alpha\beta(1-\alpha-\beta)]^{-1}\,d\beta\,d\alpha<0.49254$. The producer transfers the exact reciprocal-log pair sum to this integral, then pays the genuine-li-minus-proxy correction to obtain $0\le H_{\kappa}(N)\le(0.49254+\eta)N/\log N$ for each fixed $\eta>0$ eventually. This is multiplied by the denominator estimate; the proof fixes $\delta=\eta=10^{-7}$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.eventually_liuSelbergOptimalLambda_mainTermUpperBound_even

attribute [blueprint "bp:chen-switched-weight-payment"
  (title := "Pay the switched modulus weight by finite Cauchy")
  (statement := /-- One $C_9>0$, fixed before $\kappa,N,B$, bounds $(\sum_{q<L}\mu(q)^2 3^{\omega(q)}E_q(\kappa))^2$ by $C_9(\log(N+2))^9 C_\kappa N(1+\log N)^2\sum_{q<L}E_q(\kappa)$ for $N\ge2$, $\log N\ge1$, and $B\ge0$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.exists_liuPanWeightedSum_sq_le_unweighted

attribute [blueprint "bp:chen-square-remainder"
  (title := "Pay the actual signed Selberg remainder")
  (statement := /-- Under the canonical coprime theorem, for every $\epsilon,A>0$, filter $\mathcal F\le\mathrm{atTop}$ and eventually admissible family $\lambda_N$, there is $C>0$ with $|\mathcal E_{\lambda_N}(N)|\le CN/(\log N)^A$ eventually in $\mathcal F$. The full majorant includes the noncoprime part. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.LiuPanCanonicalCoprimeTheorem.eventually_abs_liuSelbergRemainder_le

attribute [blueprint "bp:chen-triple-upper"
  (title := "Chen triple-penalty upper bound")
  (statement := /-- Under the canonical coprime theorem, for every $0<\epsilon\le10^{-10}$ and $A>0$ there is $C>0$ such that eventually for even $N$, $T(N)\le3.94033\mathcal X_N+CN/(\log N)^A$. Both cutoff and paper-modulus residuals are included. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiuWeight.LiuPanCanonicalCoprimeTheorem.eventually_correctedChenOmegaTriple_le

attribute [blueprint "bp:chen-representation-lower-bound"
  (title := "Chen: 0.67 representation bound")
  (statement := /-- For every sufficiently large even $N$, $0.67\,\mathfrak S_{\mathrm{Liu}}(N)N/(\log N)^2\le|G(N)|$, where $G(N)$ is the original set of primes $p<N$ with $N-p\ge2$ and at most two prime factors counted with multiplicity. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  Goldbach.representation_lower_bound

attribute [blueprint "bp:chen-theorem"
  (title := "Chen prime plus at most two primes")
  (statement := /-- There exists $N_0\in\mathbb N$ such that every even $N\ge N_0$ admits $N=p+q$, with $p$ prime and either $q$ prime or $q=rs$ for primes $r,s$, which may coincide. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  Goldbach.chen_theorem

attribute [blueprint "bp:liliu-representation"
  (title := "The literal asymmetric representation")
  (statement := /-- For $N,p\in\mathbb N$, the representation predicate is $p$ prime and $\exists r,q\in\mathbb N$: $(r=1\text{ or }r\text{ prime})$, $q$ prime, $N=p+rq$, and $r^{10}\le q^9$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.IsOnePlusOneNineRepresentation

attribute [blueprint "bp:liliu-count-positive"
  (title := "Positive distinct-prime count")
  (statement := /-- For every $N\in\mathbb N$, $D_{1,19/10}(N)>0$ if and only if there exist $p,r,q\in\mathbb N$ with $p\le N$, $p,q$ prime, $r=1$ or $r$ prime, $N=p+rq$, and $r^{10}\le q^9$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.D19_pos_iff

attribute [blueprint "bp:liliu-imbalance"
  (title := "The arithmetic imbalance mechanism")
  (statement := /-- For $N,n,r,q\in\mathbb N$ and $\varepsilon>0$, assume $r>0$, $n=rq>\varepsilon N$, $r<\lceil N^{9/19-\varepsilon}\rceil$, and $(N^{9/19-\varepsilon})^{19}\le(\varepsilon N)^9$. Then $r^{10}\le q^9$. The cutoff is equivalent to $r<N^{9/19-\varepsilon}$ because $r$ is integral. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.oneNine_power_bound

attribute [blueprint "bp:liliu-basic"
  (title := "Li–Liu finite weight detector")
  (statement := /-- For every fixed $\varepsilon>0$, there is $N_0\in\mathbb N$ such that, for all $N\ge N_0$ and every real $a$, $\sum_{n\in\mathcal A}w_a(n)\le D_{1,19/10}(N)$. The threshold precedes $a$; no evenness hypothesis is needed. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.goldbachBasic_finite_le_D19

attribute [blueprint "bp:liliu-six"
  (title := "Six-term sieve inequality with paid losses")
  (statement := /-- Fix $0<\varepsilon<2/15$. There is $N_0\in\mathbb N$ such that every even $N\ge N_0$ and every $1/21<k<\sigma\le1/3$, with $z=N^k,y=N^\sigma,T=N^{9/19-\varepsilon}$, satisfy $2S_1(z)-2S_2(T)-S_3(z,y)-2S_4(y)-S_5(z,y)+S_6(z,y)-446N^{1-k}\le2D_{1,19/10}(N)$. This threshold is uniform in $k,\sigma$; there is no additional positive-loss parameter. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachbig_finite_lower_bound_eventually

attribute [blueprint "bp:liliu-twelve"
  (title := "Li–Liu twelve-term decomposition")
  (statement := /-- Fix $0<\varepsilon<2/15$. One threshold works for every $1/18<a<b<(1-3b)/3<c<1/3$. With the corresponding cutoffs, every even $N$ beyond it satisfies $3G_1+G_2-4G_3-G_4-G_5+G_6+G_7-2G_8-G_9-G_{10}^{\mathrm{corr}}-G_{11}-G_{12}-1334N^{1-a}\le4D_{1,19/10}(N)$. In the analytic application $(a,b,c)=(4/53,4/33,3/11)$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_twelve_corrected_lower_bound_eventually

attribute [blueprint "bp:liliu-sifted"
  (title := "Label-preserving output sifting")
  (statement := /-- For $N\ge2$, $\varepsilon>0$, $\beta>1/18$, any real second cutoff $C$, and $Z\ge1$, the finite labelled counts with first cutoff $B=N^\beta$ satisfy $\Pi_{10}\le\mathcal B_{10}(Z)+400\lfloor Z\rfloor$. Here the output $N-rsq$ is sifted excluding prime divisors of $N$, while the pair labels and strict prime-cofactor window are retained. Neither eventuality nor evenness is required. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachPi10_le_goldbachB10SiftedCount_add_fourHundred_floor

attribute [blueprint "bp:liliu-positive"
  (title := "The two positive lower-sieve terms")
  (statement := /-- For every $\delta>0$ and every fixed $0<\varepsilon<1$, there exists $N_0\ge4$ such that all even $N\ge N_0$ satisfy $((1-\varepsilon)L-\delta)\mathcal X_N\le3G_1+G_2$, at $(a,b)=(4/53,4/33)$. The threshold may depend on both $\delta$ and $\varepsilon$; epsilon need not shrink with delta. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachS1_positivePair_normalized_lower

attribute [blueprint "bp:liliu-retained"
  (title := "Li–Liu five-term reduction")
  (statement := /-- For every $\delta>0$, there exists $\varepsilon_0\in(0,2/15]$ such that, for every fixed $0<\varepsilon<\varepsilon_0$, there is $N_0(\delta,\varepsilon)\ge4$ for which all even $N\ge N_0$ satisfy $G_6+G_7-G_9-G_{11}-G_{12}+(124341093/200000000-\delta)\mathcal X_N\le4D_{1,19/10}(N)$, at the fixed exponents of this chapter. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_remainingFive_allRetained_small_epsilon

attribute [blueprint "bp:liliu-b9"
  (title := "The original ninth count and its split integral")
  (statement := /-- For every $\delta>0$ and every fixed $0<\varepsilon<2/15$, there is $N_0\ge4$ such that all even $N\ge N_0$ satisfy $G_9\le(C_9+\delta)\mathcal X_N$, with $G_9=S_5(N^{4/53},N^{1/3})$. The threshold follows $\delta,\varepsilon$. The low part of $C_9$ retains the additional factor $1/(1-u)$, so its reduced kernel has denominator $u(1-u)^2$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachS5Closed_normalized_upper_paperSplit

attribute [blueprint "bp:liliu-pair"
  (title := "Original positive pair counts")
  (statement := /-- For every $\delta>0$, there exists $\varepsilon_0\in(0,2/15]$ such that, for every fixed $0<\varepsilon<\varepsilon_0$, there is $N_0(\delta,\varepsilon)\ge4$ for which all even $N\ge N_0$ satisfy $(C_{67}-\delta)\mathcal X_N\le G_6+G_7$, at $(a,b,c)=(4/53,4/33,3/11)$. The small epsilon window absorbs the source-mass loss before the natural threshold is chosen. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11Author_reused_pair_lower

attribute [blueprint "bp:liliu-pair-certificate"
  (title := "Certified lower bound for the pair integral")
  (statement := /-- $54233/10000\le C_{67}$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG67IntegralConstant_lower_certified

attribute [blueprint "bp:liliu-level"
  (title := "The author weight from the actual mixed level")
  (statement := /-- For $N\ge4$, $N^{4/53}\ge4$, $1<\rho\le5/4$, and $0\le\eta<1/4$, every used grid cell and every short prime $p$ in it satisfy $4\log N/\log Q_{\mathrm{mix}}\le h(\log p/\log N)+32\eta$. The finite comparison has arbitrary real $\varepsilon$, constrained only through membership in the used-cell set; $\eta$ is the level loss, not a small-epsilon-window parameter. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11MixedLevel_author_weight

attribute [blueprint "bp:liliu-domain"
  (title := "Matching the author original ordered domain")
  (statement := /-- $I_{11}(h)=\frac{36}{5}\int_a^{1/10}\frac{K_{11}(u)}{1-u}\,du+8\int_{1/10}^bK_{11}(u)\,du$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11PrimeIntegral_author_split

attribute [blueprint "bp:liliu-g11-certificate"
  (title := "Certified author integral")
  (statement := /-- $(561522/10^6)I_{11}(h)\le10191/100000$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11PrimeIntegral_author_scalar_le_10191

attribute [blueprint "bp:liliu-g11-actual"
  (title := "Eleventh-term count upper bound")
  (statement := /-- For every $\delta>0$ and every fixed $0<\varepsilon\le1$, there exists $N_0(\delta,\varepsilon)\ge4$ such that all even $N\ge N_0$ satisfy $G_{11}\le(10191/100000+\delta)\mathcal X_N$ on the original domain $z\le r\le q\le s\le t\le B$. No factor $1-\varepsilon$ is asserted: this bound uses the full upper-endpoint rough mother. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeightG11_le_authorScalar_direct

attribute [blueprint "bp:liliu-cross"
  (title := "The original cross count after both exception payments")
  (statement := /-- For every $\delta>0$ and every fixed $0<\varepsilon\le2/15$, there exists $N_0(\delta,\varepsilon)\ge4$ such that all even $N\ge N_0$ satisfy $G_{12}\le(C_{12}+\delta)\mathcal X_N$. Both exception payments are included. The original domain is $z\le r\le q\le s\le B\le t\le C$, and $C_{12}$ uses the strict-low, closed-high Buchstab-weight split defined in the text. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachG11Author_reused_cross_upper

attribute [blueprint "bp:liliu-cross-certificate"
  (title := "Certified cross integral")
  (statement := /-- $C_{12}\le66821/100000$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  G12AnalyticCertificate.actual_le_target

attribute [blueprint "bp:liliu-author-consume"
  (title := "Author estimate consumed at the original counts")
  (statement := /-- For every $\delta>0$, there exists $\varepsilon_0\in(0,2/15]$ such that, for every fixed $0<\varepsilon<\varepsilon_0$, there is $N_0(\delta,\varepsilon)\ge4$ for which all even $N\ge N_0$ satisfy $G_6+G_7-G_{12}+(c_0-C_9-10191/100000-\delta)\mathcal X_N\le4D_{1,19/10}(N)$, at the fixed exponents of this chapter. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_paperSplit_authorG11_consumed_small_epsilon

attribute [blueprint "bp:liliu-ledger"
  (title := "Li–Liu positive total weight")
  (statement := /-- For every $\delta>0$, there is $\varepsilon_0\in(0,2/15]$ such that, for every fixed $0<\varepsilon<\varepsilon_0$, there exists $N_0(\delta,\varepsilon)\ge4$ for which all even $N\ge N_0$ satisfy $(515093/200000000-\delta)\mathcal X_N\le4D_{1,19/10}(N)$. The threshold is not asserted uniformly over all small positive epsilon. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachWeight_authorG11_numericLedger

attribute [blueprint "bp:liliu-coefficient"
  (title := "Every fixed coefficient below the retained ceiling")
  (statement := /-- $\forall\kappa<515093/800000000\ \exists K\ge4\ \forall N\ge K,\ 2\mid N\Rightarrow\kappa \mathcal X_N\le D_{1,19/10}(N)$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach_D19_author_lower_of_coefficient_lt

attribute [blueprint "bp:liliu-paper"
  (title := "Li–Liu: strict 0.0004 lower bound")
  (statement := /-- $\exists K\ge4\ \forall N\ge K,\ 2\mid N\Rightarrow 0.0004\mathcal X_N<D_{1,19/10}(N)$. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach_D19_gt_paper_0004

attribute [blueprint "bp:liliu-old-margin"
  (title := "The separate earlier positive margin")
  (statement := /-- For $m_{\mathrm{old}}:=4J_{\mathrm{elem}}+c_0-C_9-10385101/10^8-C_{12}$, where $J_{\mathrm{elem}}$ is the five fixed sum-coordinate integrals in the text (including the half-square multiplicity), $126891/200000000\le m_{\mathrm{old}}$. This is an unconditional scalar certificate with no epsilon parameter, not the definition of the margin and not the author-route ledger. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbachSharpElementaryMargin_lower_certified

attribute [blueprint "bp:liliu-existence"
  (title := "The actual unconditional existence endpoint")
  (statement := /-- There exists $K\ge4$ such that every even $N\ge K$ admits $p,r,q\in\mathbb N$ with $p\le N$, $p,q$ prime, $r=1$ or $r$ prime, $N=p+rq$, and $r\le q^{(19/10)-1}$. This endpoint is supplied by the independent old-margin existence route. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  MathlibNt.SieveTheory.LiLiuOnePlusOneNine.GoldbachBig.goldbach_onePlusOneNine_unconditional

attribute [blueprint "bp:foundation-bv-low"
  (title := "Small-conductor Siegel–Walfisz input")
  (statement := /-- The constructed smoothing function and the proved uniform Landau--Siegel lower bound supply the nonprincipal primitive Siegel--Walfisz estimate required by the ordinary BV producer. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  AnalyticNumberTheory.LargeSieve.Bombieri1965Richert418.nonprincipalPrimitivePsiSiegelWalfiszSource

attribute [blueprint "bp:foundation-bv-high"
  (title := "Large-conductor Vaughan estimates")
  (statement := /-- For each requested logarithmic saving, one common pair of Vaughan cutoffs pays the Type I, Type II and small-term means on the chosen high-conductor family, including the prefix and cofactor amplification factors. -/)
  (proofUses := [-"ZetaUpperBnd", -"ResidueTheoremOnRectangleWithSimplePole", -"MediumPNT", -"Smooth1Properties_below", -"Smooth1Properties_above", -"Smooth1", -"RectangleIntegral", -"pi_alt", -"Smooth1Nonneg", -"HolomorphicOn.vanishesOnRectangle", -"Smooth1ContinuousAt", -"existsDifferentiableOn_of_bddAbove", -"SmoothedChebyshevDirichlet_aux_integrable", -"MellinOfSmooth1b", -"Smooth1LeOne", -"VerticalIntegral"])]
  AnalyticNumberTheory.LargeSieve.standardBVHighChosenUnconditional
