import MathlibNt.SieveTheory.LinearSieve.Suzuki.SuzukiLemma144CaseISuccessorUniformStrict
import MathlibNt.SieveTheory.LinearSieve.Suzuki.SuzukiLemma144CaseIErrorTransportUniform
import MathlibNt.SieveTheory.LinearSieve.Suzuki.SuzukiLemma144CaseIGeometryPacket
import MathlibNt.SieveTheory.LinearSieve.Suzuki.SuzukiClaim1413Internal
import MathlibNt.SieveTheory.LinearSieve.Suzuki.SuzukiLemma144RecursiveCoordinateSourceSigma

open scoped Classical BigOperators Interval
open Filter Finset MeasureTheory Set Topology

namespace MathlibNt.SieveTheory

open LinearSieve SwitchingPrinciple SuzukiFiniteContinuousLayers
open SwitchingPrinciple.SuzukiLemma144Equation1410
open SwitchingPrinciple.SuzukiLemma144KappaOne


set_option maxHeartbeats 2000000

/-!
# Lemma 14.4, Case I: final producer boundary

Support primality, quotient threshold geometry, inherited parity membership,
finite-layer transport, quotient bounds, `T` positivity, and Claim 14.13 are
automatic.  The earliest missing edge is error-envelope transport: at an odd
predecessor depth the parity domain starts strictly above `1`, while Claim
14.6(i) is only available from `3` onward.
-/

/-- The sole source-coordinate edge not generated by carrier geometry.  It is
stated at the literal ceiling quotient and literal moving `sourceSigma` endpoint. -/
def CaseIRecursiveCoordinateSourceSigmaQuotient
    (S : BoundingSieve) (N D : ℕ) (d s : ℝ) : Prop :=
  ∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D
      (sourceSigma (D : ℝ) d) s,
    recursiveCoordinate D p ≤ sourceSigma ((D ⌈/⌉ p : ℕ) : ℝ) d

private theorem caseI_carrier_scale
    (S : BoundingSieve) {D Dmin : ℕ} {σ s : ℝ}
    (hDmin : 2 ≤ Dmin) (hD : Dmin ^ 2 ≤ D) (hs : 2 ≤ s) :
    CarrierQuotientThresholdGeometry S.prodPrimes.primeFactors D Dmin σ s := by
  intro p hp
  have hp' := hp
  simp only [sigmaOneCarrier, Finset.mem_filter] at hp'
  have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hp'.1
  have hD1 : (1 : ℝ) ≤ (D : ℝ) := by
    exact_mod_cast (show 1 ≤ D by nlinarith)
  have hrootOrder : (D : ℝ) ^ (1 / s) ≤ (D : ℝ) ^ (1 / (2 : ℝ)) :=
    rpow_one_div_mono_of_le hD1 (by norm_num) hs
  have hpRoot : (p : ℝ) < (D : ℝ) ^ (1 / (2 : ℝ)) := hp'.2.2.trans_le hrootOrder
  have hsquareR : (p : ℝ) ^ (2 : ℕ) < (D : ℝ) := by
    have hiff := Real.lt_rpow_inv_iff_of_pos
      (x := (p : ℝ)) (y := (D : ℝ)) (z := (2 : ℝ))
      (by positivity) (by positivity) (by norm_num)
    norm_num [one_div] at hiff hpRoot ⊢
    exact hiff.mp hpRoot
  have hsquare : p ^ 2 < D := by exact_mod_cast hsquareR
  by_cases hminp : Dmin ≤ p
  · calc
      Dmin * p ≤ p * p := Nat.mul_le_mul_right p hminp
      _ = p ^ 2 := by ring
      _ ≤ D := Nat.le_of_lt hsquare
  · have hpmin : p < Dmin := Nat.lt_of_not_ge hminp
    calc
      Dmin * p ≤ Dmin * Dmin := Nat.mul_le_mul_left Dmin (Nat.le_of_lt hpmin)
      _ = Dmin ^ 2 := by ring
      _ ≤ D := hD

private theorem caseI_inheritedCoordinate_gt
    {D p : ℕ} {s : ℝ}
    (hp : 2 ≤ p) (hD : 1 < D) (hs : 0 < s)
    (hupper : (p : ℝ) < (D : ℝ) ^ (1 / s)) :
    s - 1 < inheritedCoordinate D p := by
  have hpR : (0 : ℝ) < (p : ℝ) := by positivity
  have hDR : (0 : ℝ) < (D : ℝ) := by positivity
  have hlogp : 0 < Real.log (p : ℝ) :=
    Real.log_pos (by exact_mod_cast (show 1 < p by omega))
  have hloglt := Real.strictMonoOn_log (show (p : ℝ) ∈ Set.Ioi 0 by exact hpR)
    (show (D : ℝ) ^ (1 / s) ∈ Set.Ioi 0 by exact Real.rpow_pos_of_pos hDR _)
    hupper
  rw [Real.log_rpow hDR] at hloglt
  unfold inheritedCoordinate
  have hsne : s ≠ 0 := ne_of_gt hs
  have : s < Real.log (D : ℝ) / Real.log (p : ℝ) := by
    rw [lt_div_iff₀ hlogp]
    field_simp [hsne] at hloglt ⊢
    nlinarith
  linarith

/-- All strict-successor pointwise premises except the genuinely missing error
transport are generated uniformly from parity and large-`D` carrier geometry. -/
theorem eventually_caseI_strict_pointwise_packet_uniform_in_S
    (H : Section13HatLayers)
    {Dmin : ℕ} {d Δ : ℝ}
    (hH : Section13HatSourceContract H) (hd1 : 1 < d) (hΔ0 : 0 < Δ)
    (hDmin : 2 ≤ Dmin) :
    ∀ᶠ D : ℕ in atTop, ∀ (S : BoundingSieve) (N : ℕ) (s : ℝ),
      2 ≤ N → s - 1 ∈ KappaOneModel.parityDomain 2 (N - 1) → 2 ≤ s →
      let σ := sourceSigma (D : ℝ) d
      CaseIErrorEnvelopeTransport S H N D d σ s →
      (∀ p ∈ S.prodPrimes.primeFactors, p.Prime) ∧
      CarrierQuotientThresholdGeometry S.prodPrimes.primeFactors D Dmin σ s ∧
      (∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D σ s,
        inheritedCoordinate D p ∈ KappaOneModel.parityDomain 2 (N - 1)) ∧
      (∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D σ s,
        finiteSourceLayer 1 2 (N - 1) (recursiveCoordinate D p) ≤
          finiteSourceLayer 1 2 (N - 1) (inheritedCoordinate D p)) ∧
      CaseIErrorEnvelopeTransport S H N D d σ s ∧
      (∀ p ∈ S.prodPrimes.primeFactors,
        (D : ℝ) ^ (1 / σ) ≤ (p : ℝ) → (p : ℝ) < (D : ℝ) ^ (1 / s) →
        2 ≤ p ∧ 2 * p ≤ D) ∧
      (∀ p ∈ S.prodPrimes.primeFactors,
        (D : ℝ) ^ (1 / σ) ≤ (p : ℝ) → (p : ℝ) < (D : ℝ) ^ (1 / s) →
        0 ≤ H.T (ErrorSign.ofDepth (N - 1)) (inheritedCoordinate D p)) ∧
      (∀ p ∈ S.prodPrimes.primeFactors,
        (D : ℝ) ^ (1 / σ) ≤ (p : ℝ) → (p : ℝ) < (D : ℝ) ^ (1 / s) →
        Claim14_13PointwisePremise H N (D : ℝ) d Δ
          (Real.log (D : ℝ) / Real.log (p : ℝ)) ((D : ℝ) / (p : ℝ))) := by
  filter_upwards [eventually_ge_atTop (Dmin ^ 2)] with D hDsq
  intro S N s hN hspred hs
  dsimp only
  intro herror
  have hscale := caseI_carrier_scale S (σ := sourceSigma (D : ℝ) d)
    hDmin hDsq hs
  have hD1 : 1 < D := by
    have : 4 ≤ Dmin ^ 2 := by nlinarith
    omega
  have hprime : ∀ p ∈ S.prodPrimes.primeFactors, p.Prime := by
    intro p hp
    exact Nat.prime_of_mem_primeFactors hp
  have hceil : ∀ p ∈ S.prodPrimes.primeFactors,
      (D : ℝ) ^ (1 / sourceSigma (D : ℝ) d) ≤ (p : ℝ) →
      (p : ℝ) < (D : ℝ) ^ (1 / s) → 2 ≤ p ∧ 2 * p ≤ D := by
    intro p hp hpl hpu
    have hpCarrier : p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D
        (sourceSigma (D : ℝ) d) s := by
      simp only [sigmaOneCarrier, Finset.mem_filter]
      exact ⟨hp, hpl, hpu⟩
    exact ⟨(hprime p hp).two_le,
      (Nat.mul_le_mul_right p hDmin).trans (hscale p hpCarrier)⟩
  have hinherited : ∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D
      (sourceSigma (D : ℝ) d) s,
      inheritedCoordinate D p ∈ KappaOneModel.parityDomain 2 (N - 1) := by
    intro p hp
    have hp' := hp
    simp only [sigmaOneCarrier, Finset.mem_filter] at hp'
    apply parityDomain_mono hspred
    exact (caseI_inheritedCoordinate_gt (hprime p hp'.1).two_le hD1
      (lt_of_lt_of_le (by norm_num) hs) hp'.2.2).le
  have hsource : ∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D
      (sourceSigma (D : ℝ) d) s,
      finiteSourceLayer 1 2 (N - 1) (recursiveCoordinate D p) ≤
        finiteSourceLayer 1 2 (N - 1) (inheritedCoordinate D p) := by
    intro p hp
    have hp' := hp
    simp only [sigmaOneCarrier, Finset.mem_filter] at hp'
    obtain ⟨hp2, h2p⟩ := hceil p hp'.1 hp'.2.1 hp'.2.2
    have hrec := parityDomain_mono (hinherited p hp) (coordinate_bounds hp2 h2p).1
    exact finiteSourceLayer_recursive_le_inherited (by norm_num) (N - 1) D p
      hp2 h2p (hinherited p hp) hrec
  have hT : ∀ p ∈ S.prodPrimes.primeFactors,
      (D : ℝ) ^ (1 / sourceSigma (D : ℝ) d) ≤ (p : ℝ) →
      (p : ℝ) < (D : ℝ) ^ (1 / s) →
      0 ≤ H.T (ErrorSign.ofDepth (N - 1)) (inheritedCoordinate D p) := by
    intro p hp _hpl hpu
    have hx0 : 0 < inheritedCoordinate D p :=
      lt_trans (by linarith : 0 < s - 1)
        (caseI_inheritedCoordinate_gt (hprime p hp).two_le hD1 (by linarith) hpu)
    exact (hH.positive _ _ hx0).le
  have h1413 : ∀ p ∈ S.prodPrimes.primeFactors,
      (D : ℝ) ^ (1 / sourceSigma (D : ℝ) d) ≤ (p : ℝ) →
      (p : ℝ) < (D : ℝ) ^ (1 / s) →
      Claim14_13PointwisePremise H N (D : ℝ) d Δ
        (Real.log (D : ℝ) / Real.log (p : ℝ)) ((D : ℝ) / (p : ℝ)) := by
    intro p hp hpl hpu
    obtain ⟨hp2, h2p⟩ := hceil p hp hpl hpu
    exact claim14_13_pointwise_carrier H (by omega) hp2 h2p hd1 hΔ0
      (by simpa [inheritedCoordinate] using hT p hp hpl hpu)
  exact ⟨hprime, hscale, hinherited, hsource, herror, hceil, hT, h1413⟩

/-- Compatibility specialization of the pointwise packet uniform in `S`. -/
theorem eventually_caseI_strict_pointwise_packet
    (S : BoundingSieve) (H : Section13HatLayers)
    {Dmin : ℕ} {d Δ : ℝ}
    (hH : Section13HatSourceContract H) (hd1 : 1 < d) (hΔ0 : 0 < Δ)
    (hDmin : 2 ≤ Dmin) :
    ∀ᶠ D : ℕ in atTop, ∀ (N : ℕ) (s : ℝ),
      2 ≤ N → s - 1 ∈ KappaOneModel.parityDomain 2 (N - 1) → 2 ≤ s →
      let σ := sourceSigma (D : ℝ) d
      CaseIErrorEnvelopeTransport S H N D d σ s →
      (∀ p ∈ S.prodPrimes.primeFactors, p.Prime) ∧
      CarrierQuotientThresholdGeometry S.prodPrimes.primeFactors D Dmin σ s ∧
      (∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D σ s,
        inheritedCoordinate D p ∈ KappaOneModel.parityDomain 2 (N - 1)) ∧
      (∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D σ s,
        finiteSourceLayer 1 2 (N - 1) (recursiveCoordinate D p) ≤
          finiteSourceLayer 1 2 (N - 1) (inheritedCoordinate D p)) ∧
      CaseIErrorEnvelopeTransport S H N D d σ s ∧
      (∀ p ∈ S.prodPrimes.primeFactors,
        (D : ℝ) ^ (1 / σ) ≤ (p : ℝ) → (p : ℝ) < (D : ℝ) ^ (1 / s) →
        2 ≤ p ∧ 2 * p ≤ D) ∧
      (∀ p ∈ S.prodPrimes.primeFactors,
        (D : ℝ) ^ (1 / σ) ≤ (p : ℝ) → (p : ℝ) < (D : ℝ) ^ (1 / s) →
        0 ≤ H.T (ErrorSign.ofDepth (N - 1)) (inheritedCoordinate D p)) ∧
      (∀ p ∈ S.prodPrimes.primeFactors,
        (D : ℝ) ^ (1 / σ) ≤ (p : ℝ) → (p : ℝ) < (D : ℝ) ^ (1 / s) →
        Claim14_13PointwisePremise H N (D : ℝ) d Δ
          (Real.log (D : ℝ) / Real.log (p : ℝ)) ((D : ℝ) / (p : ℝ))) := by
  filter_upwards [eventually_caseI_strict_pointwise_packet_uniform_in_S
    H hH hd1 hΔ0 hDmin] with D hD
  exact hD S

/-- Callable strict Case-I producer.  Every carrierwise geometry and error
transport family is internal.  Besides the standard Case-I domain data, its
pointwise recursive inputs are exactly the named quotient-coordinate edge and
the global depth induction hypothesis. -/
theorem lemma14_4_caseI_final_producer_internal
    (S : BoundingSieve) (H : Section13HatLayers)
    {Dmin : ℕ} {C C145 K d Δ : ℝ}
    (hH : Section13HatSourceContract H)
    (hd1 : 1 < d) (hΔ0 : 0 < Δ) (hΔ1 : Δ < 1)
    (hd : 7 / (1 - Δ) < d)
    (hK : 2 ≤ K) (hlocal : HasDimensionOneLocalProductBound S K)
    (hC : 0 < C) (hC145 : 0 < C145)
    (hDmin : 2 ≤ Dmin) :
    ∀ᶠ D : ℕ in atTop, ∀ (N : ℕ) (s : ℝ),
      2 ≤ N →
      s ∈ KappaOneModel.parityDomain 2 N →
      s - 1 ∈ KappaOneModel.parityDomain 2 (N - 1) →
      2 ≤ s →
      2 + (ErrorSign.ofDepth N).epsilon ≤ s →
      s ≤ sourceSigma (D : ℝ) d →
      H.betaHat + (ErrorSign.ofDepth N).epsilon < s →
      GlobalDepthLemma144InductionHypothesis
        (suzukiActualT S) (fun p => suzukiVProduct S p)
        (fun n D' x => errorEnvelope H n (D' : ℝ) d x)
        2 C K Δ (N - 1) Dmin →
      suzukiActualT S N D ⌈(D : ℝ) ^ (1 / s)⌉₊ ≤
        suzukiVProduct S ⌈(D : ℝ) ^ (1 / s)⌉₊ *
          finiteSourceLayer 1 2 N s +
        sigma12InheritedBudget S H N D ⌈(D : ℝ) ^ (1 / s)⌉₊ C K d Δ s := by
  obtain ⟨Dg, _hDg, hg⟩ := exists_caseI_preThreshold_geometry_packet d hd1
  have hDgN : ∀ᶠ D : ℕ in atTop, Dg ≤ (D : ℝ) :=
    tendsto_natCast_atTop_atTop.eventually (eventually_ge_atTop Dg)
  have hpkt := eventually_caseI_strict_pointwise_packet S H hH hd1 hΔ0 hDmin
  have herrorUniform :=
    eventually_caseI_errorEnvelope_transport_uniform S H hH hd1 hΔ0 hΔ1
  have hrecursiveUniform :=
    eventually_recursiveCoordinate_le_quotient_sourceSigma S hd1
  have hstrict := lemma14_4_caseI_successor_sameC_uniform_strict
    S H hH hd1 hΔ0 hΔ1 hd hK hlocal hC hC145 hDmin
  filter_upwards [hDgN, hpkt, herrorUniform, hrecursiveUniform, hstrict]
    with D hDg hpktD herrorD hrecursiveD hstrictD
  intro N s hN hsdom hspred hs hsLower hsσ hthreshold hglobal
  have g := hg D N hDg s hs hsσ
  have hinheritedForError : ∀ p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D
      (sourceSigma (D : ℝ) d) s,
      inheritedCoordinate D p ∈ KappaOneModel.parityDomain 2 (N - 1) := by
    intro p hp
    have hp' := hp
    simp only [sigmaOneCarrier, Finset.mem_filter] at hp'
    apply parityDomain_mono hspred
    have hD1 : 1 < D := lt_of_lt_of_le (by norm_num) g.hD4
    exact (caseI_inheritedCoordinate_gt (Nat.prime_of_mem_primeFactors hp'.1).two_le
      hD1 (lt_of_lt_of_le (by norm_num) hs) hp'.2.2).le
  have herror := herrorD N s hs hinheritedForError (hrecursiveD s hs)
  obtain ⟨hprime, hscale, hinherited, hsource, herror', hceil, hT, h1413⟩ :=
    hpktD N s hN hspred hs herror
  let z : ℕ := ⌈(D : ℝ) ^ (1 / s)⌉₊
  have hprimeZ : ∀ p ∈ suzukiSupportedBelow S z, p.Prime := by
    intro p hp
    exact hprime p (Finset.mem_filter.mp hp).1
  have carrier_to_full : ∀ p,
      p ∈ sigmaOneCarrier (suzukiSupportedBelow S z) D (sourceSigma (D : ℝ) d) s →
      p ∈ sigmaOneCarrier S.prodPrimes.primeFactors D (sourceSigma (D : ℝ) d) s := by
    intro p hp
    simpa only [sigmaOneCarrier, suzukiSupportedBelow, Finset.mem_filter] using
      ⟨(Finset.mem_filter.mp (Finset.mem_filter.mp hp).1).1,
        (Finset.mem_filter.mp hp).2⟩
  have hscaleZ : CarrierQuotientThresholdGeometry
      (suzukiSupportedBelow S z) D Dmin (sourceSigma (D : ℝ) d) s := by
    intro p hp
    exact hscale p (carrier_to_full p hp)
  have hinheritedZ : ∀ p ∈ sigmaOneCarrier (suzukiSupportedBelow S z) D
      (sourceSigma (D : ℝ) d) s,
      inheritedCoordinate D p ∈ KappaOneModel.parityDomain 2 (N - 1) := by
    intro p hp; exact hinherited p (carrier_to_full p hp)
  have hsourceZ : ∀ p ∈ sigmaOneCarrier (suzukiSupportedBelow S z) D
      (sourceSigma (D : ℝ) d) s,
      finiteSourceLayer 1 2 (N - 1) (recursiveCoordinate D p) ≤
        finiteSourceLayer 1 2 (N - 1) (inheritedCoordinate D p) := by
    intro p hp; exact hsource p (carrier_to_full p hp)
  have herrorZ : ∀ p ∈ sigmaOneCarrier (suzukiSupportedBelow S z) D
      (sourceSigma (D : ℝ) d) s,
      errorEnvelope H (N - 1) (D ⌈/⌉ p : ℕ) d (recursiveCoordinate D p) ≤
        errorEnvelope H (N - 1) (D ⌈/⌉ p : ℕ) d (inheritedCoordinate D p) := by
    intro p hp; exact herror' p (carrier_to_full p hp)
  have hz : z = ⌈(D : ℝ) ^ (1 / s)⌉₊ := rfl
  have hres := hstrictD N s hN hsdom hspred hs hsLower
  dsimp only at hres
  exact hres g.hD4 g.hsigma hsσ g.hpowerS g.hpowerSigma g.hpowerOrder
    hthreshold hprimeZ hscaleZ hinheritedZ hsourceZ herrorZ hglobal
    hceil hT


end MathlibNt.SieveTheory
