import MathlibNt.SieveTheory.Switching.AlternatingPairs

/-!
# Boundary-chain tails and recursive integrals

Reversed finite Rosser chains embed into alternating-pair iterates. Uniform
absolute tails and inner/outer Darboux comparisons connect their fixed-depth
densities to continuous boundary-mass integrals.

All declarations retain the `MathlibNt.SieveTheory.SwitchingPrinciple` namespace.
-/

open scoped ArithmeticFunction.Moebius
open scoped ArithmeticFunction.zeta

set_option maxHeartbeats 6000000

namespace MathlibNt.SieveTheory.SwitchingPrinciple

open Real Finset
open MeasureTheory intervalIntegral

open scoped Classical
open scoped Asymptotics

namespace Internal
end Internal

open Internal

/-- The finite carrier generated by the reverse Rosser-pair recursion.  Lists
are stored in reverse order, so the innermost pair is visible at the head. -/
noncomputable def upperRosserAlternatingPairDiscreteChains :
    ℕ → ℕ → ℝ → Finset ℕ → Finset (List ℕ)
  | 0, _q, _r, _P => {[]}
  | k + 1, q, r, P =>
      ((P.sigma fun p₀ =>
        (P.filter (fun p₁ =>
          p₁ < p₀ ∧
            2 * (Real.log p₀ / Real.log q) <
              Real.log p₁ / Real.log q + r)).sigma fun p₁ =>
            upperRosserAlternatingPairDiscreteChains k p₀
              ((r + Real.log p₁ / Real.log q +
                  Real.log p₀ / Real.log q) /
                (Real.log p₀ / Real.log q))
              (P.filter (fun p => p₀ < p)))).image
        fun b => b.2.1 :: b.1 :: b.2.2

theorem upperRosserAlternatingPairDiscreteChains_length
    {k q : ℕ} {r : ℝ} {P : Finset ℕ} {l : List ℕ}
    (hl : l ∈ upperRosserAlternatingPairDiscreteChains k q r P) :
    l.length = 2 * k := by
  induction k generalizing q r P l with
  | zero =>
      simp [upperRosserAlternatingPairDiscreteChains] at hl
      simp [hl]
  | succ k ih =>
      rw [upperRosserAlternatingPairDiscreteChains] at hl
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hl
      rcases b with ⟨p₀, ⟨p₁, xs⟩⟩
      simp only [Finset.mem_sigma] at hb
      simp [ih hb.2.2]
      omega

theorem upperRosserAlternatingPairDiscreteChains_mem_ambient
    {k q : ℕ} {r : ℝ} {P : Finset ℕ} {l : List ℕ}
    (hl : l ∈ upperRosserAlternatingPairDiscreteChains k q r P) :
    ∀ p ∈ l, p ∈ P := by
  induction k generalizing q r P l with
  | zero =>
      simp [upperRosserAlternatingPairDiscreteChains] at hl
      simp [hl]
  | succ k ih =>
      rw [upperRosserAlternatingPairDiscreteChains] at hl
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hl
      rcases b with ⟨p₀, ⟨p₁, xs⟩⟩
      simp only [Finset.mem_sigma] at hb
      intro p hp
      simp only [List.mem_cons] at hp
      rcases hp with rfl | rfl | hp
      · exact (Finset.mem_filter.mp hb.2.1).1
      · exact hb.1
      · exact (Finset.mem_filter.mp (ih hb.2.2 p hp)).1

/-- The exact even-suffix inequalities carried by a reverse-built chain, at
the current terminal prime and adaptive state. -/
def UpperRosserEvenSuffixCondition
    (z : ℝ) (q : ℕ) (r : ℝ) (l : List ℕ) : Prop :=
  ∀ (i : ℕ) (hi : i < l.length), Even i →
    2 * (Real.log (l[i] : ℝ) / Real.log z) <
      ((l.drop (i + 1)).map
        (fun p : ℕ => Real.log (p : ℝ) / Real.log z)).sum +
        r * (Real.log (q : ℝ) / Real.log z)

/-- Removing the innermost pair transports every earlier even-suffix
inequality to the adaptive state used by the reverse-pair iterate. -/
private theorem upperRosserEvenSuffixCondition_split
    {z r : ℝ} {q : ℕ} {l : List ℕ} {k : ℕ}
    (hz : 1 < z) (hq : q.Prime) (hlen : l.length = 2 * (k + 1))
    (hallPrime : ∀ p ∈ l, p.Prime)
    (hsuffix : UpperRosserEvenSuffixCondition z q r l) :
    let xs := l.take (2 * k)
    let p₀ := l[2 * k]
    let p₁ := l[2 * k + 1]
    2 * (Real.log p₀ / Real.log q) <
        Real.log p₁ / Real.log q + r ∧
      UpperRosserEvenSuffixCondition z p₀
        ((r + Real.log p₁ / Real.log q +
            Real.log p₀ / Real.log q) /
          (Real.log p₀ / Real.log q)) xs := by
  dsimp
  let xs := l.take (2 * k)
  let p₀ := l[2 * k]
  let p₁ := l[2 * k + 1]
  have hlen' : l.length = 2 * k + 2 := by omega
  have hxslen : xs.length = 2 * k := by simp [xs, hlen']
  have hdrop : l.drop (2 * k) = [p₀, p₁] := by
    rw [List.drop_eq_getElem_cons (by omega),
      List.drop_eq_getElem_cons (by omega)]
    have hend : l.drop (2 * k + 2) = [] :=
      List.drop_eq_nil_iff.mpr (by omega)
    rw [hend]
  have hform : l = xs ++ [p₀, p₁] := by
    rw [← hdrop]
    exact (List.take_append_drop (2 * k) l).symm
  have hlogz : 0 < Real.log z := Real.log_pos hz
  have hlogq : 0 < Real.log q :=
    Real.log_pos (by exact_mod_cast hq.one_lt)
  have hp₀Prime : p₀.Prime :=
    hallPrime p₀ (List.getElem_mem (l := l) (n := 2 * k) (by omega))
  have hlogp₀ : 0 < Real.log p₀ :=
    Real.log_pos (by exact_mod_cast hp₀Prime.one_lt)
  constructor
  · have hlast := hsuffix (2 * k) (by omega) (by simp)
    have hdropLast : l.drop (2 * k + 1) = [p₁] := by
      rw [List.drop_eq_getElem_cons (by omega)]
      have hend : l.drop (2 * k + 2) = [] :=
        List.drop_eq_nil_iff.mpr (by omega)
      rw [hend]
    rw [hdropLast] at hlast
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil,
      add_zero] at hlast
    have ha : 0 < Real.log q / Real.log z := div_pos hlogq hlogz
    have heqL :
        2 * (Real.log p₀ / Real.log z) =
          (2 * (Real.log p₀ / Real.log q)) *
            (Real.log q / Real.log z) := by
      field_simp
    have heqR :
        Real.log p₁ / Real.log z +
            r * (Real.log q / Real.log z) =
          (Real.log p₁ / Real.log q + r) *
            (Real.log q / Real.log z) := by
      field_simp
    rw [show (l[2 * k] : ℕ) = p₀ by rfl, heqL, heqR] at hlast
    have hresult := lt_of_mul_lt_mul_right hlast ha.le
    simpa [p₁] using hresult
  · intro i hi heven
    have hi' : i < 2 * k := by
      rw [← hxslen]
      exact hi
    have hil : i < l.length := by rw [hlen']; omega
    have horig := hsuffix i hil heven
    have hget : l[i] = xs[i] :=
      (List.getElem_take (xs := l) (j := 2 * k) (i := i)).symm
    have hidrop :
        l.drop (i + 1) = xs.drop (i + 1) ++ [p₀, p₁] := by
      calc
        l.drop (i + 1) = (xs ++ [p₀, p₁]).drop (i + 1) :=
          congrArg (List.drop (i + 1)) hform
        _ = xs.drop (i + 1) ++ [p₀, p₁] :=
          List.drop_append_of_le_length (by rw [hxslen]; omega)
    rw [hget, hidrop] at horig
    have hscale :
        ((r + Real.log p₁ / Real.log q +
            Real.log p₀ / Real.log q) /
          (Real.log p₀ / Real.log q)) *
            (Real.log p₀ / Real.log z) =
          Real.log p₀ / Real.log z + Real.log p₁ / Real.log z +
            r * (Real.log q / Real.log z) := by
      field_simp
      ring
    rw [hscale]
    change 2 * (Real.log (xs[i] : ℝ) / Real.log z) < _
    simpa only [List.map_append, List.map_cons, List.map_nil,
      List.sum_append, List.sum_cons, List.sum_nil, add_zero, add_assoc]
      using horig

/-- Exact alternating-prefix inequalities embed a decreasing chain, reversed,
in the adaptive pair carrier.  Thus every inherited screen and cutoff is
retained at every recursive pair. -/
theorem reverse_mem_upperRosserAlternatingPairDiscreteChains
    {z r : ℝ} {q k : ℕ} {P : Finset ℕ} {l : List ℕ}
    (hz : 1 < z) (hq : q.Prime) (hP : ∀ p ∈ l, p ∈ P)
    (hprime : ∀ p ∈ P, p.Prime) (hqP : ∀ p ∈ P, q < p)
    (hsorted : l.SortedGT) (hlen : l.length = 2 * k)
    (hsuffix : UpperRosserEvenSuffixCondition z q r l) :
    l.reverse ∈ upperRosserAlternatingPairDiscreteChains k q r P := by
  induction k generalizing q r P l with
  | zero =>
      have hl : l = [] := List.eq_nil_of_length_eq_zero (by simpa using hlen)
      simp [hl, upperRosserAlternatingPairDiscreteChains]
  | succ k ih =>
      let xs := l.take (2 * k)
      let p₀ := l[2 * k]
      let p₁ := l[2 * k + 1]
      have hlen' : l.length = 2 * k + 2 := by omega
      have hxslen : xs.length = 2 * k := by simp [xs, hlen']
      have hdrop : l.drop (2 * k) = [p₀, p₁] := by
        rw [List.drop_eq_getElem_cons (by omega),
          List.drop_eq_getElem_cons (by omega)]
        have hend : l.drop (2 * k + 2) = [] :=
          List.drop_eq_nil_iff.mpr (by omega)
        rw [hend]
      have hform : l = xs ++ [p₀, p₁] := by
        rw [← hdrop]
        exact (List.take_append_drop (2 * k) l).symm
      have hp₀mem : p₀ ∈ l :=
        List.getElem_mem (l := l) (n := 2 * k) (by omega)
      have hp₁mem : p₁ ∈ l :=
        List.getElem_mem (l := l) (n := 2 * k + 1) (by omega)
      have hp₀P : p₀ ∈ P := hP p₀ hp₀mem
      have hp₁P : p₁ ∈ P := hP p₁ hp₁mem
      have hpw := List.sortedGT_iff_pairwise.mp hsorted
      rw [hform, List.pairwise_append] at hpw
      have hp₁p₀ : p₁ < p₀ := by
        have hpair := hpw.2.1
        simp only [List.pairwise_cons] at hpair
        exact hpair.1 p₁ (by simp)
      have hxsSorted : xs.SortedGT :=
        List.sortedGT_iff_pairwise.mpr hpw.1
      have hxsP :
          ∀ p ∈ xs, p ∈ P.filter (fun p => p₀ < p) := by
        intro p hp
        exact Finset.mem_filter.mpr
          ⟨hP p (by rw [hform]; simp [hp]),
            hpw.2.2 p hp p₀ (by simp)⟩
      have hsplit :=
        upperRosserEvenSuffixCondition_split hz hq hlen
          (fun p hp => hprime p (hP p hp)) hsuffix
      have hxsMem := ih (hprime p₀ hp₀P) hxsP
        (fun p hp => hprime p (Finset.mem_filter.mp hp).1)
        (fun p hp => (Finset.mem_filter.mp hp).2)
        hxsSorted hxslen hsplit.2
      rw [upperRosserAlternatingPairDiscreteChains]
      apply Finset.mem_image.mpr
      refine ⟨⟨p₀, ⟨p₁, xs.reverse⟩⟩, ?_, ?_⟩
      · simp only [Finset.mem_sigma]
        exact
          ⟨hp₀P, Finset.mem_filter.mpr ⟨hp₁P, hp₁p₀, hsplit.1⟩,
            hxsMem⟩
      · rw [hform, List.reverse_append]
        simp

/-- The weighted reverse-chain carrier is bounded by the existing adaptive
pair iterate.  Nonnegativity permits enlargement to every admissible pair at
each stage. -/
theorem sum_upperRosserAlternatingPairDiscreteChains_le_iterate
    (w : ℕ → ℝ) {k q : ℕ} {r : ℝ} {P : Finset ℕ}
    (hr : 3 ≤ r) (hq : q.Prime) (hP : ∀ p ∈ P, p.Prime)
    (hqP : ∀ p ∈ P, q < p) (hw : ∀ p ∈ P, 0 ≤ w p) :
    ∑ l ∈ upperRosserAlternatingPairDiscreteChains k q r P,
        (l.map w).prod ≤
      upperRosserAlternatingPairDiscreteIterate w k q r P := by
  induction k generalizing q r P with
  | zero =>
      simp [upperRosserAlternatingPairDiscreteChains,
        upperRosserAlternatingPairDiscreteIterate]
      exact (show (1 : ℝ) ≤ r by linarith).trans (le_abs_self r)
  | succ k ih =>
      let B := P.sigma fun p₀ =>
        (P.filter (fun p₁ =>
          p₁ < p₀ ∧
            2 * (Real.log p₀ / Real.log q) <
              Real.log p₁ / Real.log q + r)).sigma fun p₁ =>
            upperRosserAlternatingPairDiscreteChains k p₀
              ((r + Real.log p₁ / Real.log q +
                  Real.log p₀ / Real.log q) /
                (Real.log p₀ / Real.log q))
              (P.filter (fun p => p₀ < p))
      let encode : (Σ _p₀ : ℕ, Σ _p₁ : ℕ, List ℕ) → List ℕ :=
        fun b => b.2.1 :: b.1 :: b.2.2
      have hinj : Set.InjOn encode (↑B) := by
        rintro ⟨p₀, ⟨p₁, xs⟩⟩ hb ⟨p₀', ⟨p₁', xs'⟩⟩ hb' heq
        dsimp [encode] at heq
        injection heq with hp₁ htail
        injection htail with hp₀ hxs
        subst p₁'
        subst p₀'
        subst xs'
        rfl
      rw [upperRosserAlternatingPairDiscreteChains, show
        ((P.sigma fun p₀ =>
          (P.filter (fun p₁ =>
            p₁ < p₀ ∧
              2 * (Real.log p₀ / Real.log q) <
                Real.log p₁ / Real.log q + r)).sigma fun p₁ =>
              upperRosserAlternatingPairDiscreteChains k p₀
                ((r + Real.log p₁ / Real.log q +
                    Real.log p₀ / Real.log q) /
                  (Real.log p₀ / Real.log q))
                (P.filter (fun p => p₀ < p))).image
          fun b => b.2.1 :: b.1 :: b.2.2) = B.image encode by rfl,
        Finset.sum_image hinj]
      simp only [B, Finset.sum_sigma]
      rw [upperRosserAlternatingPairDiscreteIterate]
      apply Finset.sum_le_sum
      intro p₀ hp₀
      apply Finset.sum_le_sum
      intro p₁ hp₁
      have hp₁' := Finset.mem_filter.mp hp₁
      have hp₀Prime := hP p₀ hp₀
      have hp₁Prime := hP p₁ hp₁'.1
      have hqpos : (0 : ℝ) < q := by exact_mod_cast hq.pos
      have hlogq : 0 < Real.log q :=
        Real.log_pos (by exact_mod_cast hq.one_lt)
      have hp₀pos : (0 : ℝ) < p₀ := by exact_mod_cast hp₀Prime.pos
      have hp₁pos : (0 : ℝ) < p₁ := by exact_mod_cast hp₁Prime.pos
      have hy : Real.log p₁ / Real.log q ∈ Set.Ioo (1 : ℝ) r := by
        have hqy : Real.log q < Real.log p₁ :=
          (Real.strictMonoOn_log.lt_iff_lt hqpos hp₁pos).2
            (by exact_mod_cast hqP p₁ hp₁'.1)
        have hyx :
            Real.log p₁ / Real.log q <
              Real.log p₀ / Real.log q := by
          apply (div_lt_div_iff_of_pos_right hlogq).2
          exact (Real.strictMonoOn_log.lt_iff_lt hp₁pos hp₀pos).2
            (by exact_mod_cast hp₁'.2.1)
        constructor
        · exact (lt_div_iff₀ hlogq).2 (by simpa using hqy)
        · linarith [hp₁'.2.2, hyx]
      have hx :
          Real.log p₀ / Real.log q ∈
            Set.Ioo (Real.log p₁ / Real.log q)
              ((Real.log p₁ / Real.log q + r) / 2) := by
        constructor
        · apply (div_lt_div_iff_of_pos_right hlogq).2
          exact (Real.strictMonoOn_log.lt_iff_lt hp₁pos hp₀pos).2
            (by exact_mod_cast hp₁'.2.1)
        · linarith [hp₁'.2.2]
      have hnext :
          3 ≤
            (r + Real.log p₁ / Real.log q +
                Real.log p₀ / Real.log q) /
              (Real.log p₀ / Real.log q) :=
        (LinearSieve.upperRosserAlternatingPair_nextRatio_gt_three hy hx).le
      have hinner := ih hnext hp₀Prime
        (fun p hp => hP p (Finset.mem_filter.mp hp).1)
        (fun p hp => (Finset.mem_filter.mp hp).2)
        (fun p hp => hw p (Finset.mem_filter.mp hp).1)
      have hweight : 0 ≤ w p₁ * w p₀ :=
        mul_nonneg (hw p₁ hp₁'.1) (hw p₀ hp₀)
      calc
        (∑ xs ∈ upperRosserAlternatingPairDiscreteChains k p₀
              ((r + Real.log p₁ / Real.log q +
                  Real.log p₀ / Real.log q) /
                (Real.log p₀ / Real.log q))
              (P.filter (fun p => p₀ < p)),
            (List.map w (p₁ :: p₀ :: xs)).prod) =
            (w p₁ * w p₀) *
              ∑ xs ∈ upperRosserAlternatingPairDiscreteChains k p₀
                  ((r + Real.log p₁ / Real.log q +
                      Real.log p₀ / Real.log q) /
                    (Real.log p₀ / Real.log q))
                  (P.filter (fun p => p₀ < p)),
                (List.map w xs).prod := by
          simp only [List.map_cons, List.prod_cons]
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro xs hxs
          ring
        _ ≤ (w p₁ * w p₀) *
              upperRosserAlternatingPairDiscreteIterate w k p₀
                ((r + Real.log p₁ / Real.log q +
                    Real.log p₀ / Real.log q) /
                  (Real.log p₀ / Real.log q))
                (P.filter (fun p => p₀ < p)) :=
          mul_le_mul_of_nonneg_left hinner hweight
        _ = w p₀ * w p₁ *
              upperRosserAlternatingPairDiscreteIterate w k p₀
                ((r + Real.log p₁ / Real.log q +
                    Real.log p₀ / Real.log q) /
                  (Real.log p₀ / Real.log q))
                (P.filter (fun p => p₀ < p)) := by ring

/-- Every actual boundary chain of depth `2k` lies in the reverse-pair carrier.
This is the bridge from the natural Rosser cutoff to the adaptive discrete
iterate; it uses every even-prefix inequality through its suffix form. -/
theorem upperRosserBoundaryChains_reverse_mem_alternatingPairDiscreteChains
    {S : BoundingSieve} {z Δ s : ℝ} {q k : ℕ} {l : List ℕ}
    (hz : 2 ≤ z) (hΔ : 0 < Δ) (hs : s = Real.log Δ / Real.log z)
    (hcut : ∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z)
    (hq : q ∈ S.prodPrimes.primeFactors)
    (hl : l ∈ LinearSieve.upperRosserBoundaryChains
      (Nat.floor Δ + 1) q
      (S.prodPrimes.primeFactors.filter (fun p => q < p)))
    (hlen : l.length = 2 * k) :
    l.reverse ∈ upperRosserAlternatingPairDiscreteChains k q 3
      (S.prodPrimes.primeFactors.filter (fun p => q < p)) := by
  let P := S.prodPrimes.primeFactors.filter (fun p => q < p)
  have hqPrime : q.Prime := Nat.prime_of_mem_primeFactors hq
  have hchain := (LinearSieve.mem_upperRosserBoundaryChains_iff
    (P := P) (by simp [P]) hqPrime
    (fun p hp => (Finset.mem_filter.mp hp).2.le)).mp
      (by simpa [P] using hl)
  have hmem : ∀ p ∈ l, p ∈ P := by
    intro p hp
    exact hchain.2.2.1 (by simpa using hp)
  have hprime : ∀ p ∈ P, p.Prime := by
    intro p hp
    exact Nat.prime_of_mem_primeFactors (Finset.mem_filter.mp hp).1
  have hsuffix : UpperRosserEvenSuffixCondition z q 3 l := by
    intro i hi heven
    have h :=
      upperRosserBoundaryChains_logarithmicCoordinates_even_lt_suffix
        hz hΔ hs hcut hq hl (i := i)
          (by simpa [LinearSieve.logarithmicCoordinates] using hi) heven
    simpa [LinearSieve.logarithmicCoordinates,
      UpperRosserEvenSuffixCondition] using h
  exact reverse_mem_upperRosserAlternatingPairDiscreteChains
    (by linarith) hqPrime hmem hprime
    (fun p hp => (Finset.mem_filter.mp hp).2)
    hchain.2.1 hlen hsuffix

/-- The reverse-pair carrier dominates the fixed-depth boundary density for any
nonnegative ambient weight.  This weight-generic form is what permits the same
geometric carrier to be used before or after Euler normalization. -/
theorem upperRosserBoundaryChainsFixedDepthDensity_le_alternatingPairDiscreteIterate_of_nonneg
    (w : ℕ → ℝ) {S : BoundingSieve} {z Δ s : ℝ} {q k : ℕ}
    (hz : 2 ≤ z) (hΔ : 0 < Δ) (hs : s = Real.log Δ / Real.log z)
    (hcut : ∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z)
    (hq : q ∈ S.prodPrimes.primeFactors)
    (hw : ∀ p ∈ S.prodPrimes.primeFactors, 0 ≤ w p) :
    LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
        w (Nat.floor Δ + 1) q
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) k ≤
      upperRosserAlternatingPairDiscreteIterate w k q 3
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) := by
  classical
  let P := S.prodPrimes.primeFactors.filter (fun p => q < p)
  let A := (LinearSieve.upperRosserBoundaryChains
    (Nat.floor Δ + 1) q P).filter (fun l => l.length = 2 * k)
  have hreverseInj :
      Set.InjOn (fun l : List ℕ => l.reverse) (↑A : Set (List ℕ)) := by
    intro l hl l' hl' heq
    exact List.reverse_inj.mp heq
  have hsubset :
      A.image (fun l : List ℕ => l.reverse) ⊆
        upperRosserAlternatingPairDiscreteChains k q 3 P := by
    intro rl hrl
    obtain ⟨l, hl, rfl⟩ := Finset.mem_image.mp hrl
    have hl' := Finset.mem_filter.mp hl
    exact
      upperRosserBoundaryChains_reverse_mem_alternatingPairDiscreteChains
        hz hΔ hs hcut hq (by simpa [P] using hl'.1) hl'.2
  have himage :
      (∑ l ∈ A, (l.map w).prod) =
        ∑ l ∈ A.image (fun l : List ℕ => l.reverse), (l.map w).prod := by
    rw [Finset.sum_image hreverseInj]
    apply Finset.sum_congr rfl
    intro l hl
    rw [List.map_reverse, List.prod_reverse]
  have hambient :
      ∀ l ∈ upperRosserAlternatingPairDiscreteChains k q 3 P,
        0 ≤ (l.map w).prod := by
    intro l hl
    apply List.prod_nonneg
    intro x hx
    obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hx
    exact hw p (Finset.mem_filter.mp
      (upperRosserAlternatingPairDiscreteChains_mem_ambient hl p hp)).1
  have henlarge :
      (∑ l ∈ A.image (fun l : List ℕ => l.reverse), (l.map w).prod) ≤
        ∑ l ∈ upperRosserAlternatingPairDiscreteChains k q 3 P,
          (l.map w).prod :=
    Finset.sum_le_sum_of_subset_of_nonneg hsubset
      (fun l hl hnot => hambient l hl)
  have hqPrime : q.Prime := Nat.prime_of_mem_primeFactors hq
  have hcarrier :=
    sum_upperRosserAlternatingPairDiscreteChains_le_iterate w
      (k := k) (q := q) (r := (3 : ℝ)) (P := P)
      (by norm_num) hqPrime
      (fun p hp =>
        Nat.prime_of_mem_primeFactors (Finset.mem_filter.mp hp).1)
      (fun p hp => (Finset.mem_filter.mp hp).2)
      (fun p hp => hw p (Finset.mem_filter.mp hp).1)
  unfold LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
  change (∑ l ∈ A, (l.map w).prod) ≤ _
  rw [himage]
  exact henlarge.trans hcarrier

/-- The actual normalized fixed-depth boundary-chain density is dominated by
the reverse-pair iterate.  No unordered or factorial majorant is used: the
injection reverses each canonical chain and preserves its monomial exactly. -/
theorem upperRosserBoundaryChainsFixedDepthDensity_le_alternatingPairDiscreteIterate
    {S : BoundingSieve} {z Δ s : ℝ} {q k : ℕ}
    (hz : 2 ≤ z) (hΔ : 0 < Δ) (hs : s = Real.log Δ / Real.log z)
    (hcut : ∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z)
    (hq : q ∈ S.prodPrimes.primeFactors) :
    LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
        (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) k ≤
      upperRosserAlternatingPairDiscreteIterate
        (fun p => S.nu p / (1 - S.nu p)) k q 3
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) := by
  exact
    upperRosserBoundaryChainsFixedDepthDensity_le_alternatingPairDiscreteIterate_of_nonneg
      (fun p => S.nu p / (1 - S.nu p)) hz hΔ hs hcut hq
      (fun _ hp => nu_div_one_sub_nonneg_of_mem hp)

/-- The actual fixed-depth boundary density on the relative Euler-product scale
is dominated by the relative adaptive reverse-pair state.  This is the exact
embedding needed before proving a contraction that preserves the sieve product. -/
theorem upperRosserBoundaryChainsFixedDepthRelativeDensity_le_alternatingPairDiscreteRelativeIterate
    {S : BoundingSieve} {z Δ s : ℝ} {q k : ℕ}
    (hz : 2 ≤ z) (hΔ : 0 < Δ) (hs : s = Real.log Δ / Real.log z)
    (hcut : ∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z)
    (hq : q ∈ S.prodPrimes.primeFactors) :
    LinearSieve.upperRosserBoundaryChainsFixedDepthRelativeDensity
        S.nu (Nat.floor Δ + 1) q
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) k ≤
      upperRosserAlternatingPairDiscreteRelativeIterate S.nu k q 3
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) := by
  let P := S.prodPrimes.primeFactors.filter (fun p => q < p)
  have hprodPos : 0 < ∏ p ∈ P, (1 - S.nu p) := by
    apply Finset.prod_pos
    intro p hp
    have hpS := (Finset.mem_filter.mp hp).1
    have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hpS
    have hpDvd : p ∣ S.prodPrimes :=
      (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hpS |>.2
    exact sub_pos.mpr (S.nu_lt_one_of_prime p hpPrime hpDvd)
  have hselected :=
    upperRosserBoundaryChainsFixedDepthDensity_le_alternatingPairDiscreteIterate_of_nonneg
      S.nu (k := k) hz hΔ hs hcut hq
        (fun p hp => by
          have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hp
          have hpDvd : p ∣ S.prodPrimes :=
            (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hp |>.2
          exact (S.nu_pos_of_prime p hpPrime hpDvd).le)
  unfold LinearSieve.upperRosserBoundaryChainsFixedDepthRelativeDensity
    upperRosserAlternatingPairDiscreteRelativeIterate
  apply (div_le_div_iff_of_pos_right hprodPos).2
  simpa [P] using hselected

/-- The geometric reverse-pair estimate applies to the actual normalized
boundary-chain density, uniformly in the level, sieve, and terminal prime. -/
theorem
    exists_upperRosserBoundaryChainsFixedDepthDensity_eventually_geometric
    (K : ℝ) (hK : 1 ≤ K) :
    ∃ N : ℕ, ∃ C : ℝ, 0 ≤ C ∧
      ∀ (S : BoundingSieve) (k : ℕ) (q : ℕ) (z Δ s : ℝ),
        2 ≤ z → 0 < Δ → s = Real.log Δ / Real.log z →
        HasDimensionOneLocalProductBound S K →
        (∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z) →
        q ∈ S.prodPrimes.primeFactors →
        LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
            (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
            (S.prodPrimes.primeFactors.filter (fun p => q < p)) (k + N) ≤
          9 * C * (9 / 10 : ℝ) ^ k := by
  obtain ⟨N, C, hC, hiterate⟩ :=
    exists_upperRosserAlternatingPairDiscreteIterate_eventually_geometric K hK
  refine ⟨N, C, hC, ?_⟩
  intro S k q z Δ s hz hΔ hs hlocal hcut hq
  let P := S.prodPrimes.primeFactors.filter (fun p => q < p)
  have hqPrime : q.Prime := Nat.prime_of_mem_primeFactors hq
  have hembed :=
    upperRosserBoundaryChainsFixedDepthDensity_le_alternatingPairDiscreteIterate
      (k := k + N) hz hΔ hs hcut hq
  have hbound :=
    hiterate S k q 3 P hqPrime hlocal (by norm_num)
      (fun p hp => (Finset.mem_filter.mp hp).1)
      (fun p hp => (Finset.mem_filter.mp hp).2)
  calc
    LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
        (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
        (S.prodPrimes.primeFactors.filter (fun p => q < p)) (k + N) ≤
      upperRosserAlternatingPairDiscreteIterate
        (fun p => S.nu p / (1 - S.nu p)) (k + N) q 3 P := by
          simpa [P] using hembed
    _ ≤ C * (9 / 10 : ℝ) ^ k * 3 ^ 2 := hbound
    _ = 9 * C * (9 / 10 : ℝ) ^ k := by ring

/-- A genuine uniform tail function for the actual normalized boundary-chain
density at each terminal prime.  The offset is the finite number of coarse
steps, and the displayed envelope tends to zero independently of all sieve
parameters. -/
theorem exists_upperRosserBoundaryChainsFixedDepthDensity_uniform_tail
    (K : ℝ) (hK : 1 ≤ K) :
    ∃ N : ℕ, ∃ τ : ℕ → ℝ,
      Filter.Tendsto τ Filter.atTop (nhds 0) ∧
      ∀ (S : BoundingSieve) (L n : ℕ) (q : ℕ) (z Δ s : ℝ),
        2 ≤ z → 0 < Δ → s = Real.log Δ / Real.log z →
        HasDimensionOneLocalProductBound S K →
        (∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z) →
        q ∈ S.prodPrimes.primeFactors →
        (∑ j ∈ Finset.range n,
          LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
            (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
            (S.prodPrimes.primeFactors.filter (fun p => q < p))
            (L + j + N)) ≤ τ L := by
  obtain ⟨N, C, hC, hdepth⟩ :=
    exists_upperRosserBoundaryChainsFixedDepthDensity_eventually_geometric K hK
  let τ : ℕ → ℝ := fun L => 90 * C * (9 / 10 : ℝ) ^ L
  have hpow :
      Filter.Tendsto (fun L : ℕ => (9 / 10 : ℝ) ^ L)
        Filter.atTop (nhds 0) :=
    tendsto_pow_atTop_nhds_zero_of_lt_one (by norm_num) (by norm_num)
  have hτ : Filter.Tendsto τ Filter.atTop (nhds 0) := by
    simpa [τ] using
      (tendsto_const_nhds.mul hpow :
        Filter.Tendsto (fun L : ℕ => (90 * C) * (9 / 10 : ℝ) ^ L)
          Filter.atTop (nhds ((90 * C) * 0)))
  refine ⟨N, τ, hτ, ?_⟩
  intro S L n q z Δ s hz hΔ hs hlocal hcut hq
  have hterms :
      (∑ j ∈ Finset.range n,
        LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
          (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
          (S.prodPrimes.primeFactors.filter (fun p => q < p))
          (L + j + N)) ≤
        ∑ j ∈ Finset.range n,
          9 * C * (9 / 10 : ℝ) ^ (L + j) := by
    apply Finset.sum_le_sum
    intro j hj
    exact hdepth S (L + j) q z Δ s hz hΔ hs hlocal hcut hq
  have hgeom :
      (∑ j ∈ Finset.range n, (9 / 10 : ℝ) ^ j) ≤ 10 := by
    calc
      (∑ j ∈ Finset.range n, (9 / 10 : ℝ) ^ j) ≤
          ∑' j : ℕ, (9 / 10 : ℝ) ^ j :=
        (summable_geometric_of_lt_one (by norm_num) (by norm_num)).sum_le_tsum
          (Finset.range n) (by intro j hj; positivity)
      _ = (1 - (9 / 10 : ℝ))⁻¹ :=
        tsum_geometric_of_lt_one (by norm_num) (by norm_num)
      _ = 10 := by norm_num
  calc
    (∑ j ∈ Finset.range n,
        LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
          (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
          (S.prodPrimes.primeFactors.filter (fun p => q < p))
          (L + j + N)) ≤
      ∑ j ∈ Finset.range n, 9 * C * (9 / 10 : ℝ) ^ (L + j) :=
        hterms
    _ = (9 * C * (9 / 10 : ℝ) ^ L) *
        ∑ j ∈ Finset.range n, (9 / 10 : ℝ) ^ j := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro j hj
      rw [pow_add]
      ring
    _ ≤ (9 * C * (9 / 10 : ℝ) ^ L) * 10 :=
      mul_le_mul_of_nonneg_left hgeom (by positivity)
    _ = τ L := by
      dsimp [τ]
      ring

/-- Equivalently, after one uniform pair-depth cutoff, every finite remaining
block of the actual normalized boundary-chain density is smaller than a
prescribed error. -/
theorem exists_upperRosserBoundaryChainsFixedDepthDensity_uniform_tail_lt
    (K ρ : ℝ) (hK : 1 ≤ K) (hρ : 0 < ρ) :
    ∃ N L : ℕ,
      ∀ (S : BoundingSieve) (n : ℕ) (q : ℕ) (z Δ s : ℝ),
        2 ≤ z → 0 < Δ → s = Real.log Δ / Real.log z →
        HasDimensionOneLocalProductBound S K →
        (∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z) →
        q ∈ S.prodPrimes.primeFactors →
        (∑ j ∈ Finset.range n,
          LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
            (fun p => S.nu p / (1 - S.nu p)) (Nat.floor Δ + 1) q
            (S.prodPrimes.primeFactors.filter (fun p => q < p))
            (L + j + N)) < ρ := by
  obtain ⟨N, τ, hτ, hbound⟩ :=
    exists_upperRosserBoundaryChainsFixedDepthDensity_uniform_tail K hK
  have hevent := hτ.eventually (Iio_mem_nhds hρ)
  rw [Filter.eventually_atTop] at hevent
  obtain ⟨L, hL⟩ := hevent
  refine ⟨N, L, ?_⟩
  intro S n q z Δ s hz hΔ hs hlocal hcut hq
  exact (hbound S L n q z Δ s hz hΔ hs hlocal hcut hq).trans_lt
    (hL L le_rfl)

/-- Multiplication by the complete Euler product cancels the normalized
denominators above a distinguished prime.  What remains is its density times
the product of the factors at all earlier primes. -/
theorem normalizedBoundaryTail_mul_eulerProduct_eq_orderedMass
    {P : Finset ℕ} {q : ℕ} {f : ℕ → ℝ} (hq : q ∈ P)
    (hfactor : ∀ p ∈ P, 1 - f p ≠ 0) (A : ℝ) :
    ((f q / (1 - f q)) *
          (A / ∏ p ∈ P.filter (fun p => q < p), (1 - f p))) *
        ∏ p ∈ P, (1 - f p) =
      (f q * ∏ p ∈ P.filter (fun p => p < q), (1 - f p)) * A := by
  classical
  let L := P.filter (fun p => p < q)
  let U := P.filter (fun p => q < p)
  have hP : P = insert q (L ∪ U) := by
    ext p
    simp only [L, U, Finset.mem_insert, Finset.mem_union, Finset.mem_filter]
    constructor
    · intro hp
      by_cases hpq : p = q
      · exact Or.inl hpq
      · rcases lt_or_gt_of_ne hpq with hpq | hpq
        · exact Or.inr (Or.inl ⟨hp, hpq⟩)
        · exact Or.inr (Or.inr ⟨hp, hpq⟩)
    · rintro (rfl | (⟨hp, _⟩ | ⟨hp, _⟩))
      · exact hq
      · exact hp
      · exact hp
  have hqLU : q ∉ L ∪ U := by simp [L, U]
  have hLU : Disjoint L U := by
    rw [Finset.disjoint_left]
    intro p hpL hpU
    simp only [L, Finset.mem_filter] at hpL
    simp only [U, Finset.mem_filter] at hpU
    omega
  have hprod : (∏ p ∈ P, (1 - f p)) =
      (1 - f q) * (∏ p ∈ L, (1 - f p)) * ∏ p ∈ U, (1 - f p) := by
    rw [hP, Finset.prod_insert hqLU, Finset.prod_union hLU]
    ring
  have hqfactor : 1 - f q ≠ 0 := hfactor q hq
  have hUfactor : (∏ p ∈ U, (1 - f p)) ≠ 0 := by
    apply Finset.prod_ne_zero_iff.mpr
    intro p hp
    exact hfactor p (Finset.mem_filter.mp hp).1
  change ((f q / (1 - f q)) *
        (A / ∏ p ∈ U, (1 - f p))) * ∏ p ∈ P, (1 - f p) =
      (f q * ∏ p ∈ L, (1 - f p)) * A
  rw [hprod]
  field_simp [hqfactor, hUfactor]

/-- A sieve density is bounded by its normalized Euler increment. -/
theorem nu_le_nu_div_one_sub_of_mem
    {S : BoundingSieve} {p : ℕ} (hp : p ∈ S.prodPrimes.primeFactors) :
    S.nu p ≤ S.nu p / (1 - S.nu p) := by
  have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hp
  have hpDvd : p ∣ S.prodPrimes :=
    (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hp |>.2
  have hnuPos := S.nu_pos_of_prime p hpPrime hpDvd
  have hnuLt := S.nu_lt_one_of_prime p hpPrime hpDvd
  rw [le_div_iff₀ (sub_pos.mpr hnuLt)]
  nlinarith [sq_nonneg (S.nu p)]

/-- The ordered masses left after exact Euler cancellation have total at most
one.  This is the finite telescoping identity behind the global Rosser tail. -/
theorem sum_nu_mul_prod_one_sub_lt_le_one (S : BoundingSieve) :
    ∑ q ∈ S.prodPrimes.primeFactors,
        S.nu q * ∏ p ∈ S.prodPrimes.primeFactors.filter (fun p => p < q),
          (1 - S.nu p) ≤ 1 := by
  have hprod : 0 ≤ ∏ p ∈ S.prodPrimes.primeFactors, (1 - S.nu p) := by
    apply Finset.prod_nonneg
    intro p hp
    have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hp
    have hpDvd : p ∣ S.prodPrimes :=
      (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hp |>.2
    exact sub_nonneg.mpr (S.nu_lt_one_of_prime p hpPrime hpDvd).le
  have hordered :=
    Finset.prod_one_sub_ordered S.prodPrimes.primeFactors S.nu
  linarith

/-- After exact cancellation of the skipped Euler factors, the geometric
reverse-pair estimate gives a uniform absolute tail for the complete outer-prime
sum.  Unlike a pointwise terminal-prime estimate, this bound is summable because
the remaining ordered terminal masses telescope to at most one.  The bound is
absolute; it does not contain an additional full Euler-product factor. -/
theorem exists_upperRosserBoundaryChains_global_uniform_absolute_tail
    (K : ℝ) (hK : 1 ≤ K) :
    ∃ N : ℕ, ∃ τ : ℕ → ℝ,
      Filter.Tendsto τ Filter.atTop (nhds 0) ∧
      (∀ L, 0 ≤ τ L) ∧
      ∀ (S : BoundingSieve) (L n : ℕ) (z Δ s : ℝ),
        2 ≤ z → 0 < Δ → s = Real.log Δ / Real.log z →
        HasDimensionOneLocalProductBound S K →
        (∀ p ∈ S.prodPrimes.primeFactors, (p : ℝ) ≤ z) →
        (∑ q ∈ S.prodPrimes.primeFactors,
          (S.nu q / (1 - S.nu q)) *
            ((∑ j ∈ Finset.range n,
              LinearSieve.upperRosserBoundaryChainsFixedDepthDensity S.nu
                (Nat.floor Δ + 1) q
                (S.prodPrimes.primeFactors.filter (fun p => q < p))
                (L + j + N)) /
              ∏ p ∈ S.prodPrimes.primeFactors.filter (fun p => q < p),
                (1 - S.nu p))) *
          ∏ p ∈ S.prodPrimes.primeFactors, (1 - S.nu p) ≤ τ L := by
  obtain ⟨N, τ₀, hτ₀, htail⟩ :=
    exists_upperRosserBoundaryChainsFixedDepthDensity_uniform_tail K hK
  let τ : ℕ → ℝ := fun L => |τ₀ L|
  have hτ : Filter.Tendsto τ Filter.atTop (nhds 0) := by
    simpa [τ] using hτ₀.abs
  refine ⟨N, τ, hτ, fun L => abs_nonneg _, ?_⟩
  intro S L n z Δ s hz hΔ hs hlocal hcut
  let P := S.prodPrimes.primeFactors
  let B : ℕ → ℝ := fun q =>
    ∑ j ∈ Finset.range n,
      LinearSieve.upperRosserBoundaryChainsFixedDepthDensity S.nu
        (Nat.floor Δ + 1) q (P.filter (fun p => q < p)) (L + j + N)
  have hfactor : ∀ p ∈ P, 1 - S.nu p ≠ 0 := by
    intro p hp
    have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hp
    have hpDvd : p ∣ S.prodPrimes :=
      (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hp |>.2
    exact ne_of_gt (sub_pos.mpr (S.nu_lt_one_of_prime p hpPrime hpDvd))
  have hterminal : ∀ q ∈ P,
      0 ≤ S.nu q * ∏ p ∈ P.filter (fun p => p < q), (1 - S.nu p) := by
    intro q hq
    apply mul_nonneg
    · have hqPrime : q.Prime := Nat.prime_of_mem_primeFactors hq
      have hqDvd : q ∣ S.prodPrimes :=
        (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hq |>.2
      exact (S.nu_pos_of_prime q hqPrime hqDvd).le
    · apply Finset.prod_nonneg
      intro p hp
      have hpP := (Finset.mem_filter.mp hp).1
      have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hpP
      have hpDvd : p ∣ S.prodPrimes :=
        (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hpP |>.2
      exact sub_nonneg.mpr (S.nu_lt_one_of_prime p hpPrime hpDvd).le
  have hraw : ∀ q ∈ P, B q ≤ τ L := by
    intro q hq
    have hmono :
        B q ≤
          ∑ j ∈ Finset.range n,
            LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
              (fun p => S.nu p / (1 - S.nu p))
              (Nat.floor Δ + 1) q (P.filter (fun p => q < p))
              (L + j + N) := by
      dsimp [B]
      apply Finset.sum_le_sum
      intro j hj
      apply LinearSieve.upperRosserBoundaryChainsFixedDepthDensity_mono
      · intro p hp
        have hpP := (Finset.mem_filter.mp hp).1
        have hpPrime : p.Prime := Nat.prime_of_mem_primeFactors hpP
        have hpDvd : p ∣ S.prodPrimes :=
          (Nat.mem_primeFactors_of_ne_zero S.prodPrimes_ne_zero).mp hpP |>.2
        exact (S.nu_pos_of_prime p hpPrime hpDvd).le
      · intro p hp
        exact nu_le_nu_div_one_sub_of_mem (Finset.mem_filter.mp hp).1
    calc
      B q ≤
          ∑ j ∈ Finset.range n,
            LinearSieve.upperRosserBoundaryChainsFixedDepthDensity
              (fun p => S.nu p / (1 - S.nu p))
              (Nat.floor Δ + 1) q (P.filter (fun p => q < p))
              (L + j + N) := hmono
      _ ≤ τ₀ L := by
        simpa [P] using htail S L n q z Δ s hz hΔ hs hlocal hcut hq
      _ ≤ τ L := by
        dsimp [τ]
        exact le_abs_self _
  have hterminalSum :
      (∑ q ∈ P,
        S.nu q * ∏ p ∈ P.filter (fun p => p < q), (1 - S.nu p)) ≤ 1 := by
    simpa [P] using sum_nu_mul_prod_one_sub_lt_le_one S
  rw [Finset.sum_mul]
  change (∑ q ∈ P,
      ((S.nu q / (1 - S.nu q)) *
        (B q / ∏ p ∈ P.filter (fun p => q < p), (1 - S.nu p))) *
          ∏ p ∈ P, (1 - S.nu p)) ≤ τ L
  calc
    (∑ q ∈ P,
        ((S.nu q / (1 - S.nu q)) *
          (B q / ∏ p ∈ P.filter (fun p => q < p), (1 - S.nu p))) *
            ∏ p ∈ P, (1 - S.nu p)) =
        ∑ q ∈ P,
          (S.nu q * ∏ p ∈ P.filter (fun p => p < q), (1 - S.nu p)) *
            B q := by
      apply Finset.sum_congr rfl
      intro q hq
      exact normalizedBoundaryTail_mul_eulerProduct_eq_orderedMass
        hq hfactor (B q)
    _ ≤ ∑ q ∈ P,
        (S.nu q * ∏ p ∈ P.filter (fun p => p < q), (1 - S.nu p)) *
          τ L := by
      apply Finset.sum_le_sum
      intro q hq
      exact mul_le_mul_of_nonneg_left (hraw q hq) (hterminal q hq)
    _ = τ L * ∑ q ∈ P,
        S.nu q * ∏ p ∈ P.filter (fun p => p < q), (1 - S.nu p) := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro q hq
      ring
    _ ≤ τ L * 1 :=
      mul_le_mul_of_nonneg_left hterminalSum (abs_nonneg _)
    _ = τ L := by ring

/-- Removing a one-cell thickening from the inherited upper face costs at most
its width times the uniform screened integrand bound. -/
theorem integral_screened_upperRosserBoundaryMassAux_succ_le
    (k : ℕ) {c s a r w : ℝ} (hc : 0 < c) (hca : c ≤ a)
    (har : a ≤ r) (hr : r ≤ 1) (hw : 0 ≤ w) :
    (∫ x in Set.Ioo c 1, x⁻¹ *
        (if x < r + w then
          LinearSieve.upperRosserBoundaryMassAux (k + 1) (s - r - x) a x
        else 0)) ≤
      (∫ x in Set.Ioo a r, x⁻¹ *
        LinearSieve.upperRosserBoundaryMassAux (k + 1) (s - r - x) a x) +
        c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) * w := by
  let u := min 1 (r + w)
  let B := (c⁻¹ * c⁻¹) ^ (k + 1)
  let g : ℝ → ℝ := fun x => x⁻¹ *
    LinearSieve.upperRosserBoundaryMassAux (k + 1) (s - r - x) a x
  have hcu : c ≤ u := by
    dsimp [u]
    exact hca.trans (har.trans (le_min hr (le_add_of_nonneg_right hw)))
  have hru : r ≤ u := by
    dsimp [u]
    exact le_min hr (le_add_of_nonneg_right hw)
  have hu1 : u ≤ 1 := min_le_left _ _
  have hB : 0 ≤ B := by
    dsimp [B]
    positivity
  have hg_nonneg : ∀ x ∈ Set.Ioo c 1, 0 ≤ g x := by
    intro x hx
    exact mul_nonneg (inv_nonneg.mpr (hc.le.trans hx.1.le))
      (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1) (hc.le.trans hca))
  have hg_bound : ∀ x ∈ Set.Ioo c 1, g x ≤ c⁻¹ * B := by
    intro x hx
    have hxpos : 0 < x := hc.trans hx.1
    have hxinv : x⁻¹ ≤ c⁻¹ := (inv_le_inv₀ hxpos hc).2 hx.1.le
    have hmass :
        LinearSieve.upperRosserBoundaryMassAux (k + 1) (s - r - x) a x ≤ B := by
      simpa [B] using LinearSieve.upperRosserBoundaryMassAux_le_of_lower_bound
        (k + 1) hc hca hx.2.le
    exact mul_le_mul hxinv hmass
      (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1) (hc.le.trans hca))
      (inv_nonneg.mpr hc.le)
  have hint : MeasureTheory.IntegrableOn g (Set.Ioo c 1) := by
    have hfinite : MeasureTheory.volume (Set.Ioo c 1) < ⊤ := by
      rw [Real.volume_Ioo]
      exact ENNReal.ofReal_lt_top
    have hmeas : MeasureTheory.StronglyMeasurable g := by
      dsimp [g]
      exact measurable_id.inv.stronglyMeasurable.mul
        ((LinearSieve.stronglyMeasurable_upperRosserBoundaryMassAux
          (k + 1)).comp_measurable
            (show Measurable (fun x : ℝ => ((s - r - x, a), x)) by fun_prop))
    apply MeasureTheory.IntegrableOn.of_bound hfinite hmeas.aestronglyMeasurable
      (c⁻¹ * B)
    filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ioo] with x hx
    rw [Real.norm_eq_abs, abs_of_nonneg (hg_nonneg x hx)]
    exact hg_bound x hx
  have hscreen :
      (∫ x in Set.Ioo c 1, x⁻¹ *
          (if x < r + w then
            LinearSieve.upperRosserBoundaryMassAux (k + 1) (s - r - x) a x
          else 0)) = ∫ x in Set.Ioo c u, g x := by
    rw [show (fun x => x⁻¹ *
          (if x < r + w then
            LinearSieve.upperRosserBoundaryMassAux (k + 1) (s - r - x) a x
          else 0)) = (Set.Iio (r + w)).indicator g by
      funext x
      by_cases hx : x < r + w <;> simp [g, hx]]
    rw [MeasureTheory.setIntegral_indicator measurableSet_Iio, Set.Ioo_inter_Iio]
  have hlower : (∫ x in Set.Ioo c u, g x) = ∫ x in Set.Ioo a u, g x := by
    apply MeasureTheory.setIntegral_eq_of_subset_of_forall_sdiff_eq_zero
      measurableSet_Ioo
    · intro x hx
      exact ⟨hca.trans_lt hx.1, hx.2⟩
    · intro x hx
      have hxa : x ≤ a := le_of_not_gt fun hax => hx.2 ⟨hax, hx.1.2⟩
      dsimp [g]
      rw [LinearSieve.upperRosserBoundaryMassAux_succ_eq_zero_of_upper_le k hxa]
      simp
  have hintAR : MeasureTheory.IntegrableOn g (Set.Ioo a r) :=
    hint.mono_set (fun x hx => ⟨hca.trans_lt hx.1, hx.2.trans_le hr⟩)
  have hintRU : MeasureTheory.IntegrableOn g (Set.Ioo r u) :=
    hint.mono_set (fun x hx =>
      ⟨lt_of_le_of_lt (hca.trans har) hx.1, hx.2.trans_le hu1⟩)
  have hdecomp : (∫ x in Set.Ioo a u, g x) =
      (∫ x in Set.Ioo a r, g x) + ∫ x in Set.Ioo r u, g x := by
    calc
      (∫ x in Set.Ioo a u, g x) = ∫ x in a..u, g x := by
        rw [intervalIntegral.integral_of_le (har.trans hru),
          MeasureTheory.integral_Ioc_eq_integral_Ioo]
      _ = (∫ x in a..r, g x) + ∫ x in r..u, g x :=
        (intervalIntegral.integral_add_adjacent_intervals
          ((intervalIntegrable_iff_integrableOn_Ioo_of_le har).2 hintAR)
          ((intervalIntegrable_iff_integrableOn_Ioo_of_le hru).2 hintRU)).symm
      _ = (∫ x in Set.Ioo a r, g x) + ∫ x in Set.Ioo r u, g x := by
        rw [intervalIntegral.integral_of_le har,
          intervalIntegral.integral_of_le hru]
        simp_rw [MeasureTheory.integral_Ioc_eq_integral_Ioo]
  have hstrip : (∫ x in Set.Ioo r u, g x) ≤ c⁻¹ * B * w := by
    have hconst :
        MeasureTheory.IntegrableOn (fun _ : ℝ => c⁻¹ * B) (Set.Ioo r u) :=
      MeasureTheory.integrableOn_const (by
        rw [Real.volume_Ioo]
        exact ENNReal.ofReal_ne_top)
    calc
      (∫ x in Set.Ioo r u, g x) ≤ ∫ _x in Set.Ioo r u, c⁻¹ * B := by
        apply MeasureTheory.setIntegral_mono_on hintRU hconst measurableSet_Ioo
        intro x hx
        exact hg_bound x
          ⟨lt_of_le_of_lt (hca.trans har) hx.1, hx.2.trans_le hu1⟩
      _ = (u - r) * (c⁻¹ * B) := by
        rw [MeasureTheory.setIntegral_const, MeasureTheory.Measure.real_def,
          Real.volume_Ioo, ENNReal.toReal_ofReal (sub_nonneg.mpr hru)]
        rfl
      _ ≤ c⁻¹ * B * w := by
        have huw : u - r ≤ w := by
          dsimp [u]
          linarith [min_le_right (1 : ℝ) (r + w)]
        calc
          (u - r) * (c⁻¹ * B) ≤ w * (c⁻¹ * B) :=
            mul_le_mul_of_nonneg_right huw
              (mul_nonneg (inv_nonneg.mpr hc.le) hB)
          _ = c⁻¹ * B * w := by ring
  rw [hscreen, hlower, hdecomp]
  simpa [g, B] using add_le_add_left hstrip
    (∫ x in Set.Ioo a r, g x)

/-- The fixed-depth inner Darboux sum is bounded by the exact inner integral in
the Rosser recursion.  The extra term is the cost of deleting the one-cell
thickening used to absorb the ordered-prime boundary. -/
theorem exists_upperRosserFixedDepthMesh_innerDarboux_succ_le_integral_add
    (k : ℕ) {s₀ s₁ c ε η : ℝ} (hc : 0 < c) (hc1 : c < 1)
    (hε : 0 ≤ ε) (hη : 0 < η) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
      ∀ h j : Fin (m + 1),
        upperRosserFixedDepthMeshLeft c m h ≤
            upperRosserFixedDepthMeshRight c m j →
        (∑ i : Fin (m + 1),
          (if upperRosserFixedDepthMeshLeft c m i <
                upperRosserFixedDepthMeshRight c m j then
              LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j -
                  upperRosserFixedDepthMeshRight c m i)
                (upperRosserFixedDepthMeshLeft c m h)
                (upperRosserFixedDepthMeshRight c m i) + ε
            else 0) *
            (upperRosserFixedDepthMeshRight c m i /
                upperRosserFixedDepthMeshLeft c m i - 1)) ≤
          (∫ x in Set.Ioo (upperRosserFixedDepthMeshLeft c m h)
              (upperRosserFixedDepthMeshRight c m j),
            x⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
              (s - upperRosserFixedDepthMeshRight c m j - x)
              (upperRosserFixedDepthMeshLeft c m h) x) +
            (η + ε) / c +
            (c⁻¹ * c⁻¹) ^ (k + 1) *
              upperRosserFixedDepthMeshWidth c m / c ^ 2 +
            c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) *
              upperRosserFixedDepthMeshWidth c m := by
  obtain ⟨N, hN⟩ :=
    exists_upperRosserFixedDepthMesh_screenedInnerDarboux_succ_le_integral_add
      k hc hc1 hε hη
  refine ⟨N, ?_⟩
  intro m hm s hs h j horder
  have hscreen := hN m hm s hs h j
  have hremove :=
    integral_screened_upperRosserBoundaryMassAux_succ_le k (s := s) hc
      (upperRosserFixedDepthMeshLeft_mem hc1 m h).1 horder
      (upperRosserFixedDepthMeshRight_le_one hc1 m j)
      (upperRosserFixedDepthMeshWidth_pos hc1 m).le
  linarith

/-- On a sufficiently fine fixed mesh, the inner Rosser integral based at the
cell's lower endpoint is uniformly approximated from above by the integral based
at the true cutoff anywhere in that cell. -/
theorem exists_upperRosserFixedDepthMesh_innerIntegral_lower_le_add
    (k : ℕ) {s₀ s₁ c ε : ℝ} (hc : 0 < c) (hc1 : c < 1) (hε : 0 < ε) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
      ∀ h j : Fin (m + 1), ∀ a ∈ Set.Icc
        (upperRosserFixedDepthMeshLeft c m h)
        (upperRosserFixedDepthMeshRight c m h),
        (∫ x in Set.Ioo (upperRosserFixedDepthMeshLeft c m h)
            (upperRosserFixedDepthMeshRight c m j),
          x⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
            (s - upperRosserFixedDepthMeshRight c m j - x)
            (upperRosserFixedDepthMeshLeft c m h) x) ≤
          (∫ x in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
            x⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
              (s - upperRosserFixedDepthMeshRight c m j - x) a x) + ε := by
  obtain ⟨δ, hδ, hmod⟩ :=
    LinearSieve.exists_integral_inv_mul_upperRosserBoundaryMassAux_lower_modulus_succ
      k (s₀ := s₀) (s₁ := s₁) hc hε
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (1 - c) / δ < N := exists_nat_gt _
  refine ⟨N, ?_⟩
  intro m hm s hs h j a ha
  have hm' : (1 - c) / δ < (m : ℝ) :=
    hN.trans_le (by exact_mod_cast hm)
  have hwidth : upperRosserFixedDepthMeshWidth c m < δ := by
    have hcross : 1 - c < δ * (m : ℝ) := by
      simpa [mul_comm] using (div_lt_iff₀ hδ).1 hm'
    dsimp [upperRosserFixedDepthMeshWidth]
    rw [div_lt_iff₀ (by positivity : (0 : ℝ) < (m : ℝ) + 1)]
    nlinarith
  apply hmod hs (upperRosserFixedDepthMeshRight_mem hc1 m j)
    (upperRosserFixedDepthMeshLeft_mem hc1 m h)
  · exact ⟨(upperRosserFixedDepthMeshLeft_mem hc1 m h).1.trans ha.1,
      ha.2.trans (upperRosserFixedDepthMeshRight_mem hc1 m h).2⟩
  · exact ha.1
  · calc
      a - upperRosserFixedDepthMeshLeft c m h ≤
          upperRosserFixedDepthMeshRight c m h -
            upperRosserFixedDepthMeshLeft c m h := sub_le_sub_right ha.2 _
      _ = upperRosserFixedDepthMeshWidth c m := by
        rw [upperRosserFixedDepthMeshRight]
        ring
      _ < δ := hwidth

/-- The positive-depth inner Darboux sum is bounded by the exact recursive
integral at the true distinguished-prime cutoff.  This simultaneously removes
the ordered-prime screen thickening and the cellwise lower-cutoff displacement. -/
theorem exists_upperRosserFixedDepthMesh_innerDarboux_succ_le_trueIntegral_add
    (k : ℕ) {s₀ s₁ c ε η : ℝ} (hc : 0 < c) (hc1 : c < 1)
    (hε : 0 ≤ ε) (hη : 0 < η) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
      ∀ h j : Fin (m + 1), ∀ a ∈ Set.Icc
        (upperRosserFixedDepthMeshLeft c m h)
        (upperRosserFixedDepthMeshRight c m h),
        upperRosserFixedDepthMeshLeft c m h ≤
          upperRosserFixedDepthMeshRight c m j →
        (∑ i : Fin (m + 1),
          (if upperRosserFixedDepthMeshLeft c m i <
                upperRosserFixedDepthMeshRight c m j then
              LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j -
                  upperRosserFixedDepthMeshRight c m i)
                (upperRosserFixedDepthMeshLeft c m h)
                (upperRosserFixedDepthMeshRight c m i) + ε
            else 0) *
            (upperRosserFixedDepthMeshRight c m i /
                upperRosserFixedDepthMeshLeft c m i - 1)) ≤
          (∫ x in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
            x⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
              (s - upperRosserFixedDepthMeshRight c m j - x) a x) +
            η + (η + ε) / c +
            (c⁻¹ * c⁻¹) ^ (k + 1) *
              upperRosserFixedDepthMeshWidth c m / c ^ 2 +
            c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) *
              upperRosserFixedDepthMeshWidth c m := by
  obtain ⟨NInner, hInner⟩ :=
    exists_upperRosserFixedDepthMesh_innerDarboux_succ_le_integral_add
      k hc hc1 hε hη
  obtain ⟨NCutoff, hCutoff⟩ :=
    exists_upperRosserFixedDepthMesh_innerIntegral_lower_le_add
      k (s₀ := s₀) (s₁ := s₁) hc hc1 hη
  refine ⟨max NInner NCutoff, ?_⟩
  intro m hm s hs h j a ha horder
  have hinner := hInner m (le_max_left _ _ |>.trans hm) s hs h j horder
  have hcutoff := hCutoff m (le_max_right _ _ |>.trans hm) s hs h j a ha
  linarith

/-- The inner successor estimate with its local-product correction included.
The cutoff is uniform over the compact residual range and every distinguished
prime in its mesh cell. -/
theorem
    exists_upperRosserFixedDepthMesh_correctedInnerDarboux_succ_le_trueIntegral_add
    (k : ℕ) {K s₀ s₁ c ε η ρ B : ℝ} (hK : 0 ≤ K)
    (hc : 0 < c) (hc1 : c < 1) (hε : 0 ≤ ε) (hη : 0 < η)
    (hρ : 0 < ρ) (hB : 0 ≤ B) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∃ z₀ : ℝ, 2 ≤ z₀ ∧
      ∀ z : ℝ, z₀ ≤ z → ∀ s ∈ Set.Icc s₀ s₁,
        ∀ h j : Fin (m + 1), ∀ a ∈ Set.Icc
          (upperRosserFixedDepthMeshLeft c m h)
          (upperRosserFixedDepthMeshRight c m h),
          upperRosserFixedDepthMeshLeft c m h ≤
            upperRosserFixedDepthMeshRight c m j →
          (∀ i : Fin (m + 1),
            LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j -
                  upperRosserFixedDepthMeshRight c m i)
                (upperRosserFixedDepthMeshLeft c m h)
                (upperRosserFixedDepthMeshRight c m i) + ε ≤ B) →
          (∑ i : Fin (m + 1),
            (if upperRosserFixedDepthMeshLeft c m i <
                  upperRosserFixedDepthMeshRight c m j then
                LinearSieve.upperRosserBoundaryMassAux (k + 1)
                  (s - upperRosserFixedDepthMeshRight c m j -
                    upperRosserFixedDepthMeshRight c m i)
                  (upperRosserFixedDepthMeshLeft c m h)
                  (upperRosserFixedDepthMeshRight c m i) + ε
              else 0) *
              (upperRosserFixedDepthMeshRight c m i /
                    upperRosserFixedDepthMeshLeft c m i *
                (1 + K / (upperRosserFixedDepthMeshLeft c m i *
                  Real.log z)) - 1)) ≤
            (∫ x in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
              x⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j - x) a x) +
              η + (η + ε) / c +
              (c⁻¹ * c⁻¹) ^ (k + 1) *
                upperRosserFixedDepthMeshWidth c m / c ^ 2 +
              c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) *
                upperRosserFixedDepthMeshWidth c m + ρ := by
  obtain ⟨N, hinner⟩ :=
    exists_upperRosserFixedDepthMesh_innerDarboux_succ_le_trueIntegral_add
      k (s₀ := s₀) (s₁ := s₁) hc hc1 hε hη
  refine ⟨N, ?_⟩
  intro m hm
  obtain ⟨z₀, hz₀, hcorrection⟩ :=
    exists_upperRosserFixedDepthMesh_correctedDarboux_le_add
      m hK hρ hB hc hc1
  refine ⟨z₀, hz₀, ?_⟩
  intro z hz s hs h j a ha horder hcornerBound
  let M : Fin (m + 1) → ℝ := fun i =>
    if upperRosserFixedDepthMeshLeft c m i <
        upperRosserFixedDepthMeshRight c m j then
      LinearSieve.upperRosserBoundaryMassAux (k + 1)
        (s - upperRosserFixedDepthMeshRight c m j -
          upperRosserFixedDepthMeshRight c m i)
        (upperRosserFixedDepthMeshLeft c m h)
        (upperRosserFixedDepthMeshRight c m i) + ε
    else 0
  have hM : ∀ i, 0 ≤ M i ∧ M i ≤ B := by
    intro i
    by_cases hi : upperRosserFixedDepthMeshLeft c m i <
        upperRosserFixedDepthMeshRight c m j
    · simp only [M, if_pos hi]
      exact ⟨add_nonneg
        (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1)
          (hc.le.trans (upperRosserFixedDepthMeshLeft_mem hc1 m h).1))
        hε, hcornerBound i⟩
    · simp [M, hi, hB]
  have hcorrected := hcorrection z hz M hM
  have hpure := hinner m hm s hs h j a ha horder
  dsimp [M] at hcorrected
  linarith

/-- A sufficiently fine fixed mesh turns the exact positive-depth inner
integrals at its right endpoints into an outer Darboux sum.  The estimate is
uniform over a compact interval of residual levels. -/
theorem exists_upperRosserFixedDepthMesh_outerDarboux_succ_le_integral_add
   (k : ℕ) {s₀ s₁ a ε : ℝ} (ha : 0 < a) (ha1 : a < 1) (hε : 0 < ε) :
   ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
     (∑ j : Fin (m + 1),
         (∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight a m j),
           x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
             (s - upperRosserFixedDepthMeshRight a m j - x₁) a x₁) *
           (upperRosserFixedDepthMeshRight a m j /
             upperRosserFixedDepthMeshLeft a m j - 1)) ≤
       (∫ x₀ in Set.Ioo a 1, x₀⁻¹ * ∫ x₁ in Set.Ioo a x₀,
         x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
           (s - x₀ - x₁) a x₁) +
         ε / a +
         (a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)) *
           upperRosserFixedDepthMeshWidth a m / a ^ 2 := by
  obtain ⟨δ, hδ, hmod⟩ :=
   LinearSieve.exists_integral_inv_mul_upperRosserBoundaryMassAux_outer_modulus_succ
     k (s₀ := s₀) (s₁ := s₁) ha hε
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (1 - a) / δ < N := exists_nat_gt _
  refine ⟨N, ?_⟩
  intro m hm s hs
  let f : ℝ → ℝ := fun x₀ => ∫ x₁ in Set.Ioo a x₀,
   x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
     (s - x₀ - x₁) a x₁
  let M : Fin (m + 1) → ℝ := fun j =>
   f (upperRosserFixedDepthMeshRight a m j)
  let B := a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)
  have hw : upperRosserFixedDepthMeshWidth a m < δ := by
   have hm' : (1 - a) / δ < (m : ℝ) :=
     hN.trans_le (by exact_mod_cast hm)
   have hcross : 1 - a < δ * (m : ℝ) := by
     simpa [mul_comm] using (div_lt_iff₀ hδ).1 hm'
   dsimp [upperRosserFixedDepthMeshWidth]
   rw [div_lt_iff₀ (by positivity : (0 : ℝ) < (m : ℝ) + 1)]
   nlinarith
  have hB : 0 ≤ B := by
   dsimp [B]
   positivity
  have hfB : ∀ x ∈ Set.Icc a 1, f x ≤ B := by
   intro x hx
   exact LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
     (k + 1) ha hx.2
  have hmajorant : ∀ j : Fin (m + 1), ∀ x ∈
     Set.Ioo (upperRosserFixedDepthMeshLeft a m j)
       (upperRosserFixedDepthMeshRight a m j), M j ≤ f x + ε := by
   intro j x hx
   have hr := upperRosserFixedDepthMeshRight_mem ha1 m j
   have hl := upperRosserFixedDepthMeshLeft_mem ha1 m j
   have hxmem : x ∈ Set.Icc a 1 :=
     ⟨hl.1.trans hx.1.le, hx.2.le.trans hr.2⟩
   have hgap : 0 ≤ upperRosserFixedDepthMeshRight a m j - x ∧
       upperRosserFixedDepthMeshRight a m j - x <
         upperRosserFixedDepthMeshWidth a m := by
     constructor
     · linarith [hx.2]
     · rw [upperRosserFixedDepthMeshRight]
       linarith [hx.1]
   have hdist :
       dist (s, upperRosserFixedDepthMeshRight a m j) (s, x) < δ := by
     simp only [Prod.dist_eq, Real.dist_eq, sub_self, abs_zero]
     rw [abs_of_nonneg hgap.1, max_eq_right hgap.1]
     exact hgap.2.trans hw
   have hclose := hmod _ ⟨hs, hr⟩ _ ⟨hs, hxmem⟩ hdist
   have hle := le_abs_self (M j - f x)
   dsimp [M, f] at hclose hle ⊢
   linarith
  have hint : MeasureTheory.IntegrableOn
     (fun x => x⁻¹ * f x) (Set.Ioo a 1) := by
   simpa [f] using
     LinearSieve.integrableOn_outer_integrand_upperRosserBoundaryMassAux
       (k + 1) (s := s) ha (le_refl 1)
  simpa [M, f, B] using
   upperRosserFixedDepthMesh_darbouxSum_le_integral_add
     m ha ha1 hε.le hB hfB hmajorant hint

/-- A fixed mesh based at a uniform support cutoff also controls inner Rosser
integrals whose actual lower cutoff varies above it.  The crossing cell is
covered by the global outer-endpoint modulus. -/
theorem exists_upperRosserFixedDepthMesh_outerDarboux_succ_movingLower_le_integral_add
   (k : ℕ) {s₀ s₁ c ε : ℝ} (hc : 0 < c) (hc1 : c < 1) (hε : 0 < ε) :
   ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
     ∀ a ∈ Set.Icc c 1,
     (∑ j : Fin (m + 1),
         (∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
           x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
             (s - upperRosserFixedDepthMeshRight c m j - x₁) a x₁) *
           (upperRosserFixedDepthMeshRight c m j /
             upperRosserFixedDepthMeshLeft c m j - 1)) ≤
       (∫ x₀ in Set.Ioo c 1, x₀⁻¹ *
         ∫ x₁ in Set.Ioo a x₀,
           x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
             (s - x₀ - x₁) a x₁) +
         ε / c +
         (c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)) *
           upperRosserFixedDepthMeshWidth c m / c ^ 2 := by
  obtain ⟨δ, hδ, hmod⟩ :=
   LinearSieve.exists_integral_inv_mul_upperRosserBoundaryMassAux_outer_endpoint_modulus_succ_global
     k (s₀ := s₀) (s₁ := s₁) hc hε
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (1 - c) / δ < N := exists_nat_gt _
  refine ⟨N, ?_⟩
  intro m hm s hs a ha
  let f : ℝ → ℝ := fun x₀ => ∫ x₁ in Set.Ioo a x₀,
   x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
     (s - x₀ - x₁) a x₁
  let M : Fin (m + 1) → ℝ := fun j =>
   f (upperRosserFixedDepthMeshRight c m j)
  let B := c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)
  have hw : upperRosserFixedDepthMeshWidth c m < δ := by
   have hm' : (1 - c) / δ < (m : ℝ) :=
     hN.trans_le (by exact_mod_cast hm)
   have hcross : 1 - c < δ * (m : ℝ) := by
     simpa [mul_comm] using (div_lt_iff₀ hδ).1 hm'
   dsimp [upperRosserFixedDepthMeshWidth]
   rw [div_lt_iff₀ (by positivity : (0 : ℝ) < (m : ℝ) + 1)]
   nlinarith
  have hB : 0 ≤ B := by
   dsimp [B]
   positivity
  have hfB : ∀ x ∈ Set.Icc c 1, f x ≤ B := by
   intro x hx
   have hbound :=
     LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
       (k + 1) (s := s) (hc.trans_le ha.1) hx.2
   dsimp [f, B]
   calc
     (∫ x₁ in Set.Ioo a x, x₁⁻¹ *
         LinearSieve.upperRosserBoundaryMassAux (k + 1)
           (s - x - x₁) a x₁) ≤
         a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1) := hbound
     _ ≤ c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) := by
       have hainv : a⁻¹ ≤ c⁻¹ :=
         (inv_le_inv₀ (hc.trans_le ha.1) hc).2 ha.1
       have hainvNonneg : 0 ≤ a⁻¹ := inv_nonneg.mpr (hc.le.trans ha.1)
       have hcinvNonneg : 0 ≤ c⁻¹ := inv_nonneg.mpr hc.le
       have hsquare : a⁻¹ * a⁻¹ ≤ c⁻¹ * c⁻¹ :=
         mul_le_mul hainv hainv hainvNonneg hcinvNonneg
       exact mul_le_mul hainv
         (pow_le_pow_left₀ (mul_nonneg hainvNonneg hainvNonneg)
           hsquare (k + 1))
         (pow_nonneg (mul_nonneg hainvNonneg hainvNonneg) _)
         hcinvNonneg
  have hmajorant : ∀ j : Fin (m + 1), ∀ x ∈
     Set.Ioo (upperRosserFixedDepthMeshLeft c m j)
       (upperRosserFixedDepthMeshRight c m j), M j ≤ f x + ε := by
   intro j x hx
   have hl := upperRosserFixedDepthMeshLeft_mem hc1 m j
   have hr := upperRosserFixedDepthMeshRight_mem hc1 m j
   have hxmem : x ∈ Set.Icc c 1 :=
     ⟨hl.1.trans hx.1.le, hx.2.le.trans hr.2⟩
   have hgap : upperRosserFixedDepthMeshRight c m j - x <
       upperRosserFixedDepthMeshWidth c m := by
     rw [upperRosserFixedDepthMeshRight]
     linarith [hx.1]
   exact hmod hs ha hxmem hr hx.2.le (hgap.trans hw)
  have hintBase : MeasureTheory.IntegrableOn
     (fun x => x⁻¹ * f x) (Set.Ioo a 1) := by
   simpa [f] using
     LinearSieve.integrableOn_outer_integrand_upperRosserBoundaryMassAux
       (k + 1) (s := s) (hc.trans_le ha.1) (le_refl 1)
  have hint : MeasureTheory.IntegrableOn
     (fun x => x⁻¹ * f x) (Set.Ioo c 1) := by
   have hglobal :
       MeasureTheory.Integrable
         ((Set.Ioo a 1).indicator (fun x => x⁻¹ * f x)) :=
     hintBase.integrable_indicator measurableSet_Ioo
   apply hglobal.integrableOn.congr_fun _ measurableSet_Ioo
   intro x hx
   by_cases hax : a < x
   · have hmem : x ∈ Set.Ioo a 1 := ⟨hax, hx.2⟩
     rw [Set.indicator_of_mem hmem]
   · have hempty : Set.Ioo a x = ∅ :=
       Set.Ioo_eq_empty (not_lt.mpr (le_of_not_gt hax))
     have hnot : x ∉ Set.Ioo a 1 := fun hx' => hax hx'.1
     simp [f, hempty, hnot]
  simpa [M, f, B] using
   upperRosserFixedDepthMesh_darbouxSum_le_integral_add
     m hc hc1 hε.le hB hfB hmajorant hint

/-- A fixed mesh based at a uniform support cutoff controls the screened outer
Rosser sum even when the true lower cutoff varies above the mesh base.  Both the
lower cutoff and the moving upper screen are retained for recursive use. -/
theorem
    exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_movingLower_le_integral_add
    (k : ℕ) {s₀ s₁ c ε : ℝ} (hc : 0 < c) (hc1 : c < 1) (hε : 0 < ε) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
      ∀ a ∈ Set.Icc c 1, ∀ r w : ℝ,
      (∑ j : Fin (m + 1),
          (if upperRosserFixedDepthMeshRight c m j ≤ r + w then
            ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j - x₁) a x₁
          else 0) *
            (upperRosserFixedDepthMeshRight c m j /
              upperRosserFixedDepthMeshLeft c m j - 1)) ≤
        (∫ x₀ in Set.Ioo c 1, x₀⁻¹ *
          (if x₀ < r + w then
            ∫ x₁ in Set.Ioo a x₀,
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - x₀ - x₁) a x₁
          else 0)) +
          ε / c +
          (c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)) *
            upperRosserFixedDepthMeshWidth c m / c ^ 2 := by
  obtain ⟨δ, hδ, hmod⟩ :=
    LinearSieve.exists_integral_inv_mul_upperRosserBoundaryMassAux_outer_endpoint_modulus_succ_global
      k (s₀ := s₀) (s₁ := s₁) hc hε
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (1 - c) / δ < N := exists_nat_gt _
  refine ⟨N, ?_⟩
  intro m hm s hs a ha r w
  let f : ℝ → ℝ := fun x₀ => ∫ x₁ in Set.Ioo a x₀,
    x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
      (s - x₀ - x₁) a x₁
  let g : ℝ → ℝ := fun x => if x < r + w then f x else 0
  let M : Fin (m + 1) → ℝ := fun j =>
    if upperRosserFixedDepthMeshRight c m j ≤ r + w then
      f (upperRosserFixedDepthMeshRight c m j)
    else 0
  let B := c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)
  have hwidth : upperRosserFixedDepthMeshWidth c m < δ := by
    have hm' : (1 - c) / δ < (m : ℝ) :=
      hN.trans_le (by exact_mod_cast hm)
    have hcross : 1 - c < δ * (m : ℝ) := by
      simpa [mul_comm] using (div_lt_iff₀ hδ).1 hm'
    dsimp [upperRosserFixedDepthMeshWidth]
    rw [div_lt_iff₀ (by positivity : (0 : ℝ) < (m : ℝ) + 1)]
    nlinarith
  have hB : 0 ≤ B := by
    dsimp [B]
    positivity
  have hf_nonneg : ∀ x ∈ Set.Icc c 1, 0 ≤ f x := by
    intro x hx
    dsimp [f]
    apply MeasureTheory.integral_nonneg_of_ae
    filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ioo] with y hy
    exact mul_nonneg (inv_nonneg.mpr ((hc.le.trans ha.1).trans hy.1.le))
      (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1)
        (hc.le.trans ha.1))
  have hgB : ∀ x ∈ Set.Icc c 1, g x ≤ B := by
    intro x hx
    by_cases hscreen : x < r + w
    · dsimp [g]
      rw [if_pos hscreen]
      have hbound :=
        LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
          (k + 1) (s := s) (hc.trans_le ha.1) hx.2
      dsimp [f, B]
      calc
        (∫ x₁ in Set.Ioo a x,
            x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
              (s - x - x₁) a x₁) ≤
            a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1) := hbound
        _ ≤ c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) := by
          have hainv : a⁻¹ ≤ c⁻¹ :=
            (inv_le_inv₀ (hc.trans_le ha.1) hc).2 ha.1
          have hainvNonneg : 0 ≤ a⁻¹ := inv_nonneg.mpr (hc.le.trans ha.1)
          have hcinvNonneg : 0 ≤ c⁻¹ := inv_nonneg.mpr hc.le
          have hsquare : a⁻¹ * a⁻¹ ≤ c⁻¹ * c⁻¹ :=
            mul_le_mul hainv hainv hainvNonneg hcinvNonneg
          exact mul_le_mul hainv
            (pow_le_pow_left₀ (mul_nonneg hainvNonneg hainvNonneg)
              hsquare (k + 1))
            (pow_nonneg (mul_nonneg hainvNonneg hainvNonneg) _)
            hcinvNonneg
    · dsimp [g]
      rw [if_neg hscreen]
      exact hB
  have hmajorant : ∀ j : Fin (m + 1), ∀ x ∈
      Set.Ioo (upperRosserFixedDepthMeshLeft c m j)
        (upperRosserFixedDepthMeshRight c m j), M j ≤ g x + ε := by
    intro j x hx
    by_cases hj :
        upperRosserFixedDepthMeshRight c m j ≤ r + w
    · have hxscreen : x < r + w := hx.2.trans_le hj
      have hl := upperRosserFixedDepthMeshLeft_mem hc1 m j
      have hr := upperRosserFixedDepthMeshRight_mem hc1 m j
      have hxmem : x ∈ Set.Icc c 1 :=
        ⟨hl.1.trans hx.1.le, hx.2.le.trans hr.2⟩
      have hgap : upperRosserFixedDepthMeshRight c m j - x <
          upperRosserFixedDepthMeshWidth c m := by
        rw [upperRosserFixedDepthMeshRight]
        linarith [hx.1]
      have hclose := hmod hs ha hxmem hr hx.2.le (hgap.trans hwidth)
      have hle := le_abs_self
        (f (upperRosserFixedDepthMeshRight c m j) - f x)
      dsimp [M, g]
      rw [if_pos hj, if_pos hxscreen]
      dsimp [f] at hclose hle ⊢
      linarith
    · have hxmem : x ∈ Set.Icc c 1 := by
        have hl := upperRosserFixedDepthMeshLeft_mem hc1 m j
        have hr := upperRosserFixedDepthMeshRight_mem hc1 m j
        exact ⟨hl.1.trans hx.1.le, hx.2.le.trans hr.2⟩
      dsimp [M]
      rw [if_neg hj]
      exact add_nonneg (by
        dsimp [g]
        split_ifs
        · exact hf_nonneg x hxmem
        · exact le_rfl) hε.le
  have hintBase : MeasureTheory.IntegrableOn
      (fun x => x⁻¹ * f x) (Set.Ioo a 1) := by
    simpa [f] using
      LinearSieve.integrableOn_outer_integrand_upperRosserBoundaryMassAux
        (k + 1) (s := s) (hc.trans_le ha.1) (le_refl 1)
  have hintExtended : MeasureTheory.IntegrableOn
      (fun x => x⁻¹ * f x) (Set.Ioo c 1) := by
    have hglobal :
        MeasureTheory.Integrable
          ((Set.Ioo a 1).indicator (fun x => x⁻¹ * f x)) :=
      hintBase.integrable_indicator measurableSet_Ioo
    apply hglobal.integrableOn.congr_fun _ measurableSet_Ioo
    intro x hx
    by_cases hax : a < x
    · rw [Set.indicator_of_mem
        (show x ∈ Set.Ioo a 1 from ⟨hax, hx.2⟩)]
    · have hempty : Set.Ioo a x = ∅ :=
        Set.Ioo_eq_empty (not_lt.mpr (le_of_not_gt hax))
      have hnot : x ∉ Set.Ioo a 1 := fun hx' => hax hx'.1
      simp [f, hempty, hnot]
  have hint : MeasureTheory.IntegrableOn
      (fun x => x⁻¹ * g x) (Set.Ioo c 1) := by
    rw [show (fun x => x⁻¹ * g x) =
        (Set.Iio (r + w)).indicator (fun x => x⁻¹ * f x) by
      funext x
      by_cases hx : x < r + w <;> simp [g, hx]]
    exact hintExtended.indicator measurableSet_Iio
  simpa [M, g, f, B] using
    upperRosserFixedDepthMesh_darbouxSum_le_integral_add
      m hc hc1 hε.le hB hgB hmajorant hint

/-- The outer positive-depth Darboux estimate remains uniform after imposing a
moving upper screen.  Right-endpoint evaluation makes the discontinuity
one-sided: an active mesh endpoint forces its whole open cell to be active. -/
theorem exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_le_integral_add
   (k : ℕ) {s₀ s₁ a ε : ℝ} (ha : 0 < a) (ha1 : a < 1) (hε : 0 < ε) :
   ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁, ∀ r w : ℝ,
     (∑ j : Fin (m + 1),
         (if upperRosserFixedDepthMeshRight a m j < r + w then
           ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight a m j),
             x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
               (s - upperRosserFixedDepthMeshRight a m j - x₁) a x₁
         else 0) *
           (upperRosserFixedDepthMeshRight a m j /
             upperRosserFixedDepthMeshLeft a m j - 1)) ≤
       (∫ x₀ in Set.Ioo a 1, x₀⁻¹ *
         (if x₀ < r + w then
           ∫ x₁ in Set.Ioo a x₀,
             x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
               (s - x₀ - x₁) a x₁
         else 0)) +
         ε / a +
         (a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)) *
           upperRosserFixedDepthMeshWidth a m / a ^ 2 := by
  obtain ⟨δ, hδ, hmod⟩ :=
   LinearSieve.exists_integral_inv_mul_upperRosserBoundaryMassAux_outer_modulus_succ
     k (s₀ := s₀) (s₁ := s₁) ha hε
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (1 - a) / δ < N := exists_nat_gt _
  refine ⟨N, ?_⟩
  intro m hm s hs r w
  let f : ℝ → ℝ := fun x₀ => ∫ x₁ in Set.Ioo a x₀,
   x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
     (s - x₀ - x₁) a x₁
  let g : ℝ → ℝ := fun x => if x < r + w then f x else 0
  let M : Fin (m + 1) → ℝ := fun j =>
   if upperRosserFixedDepthMeshRight a m j < r + w then
     f (upperRosserFixedDepthMeshRight a m j)
   else 0
  let B := a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)
  have hw : upperRosserFixedDepthMeshWidth a m < δ := by
   have hm' : (1 - a) / δ < (m : ℝ) :=
     hN.trans_le (by exact_mod_cast hm)
   have hcross : 1 - a < δ * (m : ℝ) := by
     simpa [mul_comm] using (div_lt_iff₀ hδ).1 hm'
   dsimp [upperRosserFixedDepthMeshWidth]
   rw [div_lt_iff₀ (by positivity : (0 : ℝ) < (m : ℝ) + 1)]
   nlinarith
  have hB : 0 ≤ B := by
   dsimp [B]
   positivity
  have hf_nonneg : ∀ x ∈ Set.Icc a 1, 0 ≤ f x := by
   intro x hx
   dsimp [f]
   apply MeasureTheory.integral_nonneg_of_ae
   filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ioo] with y hy
   exact mul_nonneg (inv_nonneg.mpr (ha.le.trans hy.1.le))
     (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1) ha.le)
  have hfB : ∀ x ∈ Set.Icc a 1, g x ≤ B := by
   intro x hx
   by_cases hscreen : x < r + w
   · dsimp [g]
     rw [if_pos hscreen]
     exact LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
       (k + 1) ha hx.2
   · dsimp [g]
     rw [if_neg hscreen]
     exact hB
  have hmajorant : ∀ j : Fin (m + 1), ∀ x ∈
     Set.Ioo (upperRosserFixedDepthMeshLeft a m j)
       (upperRosserFixedDepthMeshRight a m j), M j ≤ g x + ε := by
   intro j x hx
   by_cases hj :
       upperRosserFixedDepthMeshRight a m j < r + w
   · have hxscreen : x < r + w := hx.2.trans hj
     have hr := upperRosserFixedDepthMeshRight_mem ha1 m j
     have hl := upperRosserFixedDepthMeshLeft_mem ha1 m j
     have hxmem : x ∈ Set.Icc a 1 :=
       ⟨hl.1.trans hx.1.le, hx.2.le.trans hr.2⟩
     have hgap : 0 ≤ upperRosserFixedDepthMeshRight a m j - x ∧
         upperRosserFixedDepthMeshRight a m j - x <
           upperRosserFixedDepthMeshWidth a m := by
       constructor
       · linarith [hx.2]
       · rw [upperRosserFixedDepthMeshRight]
         linarith [hx.1]
     have hdist :
         dist (s, upperRosserFixedDepthMeshRight a m j) (s, x) < δ := by
       simp only [Prod.dist_eq, Real.dist_eq, sub_self, abs_zero]
       rw [abs_of_nonneg hgap.1, max_eq_right hgap.1]
       exact hgap.2.trans hw
     have hclose := hmod _ ⟨hs, hr⟩ _ ⟨hs, hxmem⟩ hdist
     have hle := le_abs_self
       (f (upperRosserFixedDepthMeshRight a m j) - f x)
     dsimp [M, g]
     rw [if_pos hj, if_pos hxscreen]
     dsimp [f] at hclose hle ⊢
     linarith
   · have hxmem : x ∈ Set.Icc a 1 := by
       have hr := upperRosserFixedDepthMeshRight_mem ha1 m j
       have hl := upperRosserFixedDepthMeshLeft_mem ha1 m j
       exact ⟨hl.1.trans hx.1.le, hx.2.le.trans hr.2⟩
     dsimp [M]
     rw [if_neg hj]
     exact add_nonneg (by
       dsimp [g]
       split_ifs
       · exact hf_nonneg x hxmem
       · exact le_refl 0) hε.le
  have hintBase : MeasureTheory.IntegrableOn
     (fun x => x⁻¹ * f x) (Set.Ioo a 1) := by
   simpa [f] using
     LinearSieve.integrableOn_outer_integrand_upperRosserBoundaryMassAux
       (k + 1) (s := s) ha (le_refl 1)
  have hint : MeasureTheory.IntegrableOn
     (fun x => x⁻¹ * g x) (Set.Ioo a 1) := by
   rw [show (fun x => x⁻¹ * g x) =
       (Set.Iio (r + w)).indicator (fun x => x⁻¹ * f x) by
     funext x
     by_cases hx : x < r + w <;> simp [g, hx]]
   exact hintBase.indicator measurableSet_Iio
  simpa [M, g, f, B] using
   upperRosserFixedDepthMesh_darbouxSum_le_integral_add
     m ha ha1 hε.le hB hfB hmajorant hint

/-- Removing a one-cell thickening from an inherited moving outer Rosser face
costs at most the mesh width times the uniform bound for the complete outer
integrand.  The endpoint `b` is retained for recursive applications. -/
theorem integral_screened_outerRosserBoundaryMassAux_succ_le_massAux
    (k : ℕ) {s a b r w : ℝ} (ha : 0 < a) (har : a ≤ r)
    (hb1 : b ≤ 1) (hw : 0 ≤ w) (hr : r = min b (s / 3)) :
    (∫ x₀ in Set.Ioo a 1, x₀⁻¹ *
        (if x₀ < r + w then
          ∫ x₁ in Set.Ioo a x₀, x₁⁻¹ *
            LinearSieve.upperRosserBoundaryMassAux (k + 1)
              (s - x₀ - x₁) a x₁
        else 0)) ≤
      LinearSieve.upperRosserBoundaryMassAux (k + 2) s a b +
        (a⁻¹ * a⁻¹) ^ (k + 2) * w := by
  let u := min 1 (r + w)
  let B := (a⁻¹ * a⁻¹) ^ (k + 2)
  let f : ℝ → ℝ := fun x₀ => ∫ x₁ in Set.Ioo a x₀,
    x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
      (s - x₀ - x₁) a x₁
  let g : ℝ → ℝ := fun x₀ => x₀⁻¹ * f x₀
  have hr1 : r ≤ 1 := by
    rw [hr]
    exact (min_le_left b (s / 3)).trans hb1
  have hru : r ≤ u := by
    dsimp [u]
    exact le_min hr1 (le_add_of_nonneg_right hw)
  have hu1 : u ≤ 1 := min_le_left _ _
  have hau : a ≤ u := har.trans hru
  have hB : 0 ≤ B := by
    dsimp [B]
    positivity
  have hf_nonneg : ∀ x ∈ Set.Icc a 1, 0 ≤ f x := by
    intro x hx
    dsimp [f]
    apply MeasureTheory.integral_nonneg_of_ae
    filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ioo] with y hy
    exact mul_nonneg (inv_nonneg.mpr (ha.le.trans hy.1.le))
      (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1) ha.le)
  have hg_nonneg : ∀ x ∈ Set.Icc a 1, 0 ≤ g x := by
    intro x hx
    exact mul_nonneg (inv_nonneg.mpr (ha.le.trans hx.1)) (hf_nonneg x hx)
  have hg_bound : ∀ x ∈ Set.Icc a 1, g x ≤ B := by
    intro x hx
    have hxpos : 0 < x := ha.trans_le hx.1
    have hxinv : x⁻¹ ≤ a⁻¹ := (inv_le_inv₀ hxpos ha).2 hx.1
    have hfbound : f x ≤ a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1) := by
      exact LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
        (k + 1) ha hx.2
    calc
      g x ≤ a⁻¹ * (a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)) := by
        dsimp [g]
        exact mul_le_mul hxinv hfbound (hf_nonneg x hx) (inv_nonneg.mpr ha.le)
      _ = B := by
        dsimp [B]
        rw [pow_succ]
        ring
  have hint : MeasureTheory.IntegrableOn g (Set.Ioo a 1) := by
    simpa [g, f] using
      LinearSieve.integrableOn_outer_integrand_upperRosserBoundaryMassAux
        (k + 1) (s := s) ha (le_refl 1)
  have hscreen :
      (∫ x₀ in Set.Ioo a 1, x₀⁻¹ *
          (if x₀ < r + w then f x₀ else 0)) =
        ∫ x₀ in Set.Ioo a u, g x₀ := by
    rw [show (fun x₀ => x₀⁻¹ * (if x₀ < r + w then f x₀ else 0)) =
        (Set.Iio (r + w)).indicator g by
      funext x₀
      by_cases hx : x₀ < r + w <;> simp [g, hx]]
    rw [MeasureTheory.setIntegral_indicator measurableSet_Iio, Set.Ioo_inter_Iio]
  have hintAR : MeasureTheory.IntegrableOn g (Set.Ioo a r) :=
    hint.mono_set (fun x hx => ⟨hx.1, hx.2.trans_le hr1⟩)
  have hintRU : MeasureTheory.IntegrableOn g (Set.Ioo r u) :=
    hint.mono_set (fun x hx => ⟨har.trans_lt hx.1, hx.2.trans_le hu1⟩)
  have hdecomp : (∫ x in Set.Ioo a u, g x) =
      (∫ x in Set.Ioo a r, g x) + ∫ x in Set.Ioo r u, g x := by
    calc
      (∫ x in Set.Ioo a u, g x) = ∫ x in a..u, g x := by
        rw [intervalIntegral.integral_of_le hau,
          MeasureTheory.integral_Ioc_eq_integral_Ioo]
      _ = (∫ x in a..r, g x) + ∫ x in r..u, g x :=
        (intervalIntegral.integral_add_adjacent_intervals
          ((intervalIntegrable_iff_integrableOn_Ioo_of_le har).2 hintAR)
          ((intervalIntegrable_iff_integrableOn_Ioo_of_le hru).2 hintRU)).symm
      _ = (∫ x in Set.Ioo a r, g x) + ∫ x in Set.Ioo r u, g x := by
        rw [intervalIntegral.integral_of_le har,
          intervalIntegral.integral_of_le hru]
        simp_rw [MeasureTheory.integral_Ioc_eq_integral_Ioo]
  have hstrip : (∫ x in Set.Ioo r u, g x) ≤ B * w := by
    have hconst :
        MeasureTheory.IntegrableOn (fun _ : ℝ => B) (Set.Ioo r u) :=
      MeasureTheory.integrableOn_const (by
        rw [Real.volume_Ioo]
        exact ENNReal.ofReal_ne_top)
    calc
      (∫ x in Set.Ioo r u, g x) ≤ ∫ _x in Set.Ioo r u, B := by
        apply MeasureTheory.setIntegral_mono_on hintRU hconst measurableSet_Ioo
        intro x hx
        exact hg_bound x ⟨har.trans (hx.1.le), hx.2.le.trans hu1⟩
      _ = (u - r) * B := by
        rw [MeasureTheory.setIntegral_const, MeasureTheory.Measure.real_def,
          Real.volume_Ioo, ENNReal.toReal_ofReal (sub_nonneg.mpr hru)]
        rfl
      _ ≤ B * w := by
        have huw : u - r ≤ w := by
          dsimp [u]
          linarith [min_le_right (1 : ℝ) (r + w)]
        simpa [mul_comm] using mul_le_mul_of_nonneg_right huw hB
  rw [show (fun x₀ => x₀⁻¹ *
      (if x₀ < r + w then
        ∫ x₁ in Set.Ioo a x₀, x₁⁻¹ *
          LinearSieve.upperRosserBoundaryMassAux (k + 1)
            (s - x₀ - x₁) a x₁
      else 0)) =
      (fun x₀ => x₀⁻¹ * (if x₀ < r + w then f x₀ else 0)) by rfl,
    hscreen, hdecomp]
  rw [show k + 2 = (k + 1) + 1 by omega,
    LinearSieve.upperRosserBoundaryMassAux_succ, ← hr]
  simpa [g, f, B] using
    add_le_add_left hstrip (∫ x in Set.Ioo a r, g x)

/-- Removing the one-cell thickening from the global moving outer Rosser face
costs at most the mesh width times the uniform bound for the complete outer
integrand. -/
theorem integral_screened_outerRosserBoundaryMassAux_succ_le
    (k : ℕ) {s a r w : ℝ} (ha : 0 < a) (har : a ≤ r)
    (_hr1 : r ≤ 1) (hw : 0 ≤ w) (hr : r = min 1 (s / 3)) :
    (∫ x₀ in Set.Ioo a 1, x₀⁻¹ *
        (if x₀ < r + w then
          ∫ x₁ in Set.Ioo a x₀, x₁⁻¹ *
            LinearSieve.upperRosserBoundaryMassAux (k + 1)
              (s - x₀ - x₁) a x₁
        else 0)) ≤
      LinearSieve.upperRosserBoundaryMassAux (k + 2) s a 1 +
        (a⁻¹ * a⁻¹) ^ (k + 2) * w := by
  exact integral_screened_outerRosserBoundaryMassAux_succ_le_massAux
    k ha har (le_refl 1) hw hr

/-- The moving-lower outer Darboux sum is bounded by the recursive Rosser mass
with its inherited upper face.  This is the induction-closed outer quadrature:
the exact screen is `min b (s / 3)`, while the mesh itself only uses the common
positive support cutoff `c`. -/
theorem
    exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_movingLower_le_massAux_add
    (k : ℕ) {s₀ s₁ c ε : ℝ} (hc : 0 < c) (hc1 : c < 1) (hε : 0 < ε) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
      ∀ a ∈ Set.Icc c 1, ∀ b : ℝ, b ≤ 1 → a ≤ min b (s / 3) →
      (∑ j : Fin (m + 1),
          (if upperRosserFixedDepthMeshRight c m j ≤
              min b (s / 3) + upperRosserFixedDepthMeshWidth c m then
            ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j - x₁) a x₁
          else 0) *
            (upperRosserFixedDepthMeshRight c m j /
              upperRosserFixedDepthMeshLeft c m j - 1)) ≤
        LinearSieve.upperRosserBoundaryMassAux (k + 2) s a b +
          (a⁻¹ * a⁻¹) ^ (k + 2) *
            upperRosserFixedDepthMeshWidth c m +
          ε / c +
          (c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)) *
            upperRosserFixedDepthMeshWidth c m / c ^ 2 := by
  obtain ⟨N, hN⟩ :=
    exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_movingLower_le_integral_add
      k (s₀ := s₀) (s₁ := s₁) hc hc1 hε
  refine ⟨N, ?_⟩
  intro m hm s hs a ha b hb1 hscreenLower
  have hwidth : 0 ≤ upperRosserFixedDepthMeshWidth c m :=
    (upperRosserFixedDepthMeshWidth_pos hc1 m).le
  have hdarboux :=
    hN m hm s hs a ha (min b (s / 3))
      (upperRosserFixedDepthMeshWidth c m)
  have hscreen :=
    integral_screened_outerRosserBoundaryMassAux_succ_le_massAux
      k (hc.trans_le ha.1) hscreenLower hb1 hwidth rfl
  have hintegralEq :
      (∫ x₀ in Set.Ioo c 1, x₀⁻¹ *
          (if x₀ < min b (s / 3) + upperRosserFixedDepthMeshWidth c m then
            ∫ x₁ in Set.Ioo a x₀,
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - x₀ - x₁) a x₁
          else 0)) =
        ∫ x₀ in Set.Ioo a 1, x₀⁻¹ *
          (if x₀ < min b (s / 3) + upperRosserFixedDepthMeshWidth c m then
            ∫ x₁ in Set.Ioo a x₀,
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - x₀ - x₁) a x₁
          else 0) := by
    apply MeasureTheory.setIntegral_eq_of_subset_of_forall_sdiff_eq_zero
      measurableSet_Ioo
    · intro x hx
      exact ⟨ha.1.trans_lt hx.1, hx.2⟩
    · intro x hx
      have hxa : x ≤ a := le_of_not_gt fun hax => hx.2 ⟨hax, hx.1.2⟩
      have hempty : Set.Ioo a x = ∅ := Set.Ioo_eq_empty (not_lt.mpr hxa)
      simp [hempty]
  rw [hintegralEq] at hdarboux
  linarith

/-- Corrected form of the induction-closed outer quadrature.  The local-product
correction is absorbed uniformly while both the true lower cutoff and inherited
upper face remain variable. -/
theorem
    exists_upperRosserFixedDepthMesh_correctedScreenedOuterDarboux_succ_movingLower_le_massAux_add
    (k : ℕ) {K s₀ s₁ c ε ρ : ℝ} (hK : 0 ≤ K)
    (hc : 0 < c) (hc1 : c < 1) (hε : 0 < ε) (hρ : 0 < ρ) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∃ z₀ : ℝ, 2 ≤ z₀ ∧
      ∀ z : ℝ, z₀ ≤ z → ∀ s ∈ Set.Icc s₀ s₁,
        ∀ a ∈ Set.Icc c 1, ∀ b : ℝ, b ≤ 1 → a ≤ min b (s / 3) →
        (∑ j : Fin (m + 1),
            (if upperRosserFixedDepthMeshRight c m j ≤
                min b (s / 3) + upperRosserFixedDepthMeshWidth c m then
              ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
                x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                  (s - upperRosserFixedDepthMeshRight c m j - x₁) a x₁
            else 0) *
              (upperRosserFixedDepthMeshRight c m j /
                    upperRosserFixedDepthMeshLeft c m j *
                (1 + K / (upperRosserFixedDepthMeshLeft c m j *
                  Real.log z)) - 1)) ≤
          LinearSieve.upperRosserBoundaryMassAux (k + 2) s a b +
            (a⁻¹ * a⁻¹) ^ (k + 2) *
              upperRosserFixedDepthMeshWidth c m +
            ε / c +
            (c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)) *
              upperRosserFixedDepthMeshWidth c m / c ^ 2 + ρ := by
  obtain ⟨N, hscreened⟩ :=
    exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_movingLower_le_massAux_add
      k (s₀ := s₀) (s₁ := s₁) hc hc1 hε
  refine ⟨N, ?_⟩
  intro m hm
  let B := c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1)
  have hB : 0 ≤ B := by
    dsimp [B]
    positivity
  obtain ⟨z₀, hz₀, hcorrection⟩ :=
    exists_upperRosserFixedDepthMesh_correctedDarboux_le_add
      m hK hρ hB hc hc1
  refine ⟨z₀, hz₀, ?_⟩
  intro z hz s hs a ha b hb1 hscreenLower
  let M : Fin (m + 1) → ℝ := fun j =>
    if upperRosserFixedDepthMeshRight c m j ≤
        min b (s / 3) + upperRosserFixedDepthMeshWidth c m then
      ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
        x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
          (s - upperRosserFixedDepthMeshRight c m j - x₁) a x₁
    else 0
  have hM : ∀ j, 0 ≤ M j ∧ M j ≤ B := by
    intro j
    by_cases hj : upperRosserFixedDepthMeshRight c m j ≤
        min b (s / 3) + upperRosserFixedDepthMeshWidth c m
    · simp only [M, if_pos hj]
      constructor
      · apply MeasureTheory.integral_nonneg_of_ae
        filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ioo] with x hx
        exact mul_nonneg
          (inv_nonneg.mpr ((hc.le.trans ha.1).trans hx.1.le))
          (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1)
            (hc.le.trans ha.1))
      · have hbound :=
          LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
            (k + 1) (s := s) (hc.trans_le ha.1)
              (upperRosserFixedDepthMeshRight_le_one hc1 m j)
        dsimp [B]
        calc
          (∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight c m j),
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight c m j - x₁) a x₁) ≤
              a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1) := hbound
          _ ≤ c⁻¹ * (c⁻¹ * c⁻¹) ^ (k + 1) := by
            have hainv : a⁻¹ ≤ c⁻¹ :=
              (inv_le_inv₀ (hc.trans_le ha.1) hc).2 ha.1
            have hainvNonneg : 0 ≤ a⁻¹ := inv_nonneg.mpr (hc.le.trans ha.1)
            have hcinvNonneg : 0 ≤ c⁻¹ := inv_nonneg.mpr hc.le
            have hsquare : a⁻¹ * a⁻¹ ≤ c⁻¹ * c⁻¹ :=
              mul_le_mul hainv hainv hainvNonneg hcinvNonneg
            exact mul_le_mul hainv
              (pow_le_pow_left₀ (mul_nonneg hainvNonneg hainvNonneg)
                hsquare (k + 1))
              (pow_nonneg (mul_nonneg hainvNonneg hainvNonneg) _)
              hcinvNonneg
    · simp [M, hj, hB]
  have hcorrected := hcorrection z hz M hM
  have hpure := hscreened m hm s hs a ha b hb1 hscreenLower
  dsimp [M, B] at hcorrected
  linarith

/-- The screened outer Darboux sum is bounded directly by the next continuous
Rosser mass, with explicit losses for the one-cell moving-face thickening and
for right-endpoint quadrature. -/
theorem exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_le_mass_add
    (k : ℕ) {s₀ s₁ a ε : ℝ} (ha : 0 < a) (ha1 : a < 1) (hε : 0 < ε) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∀ s ∈ Set.Icc s₀ s₁,
      a ≤ min 1 (s / 3) →
      (∑ j : Fin (m + 1),
          (if upperRosserFixedDepthMeshRight a m j <
              min 1 (s / 3) + upperRosserFixedDepthMeshWidth a m then
            ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight a m j),
              x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                (s - upperRosserFixedDepthMeshRight a m j - x₁) a x₁
          else 0) *
            (upperRosserFixedDepthMeshRight a m j /
              upperRosserFixedDepthMeshLeft a m j - 1)) ≤
        LinearSieve.upperRosserBoundaryMassAux (k + 2) s a 1 +
          (a⁻¹ * a⁻¹) ^ (k + 2) *
            upperRosserFixedDepthMeshWidth a m +
          ε / a +
          (a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)) *
            upperRosserFixedDepthMeshWidth a m / a ^ 2 := by
  obtain ⟨N, hN⟩ :=
    exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_le_integral_add
      k (s₀ := s₀) (s₁ := s₁) ha ha1 hε
  refine ⟨N, ?_⟩
  intro m hm s hs hscreenLower
  have hwidth : 0 ≤ upperRosserFixedDepthMeshWidth a m :=
    (upperRosserFixedDepthMeshWidth_pos ha1 m).le
  have hdarboux :=
    hN m hm s hs (min 1 (s / 3)) (upperRosserFixedDepthMeshWidth a m)
  have hscreen :=
    integral_screened_outerRosserBoundaryMassAux_succ_le
      k ha hscreenLower (min_le_left _ _) hwidth rfl
  linarith

/-- The complete corrected outer mesh sum is bounded by the next continuous
Rosser mass.  Both the local-product correction and the moving-face cell are
absorbed into explicit errors. -/
theorem
    exists_upperRosserFixedDepthMesh_correctedScreenedOuterDarboux_succ_le_mass_add
    (k : ℕ) {K s₀ s₁ a ε ρ : ℝ} (hK : 0 ≤ K)
    (ha : 0 < a) (ha1 : a < 1) (hε : 0 < ε) (hρ : 0 < ρ) :
    ∃ N : ℕ, ∀ m, N ≤ m → ∃ z₀ : ℝ, 2 ≤ z₀ ∧
      ∀ z : ℝ, z₀ ≤ z → ∀ s ∈ Set.Icc s₀ s₁,
        a ≤ min 1 (s / 3) →
        (∑ j : Fin (m + 1),
            (if upperRosserFixedDepthMeshRight a m j <
                min 1 (s / 3) + upperRosserFixedDepthMeshWidth a m then
              ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight a m j),
                x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
                  (s - upperRosserFixedDepthMeshRight a m j - x₁) a x₁
            else 0) *
              (upperRosserFixedDepthMeshRight a m j /
                    upperRosserFixedDepthMeshLeft a m j *
                (1 + K / (upperRosserFixedDepthMeshLeft a m j *
                  Real.log z)) - 1)) ≤
          LinearSieve.upperRosserBoundaryMassAux (k + 2) s a 1 +
            (a⁻¹ * a⁻¹) ^ (k + 2) *
              upperRosserFixedDepthMeshWidth a m +
            ε / a +
            (a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)) *
              upperRosserFixedDepthMeshWidth a m / a ^ 2 + ρ := by
  obtain ⟨N, hscreened⟩ :=
    exists_upperRosserFixedDepthMesh_screenedOuterDarboux_succ_le_mass_add
      k (s₀ := s₀) (s₁ := s₁) ha ha1 hε
  refine ⟨N, ?_⟩
  intro m hm
  let B := a⁻¹ * (a⁻¹ * a⁻¹) ^ (k + 1)
  have hB : 0 ≤ B := by
    dsimp [B]
    positivity
  obtain ⟨z₀, hz₀, hcorrection⟩ :=
    exists_upperRosserFixedDepthMesh_correctedDarboux_le_add
      m hK hρ hB ha ha1
  refine ⟨z₀, hz₀, ?_⟩
  intro z hz s hs hscreenLower
  let M : Fin (m + 1) → ℝ := fun j =>
    if upperRosserFixedDepthMeshRight a m j <
        min 1 (s / 3) + upperRosserFixedDepthMeshWidth a m then
      ∫ x₁ in Set.Ioo a (upperRosserFixedDepthMeshRight a m j),
        x₁⁻¹ * LinearSieve.upperRosserBoundaryMassAux (k + 1)
          (s - upperRosserFixedDepthMeshRight a m j - x₁) a x₁
    else 0
  have hM : ∀ j, 0 ≤ M j ∧ M j ≤ B := by
    intro j
    by_cases hj : upperRosserFixedDepthMeshRight a m j <
        min 1 (s / 3) + upperRosserFixedDepthMeshWidth a m
    · simp only [M, if_pos hj]
      constructor
      · apply MeasureTheory.integral_nonneg_of_ae
        filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ioo] with x hx
        exact mul_nonneg (inv_nonneg.mpr (ha.le.trans hx.1.le))
          (LinearSieve.upperRosserBoundaryMassAux_nonneg (k + 1) ha.le)
      · exact LinearSieve.integral_inv_mul_upperRosserBoundaryMassAux_le
          (k + 1) ha (upperRosserFixedDepthMeshRight_le_one ha1 m j)
    · simp [M, hj, hB]
  have hcorrected := hcorrection z hz M hM
  have hpure := hscreened m hm s hs hscreenLower
  dsimp [M, B] at hcorrected
  linarith

/-- Uniform inner Stieltjes comparison for the terminal depth-zero residual.
After the ordering constraints are imposed, its support is the single moving
logarithmic interval defining `upperRosserBoundaryLogKernel`. -/
theorem
    exists_sum_nu_div_one_sub_mul_upperRosserBoundaryMassAux_zero_le_logKernel_add_screened
    (K ρ c : ℝ) (hK : 1 ≤ K) (hρ : 0 < ρ) (hc : 0 < c)
    (hc1 : c < 1) :
    ∃ z₀ : ℝ, 2 ≤ z₀ ∧
      ∀ (S : BoundingSieve) (z s x₀ a : ℝ) (T : Finset ℕ),
        z₀ ≤ z → HasDimensionOneLocalProductBound S K →
        c ≤ a → x₀ ≤ 1 →
        T ⊆ S.prodPrimes.primeFactors →
        (∀ p ∈ T,
          a < Real.log p / Real.log z ∧ Real.log p / Real.log z < x₀) →
        ∑ p ∈ T, (S.nu p / (1 - S.nu p)) *
            LinearSieve.upperRosserBoundaryMassAux 0
              (s - x₀ - Real.log p / Real.log z) a
              (Real.log p / Real.log z) ≤
          LinearSieve.upperRosserBoundaryLogKernel s a x₀ + ρ := by
  obtain ⟨z₀, hz₀, hinterval⟩ :=
    exists_weighted_sum_nu_div_one_sub_le_integral_Ioo_add_screened
      K ρ 1 0 c hK hρ (by norm_num) (by norm_num) hc hc1
  refine ⟨z₀, hz₀, ?_⟩
  intro S z s x₀ a T hz hlocal ha hx₀ hT hcoord
  let d : ℝ := max a (s - x₀ - 3 * a)
  let mass : ℕ → ℝ := fun p =>
    LinearSieve.upperRosserBoundaryMassAux 0
      (s - x₀ - Real.log p / Real.log z) a
      (Real.log p / Real.log z)
  by_cases hdx₀ : d < x₀
  · let U : Finset ℕ := T.filter (fun p => mass p ≠ 0)
    have hsum :
        (∑ p ∈ T, (S.nu p / (1 - S.nu p)) * mass p) =
          ∑ p ∈ U, mass p * (S.nu p / (1 - S.nu p)) := by
      calc
        (∑ p ∈ T, (S.nu p / (1 - S.nu p)) * mass p) =
            ∑ p ∈ T, mass p * (S.nu p / (1 - S.nu p)) := by
          apply Finset.sum_congr rfl
          intro p hp
          ring
        _ = ∑ p ∈ U, mass p * (S.nu p / (1 - S.nu p)) := by
          symm
          rw [Finset.sum_filter]
          apply Finset.sum_congr rfl
          intro p hp
          by_cases hmass : mass p ≠ 0
          · simp [hmass]
          · simp [not_ne_iff.mp hmass]
    have hU : U ⊆ S.prodPrimes.primeFactors := by
      intro p hp
      exact hT (Finset.mem_filter.mp hp).1
    have hcoordU : ∀ p ∈ U,
        Real.log p / Real.log z ∈ Set.Icc d x₀ := by
      intro p hp
      have hp' := Finset.mem_filter.mp hp
      have hpcoord := hcoord p hp'.1
      have hres :
          0 ≤ s - x₀ - Real.log p / Real.log z ∧
            s - x₀ - Real.log p / Real.log z < 3 * a := by
        have hmass := hp'.2
        dsimp [mass] at hmass
        by_cases hres :
            0 ≤ s - x₀ - Real.log p / Real.log z ∧
              s - x₀ - Real.log p / Real.log z < 3 * a
        · exact hres
        · simp at hmass
          exact (hres ⟨by linarith [hmass.1], hmass.2⟩).elim
      constructor
      · dsimp [d]
        exact max_le hpcoord.1.le (by linarith [hres.2])
      · exact hpcoord.2.le
    have hinv :
        MeasureTheory.IntegrableOn (fun x : ℝ => x⁻¹)
          (Set.Ioo c 1) := by
      apply (intervalIntegrable_iff_integrableOn_Ioo_of_le hc1.le).1
      apply intervalIntegral.intervalIntegrable_inv (f := fun x : ℝ => x)
      · intro x hx
        rw [Set.uIcc_of_le hc1.le] at hx
        exact ne_of_gt (hc.trans_le hx.1)
      · exact continuous_id.continuousOn
    have hcomparison :=
      hinterval S z U mass (fun _ => (1 : ℝ)) d x₀ hz hlocal hU
        (ha.trans (le_max_left _ _))
        hdx₀.le hx₀ hcoordU
        (by intro x hx; norm_num)
        (by intro x hx; norm_num)
        (by intro x hx y hy; norm_num)
        (by simpa using hinv)
        (by
          intro p hp
          dsimp [mass]
          split_ifs <;> norm_num)
    have hintegral :
        (∫ x in Set.Ioo d x₀, x⁻¹) =
          LinearSieve.upperRosserBoundaryLogKernel s a x₀ := by
      rw [LinearSieve.upperRosserBoundaryLogKernel, if_pos hdx₀]
      rw [← MeasureTheory.integral_Ioc_eq_integral_Ioo,
        ← intervalIntegral.integral_of_le hdx₀.le,
        integral_inv_of_pos]
      · exact hc.trans_le (ha.trans (le_max_left _ _))
      · exact (hc.trans_le (ha.trans (le_max_left _ _))).trans hdx₀
    change (∑ p ∈ T, (S.nu p / (1 - S.nu p)) * mass p) ≤ _
    rw [hsum]
    calc
      (∑ p ∈ U, mass p * (S.nu p / (1 - S.nu p))) ≤
          (∫ x in Set.Ioo d x₀, x⁻¹) + ρ := by simpa using hcomparison
      _ = LinearSieve.upperRosserBoundaryLogKernel s a x₀ + ρ := by
        rw [hintegral]
  · have hmass : ∀ p ∈ T, mass p = 0 := by
      intro p hp
      have hpcoord := hcoord p hp
      dsimp [mass]
      apply if_neg
      intro hres
      have hdxp : d < Real.log p / Real.log z := by
        dsimp [d]
        exact max_lt hpcoord.1 (by linarith [hres.2])
      exact hdx₀ (hdxp.trans hpcoord.2)
    change (∑ p ∈ T, (S.nu p / (1 - S.nu p)) * mass p) ≤ _
    rw [Finset.sum_eq_zero (fun p hp => by simp [hmass p hp])]
    rw [LinearSieve.upperRosserBoundaryLogKernel, if_neg hdx₀]
    simpa using hρ.le

/-- Compatibility specialization of the terminal inner comparison to the
traditional one-sixth screen. -/
theorem
    exists_sum_nu_div_one_sub_mul_upperRosserBoundaryMassAux_zero_le_logKernel_add
    (K ρ : ℝ) (hK : 1 ≤ K) (hρ : 0 < ρ) :
    ∃ z₀ : ℝ, 2 ≤ z₀ ∧
      ∀ (S : BoundingSieve) (z s x₀ a : ℝ) (T : Finset ℕ),
        z₀ ≤ z → HasDimensionOneLocalProductBound S K →
        1 / 6 ≤ a → x₀ ≤ 1 →
        T ⊆ S.prodPrimes.primeFactors →
        (∀ p ∈ T,
          a < Real.log p / Real.log z ∧ Real.log p / Real.log z < x₀) →
        ∑ p ∈ T, (S.nu p / (1 - S.nu p)) *
            LinearSieve.upperRosserBoundaryMassAux 0
              (s - x₀ - Real.log p / Real.log z) a
              (Real.log p / Real.log z) ≤
          LinearSieve.upperRosserBoundaryLogKernel s a x₀ + ρ :=
  exists_sum_nu_div_one_sub_mul_upperRosserBoundaryMassAux_zero_le_logKernel_add_screened
    K ρ (1 / 6) hK hρ (by norm_num) (by norm_num)

end MathlibNt.SieveTheory.SwitchingPrinciple
