#!/usr/bin/env python3
"""Generate LeanArchitect annotations from the reviewed mathematical catalogue."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Imported upstream annotations are outside this project's editorial projection.
# This excludes labels, not Lean declarations or proof dependencies.
EXCLUDED = [
    'ZetaUpperBnd', 'ResidueTheoremOnRectangleWithSimplePole', 'MediumPNT',
    'Smooth1Properties_below', 'Smooth1Properties_above', 'Smooth1',
    'RectangleIntegral', 'pi_alt', 'Smooth1Nonneg', 'HolomorphicOn.vanishesOnRectangle',
    'Smooth1ContinuousAt', 'existsDifferentiableOn_of_bddAbove',
    'SmoothedChebyshevDirichlet_aux_integrable', 'MellinOfSmooth1b',
    'Smooth1LeOne', 'VerticalIntegral',
]


def generate(nodes):
    labels = [node['label'] for node in nodes]
    declarations = [node['declaration'] for node in nodes]
    if len(set(labels)) != len(labels) or len(set(declarations)) != len(declarations):
        raise ValueError('Blueprint labels and declarations must be unique')
    if set(labels) & set(EXCLUDED):
        raise ValueError('A selected label cannot also be excluded')
    blocks = []
    exclusions = ', '.join('-' + json.dumps(label) for label in EXCLUDED)
    for node in nodes:
        statement = node['statement']
        if '-/' in statement or any(ord(c) < 32 and c != '\n' for c in statement):
            raise ValueError('Invalid statement text: ' + node['label'])
        blocks.append(
            'attribute [blueprint ' + json.dumps(node['label']) + '\n'
            + '  (title := ' + json.dumps(node['title'], ensure_ascii=False) + ')\n'
            + '  (statement := /-- ' + statement + ' -/)\n'
            + '  (proofUses := [' + exclusions + '])]\n'
            + '  ' + node['declaration'] + '\n'
        )
    return ('import Architect\nimport Goldbach.All\n\n'
            '/-! Generated by scripts/generate_blueprint.py from blueprint/nodes.json.\n'
            'The mathematical exposition is curated; theorem proofs are unchanged. -/\n\n'
            + '\n'.join(blocks))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate(json.loads((ROOT / 'blueprint/nodes.json').read_text()))
    path = ROOT / 'Goldbach/Blueprint.lean'
    if args.check:
        if path.read_text() != result:
            raise SystemExit('Regenerate annotations: python3 scripts/generate_blueprint.py')
        print('Blueprint annotations match the mathematical catalogue.')
    else:
        path.write_text(result)
        print('Generated ' + str(path.relative_to(ROOT)))


if __name__ == '__main__':
    main()
