import MathlibNt.Wu2008DoubleSieve.GeoMassReductionRectangle

/-! Positive logarithmic fibre primitives; no simplex formula is postulated. -/
namespace Wu2008DoubleSieve.SecondFunctionalGeometricMass
open Set MeasureTheory

/-- The actual primitive used in induction over ordered pure-density fibres. -/
theorem log_power_integral (n : ℕ) {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    (∫ x in a..b, Real.log (x/a)^n / x) =
      Real.log (b/a)^(n+1) / (n+1 : ℕ) := by
  have hlog : ContinuousOn (fun x : ℝ => Real.log (x/a)) (Icc a b) :=
    (continuousOn_id.div_const a).log
      (fun x hx => ne_of_gt (div_pos (ha.trans_le hx.1) ha))
  have hc : ContinuousOn (fun x : ℝ => Real.log (x/a)^n / x) (Icc a b) :=
    (hlog.pow n).div continuousOn_id (fun x hx => ne_of_gt (ha.trans_le hx.1))
  have hd : ∀ x ∈ uIcc a b, HasDerivAt
      (fun y : ℝ => Real.log (y/a)^(n+1) / (n+1 : ℕ))
      (Real.log (x/a)^n / x) x := by
    intro x hx
    rw [uIcc_of_le hab] at hx
    have hx0 : x ≠ 0 := ne_of_gt (ha.trans_le hx.1)
    have hl : HasDerivAt (fun y : ℝ => Real.log (y/a)) (1/x) x := by
      convert! (Real.hasDerivAt_log (div_ne_zero hx0 ha.ne')).comp x
        ((hasDerivAt_id x).div_const a) using 1
      field_simp
    convert! (hl.pow (n+1)).div_const ((n+1 : ℕ) : ℝ) using 1
    simp only [Nat.add_sub_cancel]
    have hn : ((n+1 : ℕ) : ℝ) ≠ 0 := by positivity
    field_simp
  have h := intervalIntegral.integral_eq_sub_of_hasDerivAt hd
    (hc.intervalIntegrable_of_Icc hab)
  simpa only [div_self ha.ne', Real.log_one, zero_pow (Nat.succ_ne_zero n),
    zero_div, sub_zero] using h

/-- The factorial is generated by integrating one more pure-density coordinate. -/
theorem factorial_fibre_step (n : ℕ) {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    (∫ x in a..b, Real.log (x/a)^n / ((n.factorial : ℝ) * x)) =
      Real.log (b/a)^(n+1) / ((n+1).factorial : ℝ) := by
  calc
    _ = (1 / (n.factorial : ℝ)) * (∫ x in a..b, Real.log (x/a)^n / x) := by
      rw [← intervalIntegral.integral_const_mul]
      apply intervalIntegral.integral_congr
      intro x _hx
      ring
    _ = _ := by
      rw [log_power_integral n ha hab, Nat.factorial_succ, Nat.cast_mul, Nat.cast_add,
        Nat.cast_one]
      simp only [div_eq_mul_inv, mul_inv_rev, one_mul]
      ring

/-- Every logarithmic kernel in the proposed one-dimensional reduction is integrable. -/
theorem log_kernel_integrable (j k : ℕ) {a b : ℝ} (ha : 0 < a) :
    IntegrableOn (fun x : ℝ =>
      Real.log (x/a)^j * Real.log (b/x)^k / x^2) (Icc a b) := by
  apply ContinuousOn.integrableOn_Icc
  have hleft : ContinuousOn (fun x : ℝ => Real.log (x/a)) (Icc a b) :=
    (continuousOn_id.div_const a).log
      (fun x hx => ne_of_gt (div_pos (ha.trans_le hx.1) ha))
  have hright : ContinuousOn (fun x : ℝ => Real.log (b/x)) (Icc a b) :=
    (continuousOn_const.div continuousOn_id
      (fun x hx => ne_of_gt (ha.trans_le hx.1))).log
      (fun x hx => ne_of_gt (div_pos ((ha.trans_le hx.1).trans_le hx.2)
        (ha.trans_le hx.1)))
  exact ((hleft.pow j).mul (hright.pow k)).div (continuousOn_id.pow 2)
    (fun x hx => pow_ne_zero 2 (ne_of_gt (ha.trans_le hx.1)))

end Wu2008DoubleSieve.SecondFunctionalGeometricMass
